/* Sequences */
DROP SEQUENCE OBJECT_SEQ;
CREATE SEQUENCE OBJECT_SEQ NOCACHE;

DROP SEQUENCE ANNOTATION_SEQ;
CREATE SEQUENCE ANNOTATION_SEQ NOCACHE;

DROP SEQUENCE ALIAS_SEQ;
CREATE SEQUENCE ALIAS_SEQ NOCACHE;

DROP SEQUENCE RELATION_SEQ;
CREATE SEQUENCE RELATION_SEQ NOCACHE;

DROP SEQUENCE URL_SEQ;
CREATE SEQUENCE URL_SEQ NOCACHE;

DROP SEQUENCE TAG_SEQ;
CREATE SEQUENCE TAG_SEQ NOCACHE;

/* Source */
DROP TABLE SOURCE CASCADE CONSTRAINTS;
CREATE TABLE SOURCE ( 
SOURCE_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
BUD_ID INTEGER,
DESCRIPTION VARCHAR2(400),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT SOURCE_PK PRIMARY KEY (SOURCE_ID), 
CONSTRAINT SOURCE_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
GRANT SELECT ON SOURCE TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON SOURCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON SOURCE TO AUXILIARY;

DROP TABLE TAG CASCADE CONSTRAINTS;
CREATE TABLE TAG (
TAG_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT TAG_PK PRIMARY KEY (TAG_ID) ,
CONSTRAINT TAG_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX TAG_SOURCE_FK ON TAG (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE TAG
ADD CONSTRAINT TAG_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON TAG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON TAG TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON TAG TO AUXILIARY;

/* Bioentity */
DROP TABLE BIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY (
BIOENTITY_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
SGDID VARCHAR2(40),
UNIPROTID VARCHAR2(40),
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('LOCUS', 'REFERENCE', 'COMPLEX', 'PATHWAY', 'STRAIN')),
BIOENT_STATUS VARCHAR2(40),
DESCRIPTION VARCHAR2(400),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT BIOENTITY_PK PRIMARY KEY (BIOENTITY_ID),
CONSTRAINT BIOENTITY_UK UNIQUE (FORMAT_NAME, SUBCLASS),
CONSTRAINT BIOENTITY_SGD_UK UNIQUE(SGDID)) TABLESPACE DATA1;
CREATE INDEX BIOENT_SOURCE_FK ON BIOENTITY (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITY
ADD CONSTRAINT BIOENT_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITY TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON BIOENTITY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY TO AUXILIARY;

DROP TABLE LOCUSBIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE LOCUSBIOENTITY (
BIOENTITY_ID INTEGER NOT NULL,
LOCUS_TYPE VARCHAR2(40) NOT NULL,
NAME_DESCRIPTION VARCHAR2(100),
HEADLINE VARCHAR2(70),
GENE_NAME VARCHAR2(100),
QUALIFIER VARCHAR2(40),
GENETIC_POSITION DECIMAL(7, 3) NULL,
CONSTRAINT LOCUSBIOENTITY_PK PRIMARY KEY (BIOENTITY_ID) ) TABLESPACE DATA1;
ALTER TABLE LOCUSBIOENTITY
ADD CONSTRAINT LOCUS_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID);
GRANT SELECT ON LOCUSBIOENTITY TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUSBIOENTITY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUSBIOENTITY TO AUXILIARY;

DROP TABLE LOCUS_ALIAS CASCADE CONSTRAINTS;
CREATE TABLE LOCUS_ALIAS (
ALIAS_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
LOCUS_ID INTEGER NOT NULL,
IS_EXTERNAL_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT LOCUS_ALIAS_PK PRIMARY KEY (ALIAS_ID),
CONSTRAINT LOCUS_ALIAS_UK UNIQUE (LOCUS_ID, DISPLAY_NAME, CATEGORY) ) TABLESPACE DATA1;
CREATE INDEX LOCUS_ALIAS_LOCUS_FK_INDEX ON LOCUS_ALIAS (LOCUS_ID) TABLESPACE DATA1;
CREATE INDEX LOCUS_ALIAS_SOURCE_FK_INDEX ON LOCUS_ALIAS (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE LOCUS_ALIAS
ADD CONSTRAINT LOCUS_ALIAS_LOCUS_FK FOREIGN KEY (LOCUS_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LOCUS_ALIAS
ADD CONSTRAINT LOCUS_ALIAS_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON LOCUS_ALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUS_ALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUS_ALIAS TO AUXILIARY;

DROP TABLE LOCUS_RELATION CASCADE CONSTRAINTS;
CREATE TABLE LOCUS_RELATION (
RELATION_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
PARENT_ID INTEGER NOT NULL,
CHILD_ID INTEGER NOT NULL,
RELATION_TYPE VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT LOCUS_RELATION_PK PRIMARY KEY (RELATION_ID),
CONSTRAINT LOCUS_RELATION_UK UNIQUE(RELATION_TYPE, PARENT_ID, CHILD_ID)) TABLESPACE DATA1;
CREATE INDEX LOCUS_REL_PARENT_FK_INDEX ON LOCUS_RELATION (PARENT_ID) TABLESPACE DATA1;
CREATE INDEX LOCUS_REL_CHILD_FK_INDEX ON LOCUS_RELATION (CHILD_ID) TABLESPACE DATA1;
CREATE INDEX LOCUS_REL_SOURCE_FK_INDEX ON LOCUS_RELATION (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE LOCUS_RELATION
ADD CONSTRAINT LOCUS_REL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LOCUS_RELATION
ADD CONSTRAINT LOCUS_REL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LOCUS_RELATION
ADD CONSTRAINT LOCUS_REL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON LOCUS_RELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUS_RELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUS_RELATION TO AUXILIARY;

DROP TABLE LOCUS_URL CASCADE CONSTRAINTS;
CREATE TABLE LOCUS_URL (
URL_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
LOCUS_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT LOCUS_URL_PK PRIMARY KEY (URL_ID),
CONSTRAINT LOCUS_URL_UK UNIQUE (LOCUS_ID, DISPLAY_NAME, CATEGORY) ) TABLESPACE DATA2;
CREATE INDEX LOCUS_URL_SOURCE_FK_INDEX ON LOCUS_URL (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX LOCUS_URL_LOCUS_FK_INDEX ON LOCUS_URL (LOCUS_ID) TABLESPACE DATA1;
ALTER TABLE LOCUS_URL
ADD CONSTRAINT LOCUS_URL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LOCUS_URL
ADD CONSTRAINT LOCUS_URL_LOCUS_FK FOREIGN KEY (LOCUS_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON LOCUS_URL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUS_URL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUS_URL TO AUXILIARY;

/* Reference */
DROP TABLE BOOK CASCADE CONSTRAINTS;
CREATE TABLE BOOK (
BOOK_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
TITLE VARCHAR2(200) NOT NULL,
VOLUME_TITLE VARCHAR2(200),
ISBN VARCHAR2(20),
TOTAL_PAGES INTEGER,
PUBLISHER VARCHAR2(100),
PUBLISHER_LOCATION VARCHAR2(100),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT BOOK_PK PRIMARY KEY (BOOK_ID),
CONSTRAINT BOOK_UK UNIQUE (TITLE, VOLUME_TITLE) ,
CONSTRAINT BOOK_FORMAT_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX BOOK_SOURCE_FK_INDEX ON BOOK (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE BOOK
ADD CONSTRAINT BOOK_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BOOK TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BOOK TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BOOK TO AUXILIARY;

DROP TABLE JOURNAL CASCADE CONSTRAINTS;
CREATE TABLE JOURNAL (
JOURNAL_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
MED_ABBR VARCHAR2(100),
TITLE VARCHAR2(200),
ISSN_PRINT VARCHAR2(20),
ISSN_ONLINE VARCHAR2(20),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT JOURNAL_PK PRIMARY KEY (JOURNAL_ID),
CONSTRAINT JOURNAL_UK UNIQUE (MED_ABBR, TITLE) ) TABLESPACE DATA1;
CREATE INDEX JOURNAL_SOURCE_FK_INDEX ON JOURNAL (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE JOURNAL
ADD CONSTRAINT JOURNAL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON JOURNAL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON JOURNAL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON JOURNAL TO AUXILIARY;

DROP TABLE REFERENCEBIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE REFERENCEBIOENTITY (
BIOENTITY_ID INTEGER NOT NULL,
FULLTEXT_STATUS VARCHAR2(40) NOT NULL,
CITATION VARCHAR2(500) NOT NULL,
YEAR INTEGER NOT NULL,
PUBMED_ID INTEGER,
PUBMED_CENTRAL_ID VARCHAR2(40),
DATE_PUBLISHED VARCHAR2(40),
DATE_REVISED VARCHAR2(40),
ISSUE VARCHAR2(40),
PAGE VARCHAR2(40),
VOLUME VARCHAR2(40),
TITLE VARCHAR2(400),
JOURNAL_ID INTEGER,
BOOK_ID INTEGER,
DOI VARCHAR2(100),
CONSTRAINT REFERENCE_PK PRIMARY KEY (BIOENTITY_ID),
CONSTRAINT REFERENCE_CITATION_UK UNIQUE (CITATION)) TABLESPACE DATA2;
CREATE INDEX REF_BOOK_FK_INDEX ON REFERENCEBIOENTITY (BOOK_ID) TABLESPACE DATA2;
CREATE INDEX REF_JOURNAL_FK_INDEX ON REFERENCEBIOENTITY (JOURNAL_ID) TABLESPACE DATA2;
ALTER TABLE REFERENCEBIOENTITY
ADD CONSTRAINT REFERENCE_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID);
ALTER TABLE REFERENCEBIOENTITY
ADD CONSTRAINT REF_JOURNAL_FK FOREIGN KEY (JOURNAL_ID) REFERENCES JOURNAL (JOURNAL_ID)
ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCEBIOENTITY
ADD CONSTRAINT REF_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID)
ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCEBIOENTITY TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEBIOENTITY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEBIOENTITY TO AUXILIARY;

DROP TABLE REFERENCE_ALIAS CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE_ALIAS (
ALIAS_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
REFERENCE_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT REFERENCE_ALIAS_PK PRIMARY KEY (ALIAS_ID),
CONSTRAINT REFERENCE_ALIAS_UK UNIQUE (REFERENCE_ID, DISPLAY_NAME, CATEGORY) ) TABLESPACE DATA1;
CREATE INDEX REF_ALIAS_SOURCE_FK_INDEX ON REFERENCE_ALIAS (SOURCE_ID) TABLESPACE DATA1;
CREATE INDEX REF_ALIAS_REF_FK_INDEX ON REFERENCE_ALIAS (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCE_ALIAS
ADD CONSTRAINT REF_ALIAS_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE_ALIAS
ADD CONSTRAINT REF_ALIAS_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCEBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCE_ALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_ALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_ALIAS TO AUXILIARY;

DROP TABLE REFERENCE_RELATION CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE_RELATION (
RELATION_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
PARENT_ID INTEGER NOT NULL,
CHILD_ID INTEGER NOT NULL,
RELATION_TYPE VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT REFERENCE_RELATION_PK PRIMARY KEY (RELATION_ID),
CONSTRAINT REFERENCE_RELATION_UK UNIQUE(RELATION_TYPE, PARENT_ID, CHILD_ID)) TABLESPACE DATA1;
CREATE INDEX REF_REL_PARENT_FK_INDEX ON REFERENCE_RELATION (PARENT_ID) TABLESPACE DATA1;
CREATE INDEX REF_REL_CHILD_FK_INDEX ON REFERENCE_RELATION (CHILD_ID) TABLESPACE DATA1;
CREATE INDEX REF_REL_SOURCE_FK_INDEX ON REFERENCE_RELATION (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCE_RELATION
ADD CONSTRAINT REF_REL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES REFERENCEBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE_RELATION
ADD CONSTRAINT REF_REL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES REFERENCEBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE_RELATION
ADD CONSTRAINT REFERENCE_REL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCE_RELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_RELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_RELATION TO AUXILIARY;

DROP TABLE REFERENCE_URL CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE_URL (
URL_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
REFERENCE_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT REFERENCE_URL_PK PRIMARY KEY (URL_ID),
CONSTRAINT REFERENCE_URL_UK UNIQUE (REFERENCE_ID, DISPLAY_NAME, CATEGORY) ) TABLESPACE DATA2;
CREATE INDEX REF_URL_SOURCE_FK_INDEX ON REFERENCE_URL (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX REF_URL_REF_FK_INDEX ON REFERENCE_URL (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCE_URL
ADD CONSTRAINT REF_URL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE_URL
ADD CONSTRAINT REF_URL_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCEBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCE_URL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_URL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_URL TO AUXILIARY;

DROP TABLE REFTYPE CASCADE CONSTRAINTS;
CREATE TABLE REFTYPE ( 
REFTYPE_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT REFTYPE_PK PRIMARY KEY (REFTYPE_ID), 
CONSTRAINT REFTYPE_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX REFTYPE_SOURCE_FK_INDEX ON REFTYPE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE REFTYPE
ADD CONSTRAINT REFTYPE_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFTYPE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFTYPE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFTYPE TO AUXILIARY;

DROP TABLE AUTHOR CASCADE CONSTRAINTS;
CREATE TABLE AUTHOR ( 
AUTHOR_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID), 
CONSTRAINT AUTHOR_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX AUTHOR_SOURCE_FK_INDEX ON AUTHOR (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE AUTHOR
ADD CONSTRAINT AUTHOR_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUTHOR TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR TO AUXILIARY;

DROP TABLE EVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE EVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(300) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
ECO_ID VARCHAR2(40),
CATEGORY VARCHAR2(20),
DESCRIPTION VARCHAR2(1000), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT EVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT EVIDENCE_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX EV_SOURCE_FK_INDEX ON EVIDENCE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE EVIDENCE
ADD CONSTRAINT EV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON EVIDENCE TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON EVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE TO AUXILIARY;

DROP TABLE EVIDENCE_ALIAS CASCADE CONSTRAINTS;
CREATE TABLE EVIDENCE_ALIAS (
ALIAS_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
EVIDENCE_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT EVIDENCE_ALIAS_PK PRIMARY KEY (ALIAS_ID),
CONSTRAINT EVIDENCE_ALIAS_UK UNIQUE (EVIDENCE_ID, DISPLAY_NAME, CATEGORY) ) TABLESPACE DATA1;
CREATE INDEX EV_ALIAS_SOURCE_FK_INDEX ON EVIDENCE_ALIAS (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE EVIDENCE_ALIAS
ADD CONSTRAINT EV_ALIAS_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX EV_ALIAS_EV_FK_INDEX ON EVIDENCE_ALIAS (EVIDENCE_ID) TABLESPACE DATA1;
ALTER TABLE EVIDENCE_ALIAS
ADD CONSTRAINT EV_ALIAS_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON EVIDENCE_ALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE_ALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE_ALIAS TO AUXILIARY;

DROP TABLE EVIDENCE_RELATION CASCADE CONSTRAINTS;
CREATE TABLE EVIDENCE_RELATION (
RELATION_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
PARENT_ID INTEGER NOT NULL,
CHILD_ID INTEGER NOT NULL,
RELATION_TYPE VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT EVIDENCE_RELATION_PK PRIMARY KEY (RELATION_ID),
CONSTRAINT EVIDENCE_RELATION_UK UNIQUE(RELATION_TYPE, PARENT_ID, CHILD_ID)) TABLESPACE DATA1;
CREATE INDEX EV_REL_PARENT_FK_INDEX ON EVIDENCE_RELATION (PARENT_ID) TABLESPACE DATA1;
CREATE INDEX EV_REL_CHILD_FK_INDEX ON EVIDENCE_RELATION (CHILD_ID) TABLESPACE DATA1;
CREATE INDEX EV_REL_SOURCE_FK_INDEX ON EVIDENCE_RELATION (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE EVIDENCE_RELATION
ADD CONSTRAINT EV_REL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EVIDENCE_RELATION
ADD CONSTRAINT EV_REL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EVIDENCE_RELATION
ADD CONSTRAINT EV_REL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON EVIDENCE_RELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE_RELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE_RELATION TO AUXILIARY;

DROP TABLE ORGANISM CASCADE CONSTRAINTS;
CREATE TABLE ORGANISM (
ORGANISM_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
TAXON_ID INTEGER,
FULL_NAME VARCHAR2(500) NOT NULL,
GENUS VARCHAR2(40),
SPECIES VARCHAR2(40),
RANK VARCHAR2(40),
DESCRIPTION VARCHAR2(500),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT ORGANISM_PK PRIMARY KEY (ORGANISM_ID),
CONSTRAINT ORGANISM_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX ORGANISM_SOURCE_FK_INDEX ON ORGANISM (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE ORGANISM
ADD CONSTRAINT ORGANISM_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON ORGANISM TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON ORGANISM TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ORGANISM TO AUXILIARY;

DROP TABLE STRAINBIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE STRAINBIOENTITY (
BIOENTITY_ID INTEGER NOT NULL,
ORGANISM_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
GENOTYPE VARCHAR2(500),
GENBANK_ID VARCHAR2(40),
ASSEMBLY_SIZE INTEGER,
FOLD_COVERAGE INTEGER,
SCAFFOLD_NUMBER INTEGER,
LONGEST_SCAFFOLD INTEGER,
SCAFFOLD_NFIFTY INTEGER,
CONSTRAINT STRAINBIOENTITY_PK PRIMARY KEY (BIOENTITY_ID)) TABLESPACE DATA1;
CREATE INDEX STRAIN_ORGANISM_FK_INDEX ON STRAINBIOENTITY (ORGANISM_ID) TABLESPACE DATA1;
ALTER TABLE STRAINBIOENTITY
ADD CONSTRAINT STRAINBIOENTITY_BIOENTITY_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE STRAINBIOENTITY
ADD CONSTRAINT STRAIN_ORGNAISM_FK FOREIGN KEY (ORGANISM_ID) REFERENCES ORGANISM (ORGANISM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON STRAINBIOENTITY TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON STRAINBIOENTITY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAINBIOENTITY TO AUXILIARY;

DROP TABLE STRAIN_URL CASCADE CONSTRAINTS;
CREATE TABLE STRAIN_URL (
URL_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
STRAIN_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT STRAIN_URL_PK PRIMARY KEY (URL_ID),
CONSTRAINT STRAIN_URL_UK UNIQUE (STRAIN_ID, DISPLAY_NAME, CATEGORY) ) TABLESPACE DATA1;
CREATE INDEX STRAIN_URL_SOURCE_FK_INDEX ON STRAIN_URL (SOURCE_ID) TABLESPACE DATA1;
CREATE INDEX STRAIN_URL_STRAIN_FK_INDEX ON STRAIN_URL (STRAIN_ID) TABLESPACE DATA1;
ALTER TABLE STRAIN_URL
ADD CONSTRAINT STRAIN_URL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE STRAIN_URL
ADD CONSTRAINT STRAIN_URL_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAINBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON STRAIN_URL TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON STRAIN_URL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAIN_URL TO AUXILIARY;

DROP TABLE STRAIN_RELATION CASCADE CONSTRAINTS;
CREATE TABLE STRAIN_RELATION (
RELATION_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
PARENT_ID INTEGER NOT NULL,
CHILD_ID INTEGER NOT NULL,
RELATION_TYPE VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT STRAIN_RELATION_PK PRIMARY KEY (RELATION_ID),
CONSTRAINT STRAIN_RELATION_UK UNIQUE (RELATION_TYPE, PARENT_ID, CHILD_ID) ) TABLESPACE DATA1;
CREATE INDEX STRAIN_REL_PARENT_FK_INDEX ON STRAIN_RELATION (PARENT_ID) TABLESPACE DATA1;
CREATE INDEX STRAIN_REL_CHILD_FK_INDEX ON STRAIN_RELATION (CHILD_ID) TABLESPACE DATA1;
CREATE INDEX STRAIN_REL_SOURCE_FK_INDEX ON STRAIN_RELATION (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE STRAIN_RELATION
ADD CONSTRAINT STRAIN_REL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE STRAIN_RELATION
ADD CONSTRAINT STRAIN_REL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES STRAINBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE STRAIN_RELATION
ADD CONSTRAINT STRAIN_REL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES STRAINBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON STRAIN_RELATION TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON STRAIN_RELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAIN_RELATION TO AUXILIARY;

DROP TABLE CHEMICAL CASCADE CONSTRAINTS;
CREATE TABLE CHEMICAL (
CHEMICAL_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
CHEBI_ID VARCHAR2(50),
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT CHEMICAL_PK PRIMARY KEY (CHEMICAL_ID),
CONSTRAINT CHEMICAL_UK UNIQUE (FORMAT_NAME)) TABLESPACE DATA1;
CREATE INDEX CHEM_SOURCE_FK_INDEX ON CHEMICAL (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE CHEMICAL
ADD CONSTRAINT CHEM_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CHEMICAL TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON CHEMICAL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICAL TO AUXILIARY;

DROP TABLE CONTIG CASCADE CONSTRAINTS;
CREATE TABLE CONTIG (
CONTIG_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
STRAIN_ID INTEGER NOT NULL,
IS_CHROMOSOME INTEGER NOT NULL,
CENTROMERE_START INTEGER NULL,
CENTROMERE_END INTEGER NULL,
GENBANK_ACCESSION VARCHAR2(40),
GI_NUMBER VARCHAR2(40),
REFSEQ_ID VARCHAR2(40),
REFERENCE_CHROMOSOME_ID INTEGER,
REFERENCE_START INTEGER,
REFERENCE_END INTEGER,
REFERENCE_PERCENT_IDENTITY DECIMAL(7, 3),
REFERENCE_ALIGNMENT_LENGTH INTEGER,
HEADER VARCHAR2(200),
FILENAME VARCHAR2(200),
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT CONTIG_PK PRIMARY KEY (CONTIG_ID),
CONSTRAINT CONTIG_UK UNIQUE (FORMAT_NAME)) TABLESPACE DATA1;
CREATE INDEX CONTIG_SOURCE_FK_INDEX ON CONTIG (SOURCE_ID) TABLESPACE DATA1;
CREATE INDEX CONTIG_STRAIN_FK_INDEX ON CONTIG (STRAIN_ID) TABLESPACE DATA1;
ALTER TABLE CONTIG
ADD CONSTRAINT CONTIG_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE CONTIG
ADD CONSTRAINT CONTIG_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAINBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CONTIG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONTIG TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONTIG TO AUXILIARY;

DROP TABLE DATASET CASCADE CONSTRAINTS;
CREATE TABLE DATASET (
DATASET_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
GEO_ID VARCHAR2(40),
PCL_FILENAME VARCHAR2(100),
SHORT_DESCRIPTION VARCHAR2(400),
CHANNEL_COUNT INTEGER,
CONDITION_COUNT INTEGER,
REFERENCE_ID INTEGER,
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT DATASET_PK PRIMARY KEY (DATASET_ID),
CONSTRAINT DATASET_UK UNIQUE (FORMAT_NAME)) TABLESPACE DATA1;
CREATE INDEX DATASET_SOURCE_FK_INDEX ON DATASET (SOURCE_ID) TABLESPACE DATA1;
CREATE INDEX DATASET_REF_FK_INDEX ON DATASET (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE DATASET
ADD CONSTRAINT DATASET_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DATASET
ADD CONSTRAINT DATASET_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCEBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DATASET TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASET TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASET TO AUXILIARY;

DROP TABLE DATASET_TAG CASCADE CONSTRAINTS;
CREATE TABLE DATASET_TAG (
DATASET_TAG_ID INTEGER NOT NULL,
TAG_ID INTEGER NOT NULL,
DATASET_ID INTEGER NOT NULL,
CONSTRAINT DATASET_TAG_PK PRIMARY KEY (DATASET_TAG_ID),
CONSTRAINT DATASET_TAG_UK UNIQUE (TAG_ID, DATASET_ID)) TABLESPACE DATA1;
CREATE INDEX DATASET_TAG_DATASET_FK_INDEX ON DATASET_TAG (DATASET_ID) TABLESPACE DATA1;
ALTER TABLE DATASET_TAG
ADD CONSTRAINT DATASET_TAG_TAG_FK FOREIGN KEY (TAG_ID) REFERENCES TAG (TAG_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DATASET_TAG
ADD CONSTRAINT DATASET_TAG_DATASET_FK FOREIGN KEY (DATASET_ID) REFERENCES DATASET (DATASET_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DATASET_TAG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASET_TAG TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASET_TAG TO AUXILIARY;

DROP TABLE DATASETCOLUMN CASCADE CONSTRAINTS;
CREATE TABLE DATASETCOLUMN (
DATASETCOLUMN_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
DATASET_ID INTEGER,
FILE_ORDER INTEGER,
GEO_ID VARCHAR2(40),
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT DATASETCOLUMN_PK PRIMARY KEY (DATASETCOLUMN_ID),
CONSTRAINT DATASETCOLUMN_UK UNIQUE (FORMAT_NAME)) TABLESPACE DATA1;
CREATE INDEX DATASETCOL_SOURCE_FK_INDEX ON DATASETCOLUMN (SOURCE_ID) TABLESPACE DATA1;
CREATE INDEX DATASETCOL_DSET_FK_INDEX ON DATASETCOLUMN (DATASET_ID) TABLESPACE DATA1;
ALTER TABLE DATASETCOLUMN
ADD CONSTRAINT DSETCOLUMN_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DATASETCOLUMN
ADD CONSTRAINT DATASETCOL_DSET_FK FOREIGN KEY (DATASET_ID) REFERENCES DATASET (DATASET_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DATASETCOLUMN TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASETCOLUMN TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASETCOLUMN TO AUXILIARY;

DROP TABLE PROTEINDOMAIN CASCADE CONSTRAINTS;
CREATE TABLE PROTEINDOMAIN (
PROTEINDOMAIN_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
INTERPRO_ID VARCHAR2(20),
INTERPRO_DESCRIPTION VARCHAR2(500),
EXTERNAL_URL VARCHAR2(500),
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT PROTEINDOMAIN_PK PRIMARY KEY (PROTEINDOMAIN_ID),
CONSTRAINT PROTEINDOMAIN_UK UNIQUE (FORMAT_NAME)) TABLESPACE DATA1;
CREATE INDEX PROTEINDOMAIN_SOURCE_FK_INDEX ON PROTEINDOMAIN (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE PROTEINDOMAIN
ADD CONSTRAINT PROTEINDOMAIN_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PROTEINDOMAIN TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINDOMAIN TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINDOMAIN TO AUXILIARY;

DROP TABLE GOTERM CASCADE CONSTRAINTS;
CREATE TABLE GOTERM (
GOTERM_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
GO_ID VARCHAR2(12) NOT NULL,
GO_ASPECT VARCHAR2(40) NOT NULL,
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT GOTERM_PK PRIMARY KEY (GOTERM_ID),
CONSTRAINT GOTERM_UK UNIQUE (FORMAT_NAME),
CONSTRAINT GOTERM_BUD_UK UNIQUE (BUD_ID)) TABLESPACE DATA1;
CREATE INDEX GOTERM_GO_INDEX ON GOTERM (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE GOTERM
ADD CONSTRAINT GOTERM_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GOTERM TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOTERM TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOTERM TO AUXILIARY;

DROP TABLE GOTERM_ALIAS CASCADE CONSTRAINTS;
CREATE TABLE GOTERM_ALIAS (
ALIAS_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
GOTERM_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
NOTE VARCHAR2(1000) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT GOTERM_ALIAS_PK PRIMARY KEY (ALIAS_ID),
CONSTRAINT GOTERM_ALIAS_UK UNIQUE (GOTERM_ID, DISPLAY_NAME, CATEGORY),
CONSTRAINT GOTERM_ALIAS_BUD_UK UNIQUE (BUD_ID)) TABLESPACE DATA1;
CREATE INDEX GOTERM_ALIAS_SOURCE_FK_INDEX ON GOTERM_ALIAS (SOURCE_ID) TABLESPACE DATA1;
CREATE INDEX GOTERM_ALIAS_GOTERM_FK_INDEX ON GOTERM_ALIAS (GOTERM_ID) TABLESPACE DATA1;
ALTER TABLE GOTERM_ALIAS
ADD CONSTRAINT GOTERM_ALIAS_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOTERM_ALIAS
ADD CONSTRAINT GOTERM_ALIAS_GOTERM_FK FOREIGN KEY (GOTERM_ID) REFERENCES GOTERM (GOTERM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GOTERM_ALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOTERM_ALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOTERM_ALIAS TO AUXILIARY;

DROP TABLE OBSERVABLE CASCADE CONSTRAINTS;
CREATE TABLE OBSERVABLE (
OBSERVABLE_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
ANCESTOR_TYPE VARCHAR(40) NOT NULL,
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT OBSERVABLE_PK PRIMARY KEY (OBSERVABLE_ID),
CONSTRAINT OBSERVABLE_UK UNIQUE (FORMAT_NAME),
CONSTRAINT OBSERVABLE_BUD_UK UNIQUE (BUD_ID)) TABLESPACE DATA1;
CREATE INDEX OBSERVABLE_SOURCE_FK_INDEX ON OBSERVABLE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE OBSERVABLE
ADD CONSTRAINT OBSERVABLE_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON OBSERVABLE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON OBSERVABLE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON OBSERVABLE TO AUXILIARY;

DROP TABLE PHENOTYPE CASCADE CONSTRAINTS;
CREATE TABLE PHENOTYPE (
PHENOTYPE_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
OBSERVABLE_ID INTEGER NOT NULL,
QUALIFIER VARCHAR2(100),
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT PHENOTYPE_PK PRIMARY KEY (PHENOTYPE_ID),
CONSTRAINT PHENOTYPE_UK UNIQUE (FORMAT_NAME),
CONSTRAINT PHENOTYPE_BUD_UK UNIQUE (BUD_ID)) TABLESPACE DATA1;
CREATE INDEX PHENOTYPE_SOURCE_FK_INDEX ON PHENOTYPE (SOURCE_ID) TABLESPACE DATA1;
CREATE INDEX PHENOTYPE_OBSERVABLE_FK_INDEX ON PHENOTYPE (OBSERVABLE_ID) TABLESPACE DATA1;
ALTER TABLE PHENOTYPE
ADD CONSTRAINT PHENOTYPE_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPE
ADD CONSTRAINT PHENOTYPE_OBSERVABLE_FK FOREIGN KEY (OBSERVABLE_ID) REFERENCES OBSERVABLE (OBSERVABLE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHENOTYPE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPE TO AUXILIARY;

DROP TABLE RESERVEDNAME CASCADE CONSTRAINTS;
CREATE TABLE RESERVEDNAME (
RESERVEDNAME_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
SOURCE_ID INTEGER NOT NULL,
BUD_ID INTEGER,
LOCUS_ID INTEGER NULL,
REFERENCE_ID INTEGER NULL,
RESERVATION_DATE DATE NOT NULL,
EXPIRATION_DATE DATE NOT NULL,
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT RESERVEDNAME_PK PRIMARY KEY (RESERVEDNAME_ID),
CONSTRAINT RESERVEDNAME_UK UNIQUE (FORMAT_NAME),
CONSTRAINT RESERVEDNAME_BUD_UK UNIQUE (BUD_ID)) TABLESPACE DATA1;
CREATE INDEX RESERVEDNAME_SOURCE_FK_INDEX ON RESERVEDNAME (SOURCE_ID) TABLESPACE DATA1;
CREATE INDEX RESERVEDNAME_LOCUS_FK_INDEX ON RESERVEDNAME (LOCUS_ID) TABLESPACE DATA1;
CREATE INDEX RESERVEDNAME_REF_FK_INDEX ON RESERVEDNAME (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE RESERVEDNAME
ADD CONSTRAINT RESERVEDNAME_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE RESERVEDNAME
ADD CONSTRAINT RESERVEDNAME_LOCUS_FK FOREIGN KEY (LOCUS_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE RESERVEDNAME
ADD CONSTRAINT RN_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCEBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON RESERVEDNAME TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON RESERVEDNAME TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON RESERVEDNAME TO AUXILIARY;

/* ANNOTATION */
DROP TABLE ANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE ANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('PHENOTYPE', 'GO', 'GENINTERACTION', 'PHYSINTERACTION', 'BINDING', 'DOMAIN', 'LITERATURE', 'REGULATION', 'DNASEQUENCE', 'PROTEINSEQUENCE', 'BIOENTITY', 'ALIAS', 'PHOSPHORYLATION', 'PROTEINEXPERIMENT', 'EXPRESSION', 'HISTORY', 'PATHWAY')),
JSON VARCHAR2(4000),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT ANNOTATION_PK PRIMARY KEY (ANNOTATION_ID) ) TABLESPACE DATA2;
CREATE INDEX EV_SUBCLASS_INDEX ON ANNOTATION (SUBCLASS) TABLESPACE DATA2;
DROP SEQUENCE ANNOTATION_SEQ;
CREATE SEQUENCE ANNOTATION_SEQ NOCACHE;
GRANT SELECT ON ANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ANNOTATION TO AUXILIARY;

DROP TABLE ARCH_LITERATUREANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE ARCH_LITERATUREANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NULL,
TOPIC VARCHAR2(60) NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT ARCH_LITERATUREANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT ARCH_LITERATUREANNOTATION_UK UNIQUE (BIOENTITY_ID, REFERENCE_ID, TOPIC) ) TABLESPACE DATA2;
CREATE INDEX ARLITEV_REF_FK_INDEX ON ARCH_LITERATUREANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX ARLITEV_STRAIN_FK_INDEX ON ARCH_LITERATUREANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX ARLITEV_EXPT_FK_INDEX ON ARCH_LITERATUREANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX ARLITEV_SOURCE_FK_INDEX ON ARCH_LITERATUREANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX ARLITEV_BIOENT_FK_INDEX ON ARCH_LITERATUREANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE ARCH_LITERATUREANNOTATION
ADD CONSTRAINT ARLITEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREANNOTATION
ADD CONSTRAINT ARLITEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREANNOTATION
ADD CONSTRAINT ARLITEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREANNOTATION
ADD CONSTRAINT ARLITEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREANNOTATION
ADD CONSTRAINT ARLITEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREANNOTATION
ADD CONSTRAINT ARLITEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON ARCH_LITERATUREANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ARCH_LITERATUREANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ARCH_LITERATUREANNOTATION TO AUXILIARY;

DROP TABLE BINDINGANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE BINDINGANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
TOTAL_SCORE VARCHAR2(10) NOT NULL,
EXPERT_CONFIDENCE VARCHAR2(40) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
MOTIF_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT BINDINGANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT BINDINGANNOTATION_UK UNIQUE (BIOENTITY_ID, MOTIF_ID) ) TABLESPACE DATA2;
CREATE INDEX BINDEV_REF_FK_INDEX ON BINDINGANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX BINDEV_STRAIN_FK_INDEX ON BINDINGANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX BINDEV_EXPT_FK_INDEX ON BINDINGANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX BINDEV_SOURCE_FK_INDEX ON BINDINGANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX BINDEV_BIOENT_FK_INDEX ON BINDINGANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE BINDINGANNOTATION
ADD CONSTRAINT BINDEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGANNOTATION
ADD CONSTRAINT BINDEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGANNOTATION
ADD CONSTRAINT BINDEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGANNOTATION
ADD CONSTRAINT BINDEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGANNOTATION
ADD CONSTRAINT BINDEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGANNOTATION
ADD CONSTRAINT BINDEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BINDINGANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BINDINGANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BINDINGANNOTATION TO AUXILIARY;

DROP TABLE DNASEQUENCEANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE DNASEQUENCEANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
DNA_TYPE VARCHAR2(50) NOT NULL,
RESIDUES CLOB NOT NULL,
CONTIG_ID INTEGER NULL,
START_INDEX INTEGER NULL,
END_INDEX INTEGER NULL,
STRAND VARCHAR2(1),
HEADER VARCHAR2(200),
FILENAME VARCHAR2(200),
NOTE VARCHAR2(1000) NULL,
CONSTRAINT DNASEQUENCEANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT DNASEQUENCEANNOTATION_UK UNIQUE (BIOENTITY_ID, STRAIN_ID, DNA_TYPE) ) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_REF_FK_INDEX ON DNASEQUENCEANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_STRAIN_FK_INDEX ON DNASEQUENCEANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_EXPT_FK_INDEX ON DNASEQUENCEANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_SOURCE_FK_INDEX ON DNASEQUENCEANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_BIOENT_FK_INDEX ON DNASEQUENCEANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_CONTIG_FK_INDEX ON DNASEQUENCEANNOTATION	(CONTIG_ID) TABLESPACE DATA2;
ALTER TABLE DNASEQUENCEANNOTATION
ADD CONSTRAINT DNASEQEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEANNOTATION
ADD CONSTRAINT DNASEQEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEANNOTATION
ADD CONSTRAINT DNASEQEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEANNOTATION
ADD CONSTRAINT DNASEQEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEANNOTATION
ADD CONSTRAINT DNASEQEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEANNOTATION
ADD CONSTRAINT DNASEQEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEANNOTATION
ADD CONSTRAINT DNASEQEV_CONTIG_FK FOREIGN KEY (CONTIG_ID) REFERENCES CONTIGBIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DNASEQUENCEANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DNASEQUENCEANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DNASEQUENCEANNOTATION TO AUXILIARY;

DROP TABLE DOMAINANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE DOMAINANNOTATION ( 
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOITEM_ID INTEGER NOT NULL,
START_INDEX INTEGER, 
END_INDEX INTEGER, 
EVALUE VARCHAR2(40), 
DOMAIN_STATUS VARCHAR2(40), 
DATE_OF_RUN DATE,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT DOMAINANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT DOMAINANNOTATION_UK UNIQUE (BIOENTITY_ID, BIOITEM_ID, START_INDEX, END_INDEX) ) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_REF_FK_INDEX ON DOMAINANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_STRAIN_FK_INDEX ON DOMAINANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_EXPT_FK_INDEX ON DOMAINANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_SOURCE_FK_INDEX ON DOMAINANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_BIOENT_FK_INDEX ON DOMAINANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_DOMAIN_FK_INDEX ON DOMAINANNOTATION (BIOITEM_ID) TABLESPACE DATA2;
ALTER TABLE DOMAINANNOTATION 
ADD CONSTRAINT DOMAINEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINANNOTATION
ADD CONSTRAINT DOMAINEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINANNOTATION
ADD CONSTRAINT DOMAINEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINANNOTATION
ADD CONSTRAINT DOMAINEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINANNOTATION
ADD CONSTRAINT DOMAINEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINANNOTATION  
ADD CONSTRAINT DOMAINEV_DOMAIN_FK FOREIGN KEY (BIOITEM_ID) REFERENCES DOMAINBIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINANNOTATION 
ADD CONSTRAINT DOMAINEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DOMAINANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAINANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAINANNOTATION TO AUXILIARY;

DROP TABLE ENZYMEANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE ENZYMEANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT ENZYMEANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT ENZYMEANNOTATION_UK UNIQUE (BIOENTITY_ID, BIOCONCEPT_ID) ) TABLESPACE DATA2;
CREATE INDEX ECEV_REF_FK_INDEX ON ENZYMEANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_STRAIN_FK_INDEX ON ENZYMEANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_EXPT_FK_INDEX ON ENZYMEANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_SOURCE_FK_INDEX ON ENZYMEANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_BIOENT_FK_INDEX ON ENZYMEANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_BIOCON_FK_INDEX ON ENZYMEANNOTATION	(BIOCONCEPT_ID) TABLESPACE DATA2;
ALTER TABLE ENZYMEANNOTATION
ADD CONSTRAINT ECEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ENZYMEANNOTATION
ADD CONSTRAINT ECEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ENZYMEANNOTATION
ADD CONSTRAINT ECEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ENZYMEANNOTATION
ADD CONSTRAINT ECEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ENZYMEANNOTATION
ADD CONSTRAINT ECEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ENZYMEANNOTATION
ADD CONSTRAINT ECEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ENZYMEANNOTATION
ADD CONSTRAINT ECEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON ENZYMEANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENZYMEANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ENZYMEANNOTATION TO AUXILIARY;

DROP TABLE EXPRESSIONANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE EXPRESSIONANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
DESCRIPTION CLOB,
DATASETCOLUMN_ID INTEGER,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT EXPRESSIONANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT EXPRESSIONANNOTATION_UK UNIQUE (DATASETCOLUMN_ID)) TABLESPACE DATA2;
CREATE INDEX EXPEV_REF_FK_INDEX ON EXPRESSIONANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX EXPEV_STRAIN_FK_INDEX ON EXPRESSIONANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX EXPEV_EXPT_FK_INDEX ON EXPRESSIONANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX EXPEV_SOURCE_FK_INDEX ON EXPRESSIONANNOTATION (SOURCE_ID) TABLESPACE DATA2;
ALTER TABLE EXPRESSIONANNOTATION
ADD CONSTRAINT EXPEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONANNOTATION
ADD CONSTRAINT EXPEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONANNOTATION
ADD CONSTRAINT EXPEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONANNOTATION
ADD CONSTRAINT EXPEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONANNOTATION
ADD CONSTRAINT EXPEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONANNOTATION
ADD CONSTRAINT EXPEV_DSETCOL_FK FOREIGN KEY (DATASETCOLUMN_ID) REFERENCES DATASETCOLUMNBIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON EXPRESSIONANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPRESSIONANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPRESSIONANNOTATION TO AUXILIARY;

DROP TABLE GENINTERACTIONANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE GENINTERACTIONANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NULL,
PHENOTYPE_ID INTEGER,
MUTANT_TYPE VARCHAR2(100),
ANNOTATION_TYPE VARCHAR2(40) NOT NULL,
BAIT_HIT VARCHAR2(20) NOT NULL,
BIOENTITY1_ID INTEGER NOT NULL,
BIOENTITY2_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT GENINTERACTIONANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT GENINTERACTIONANNOTATION_UK UNIQUE (BIOENTITY1_ID, BIOENTITY2_ID, BAIT_HIT, EXPERIMENT_ID, REFERENCE_ID)) TABLESPACE DATA2;
CREATE INDEX GENINTEV_REF_FK_INDEX ON GENINTERACTIONANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_STRAIN_FK_INDEX ON GENINTERACTIONANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_EXPT_FK_INDEX ON GENINTERACTIONANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_SOURCE_FK_INDEX ON GENINTERACTIONANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_BIOENT2_INDEX ON GENINTERACTIONANNOTATION (BIOENTITY2_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_BIOENT1_INDEX ON GENINTERACTIONANNOTATION (BIOENTITY1_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_PHENO_FK_INDEX ON GENINTERACTIONANNOTATION (PHENOTYPE_ID) TABLESPACE DATA2;
ALTER TABLE GENINTERACTIONANNOTATION
ADD CONSTRAINT GENINTEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONANNOTATION
ADD CONSTRAINT GENINTEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONANNOTATION
ADD CONSTRAINT GENINTEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONANNOTATION
ADD CONSTRAINT GENINTEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONANNOTATION
ADD CONSTRAINT GENINTEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONANNOTATION
ADD CONSTRAINT GENINTEV_PHENO_FK FOREIGN KEY (PHENOTYPE_ID) REFERENCES PHENOTYPEBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONANNOTATION
ADD CONSTRAINT GENINTEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONANNOTATION
ADD CONSTRAINT GENINTEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GENINTERACTIONANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GENINTERACTIONANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GENINTERACTIONANNOTATION TO AUXILIARY;

DROP TABLE GOANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE GOANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
GO_ANNOTATION VARCHAR2(40) NOT NULL,
ANNOTATION_TYPE VARCHAR2(40) NOT NULL,
QUALIFIER VARCHAR2(40) NOT NULL,
CONDITIONS_KEY VARCHAR2(1000) NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT GOANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT GOANNOTATION_UK UNIQUE (BIOENTITY_ID, BIOCONCEPT_ID, GO_ANNOTATION, REFERENCE_ID, CONDITIONS_KEY)) TABLESPACE DATA2;
CREATE INDEX GOEV_REF_FK_INDEX ON GOANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_STRAIN_FK_INDEX ON GOANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_EXPT_FK_INDEX ON GOANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_SOURCE_FK_INDEX ON GOANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_BIOENT_FK_INDEX ON GOANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_BIOCON_FK_INDEX ON GOANNOTATION	(BIOCONCEPT_ID) TABLESPACE DATA2;
ALTER TABLE GOANNOTATION
ADD CONSTRAINT GOEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOANNOTATION
ADD CONSTRAINT GOEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOANNOTATION
ADD CONSTRAINT GOEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOANNOTATION
ADD CONSTRAINT GOEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOANNOTATION
ADD CONSTRAINT GOEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOANNOTATION
ADD CONSTRAINT GOEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOANNOTATION
ADD CONSTRAINT GOEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES GOBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GOANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOANNOTATION TO AUXILIARY;

DROP TABLE GOSLIMANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE GOSLIMANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER,
EXPERIMENT_ID INTEGER,
STRAIN_ID INTEGER,
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER,
ASPECT VARCHAR(1),
NOTE VARCHAR2(1000) NULL,
CONSTRAINT GOSLIMANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT GOSLIMANNOTATION_UK UNIQUE (BIOENTITY_ID, BIOCONCEPT_ID)) TABLESPACE DATA2;
CREATE INDEX GOSLIMEV_REF_FK_INDEX ON GOSLIMANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX GOSLIMEV_STRAIN_FK_INDEX ON GOSLIMANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX GOSLIMEV_EXPT_FK_INDEX ON GOSLIMANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX GOSLIMEV_SOURCE_FK_INDEX ON GOSLIMANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX GOSLIMEV_BIOENT_FK_INDEX ON GOSLIMANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX GOSLIMEV_BIOCON_FK_INDEX ON GOSLIMANNOTATION	(BIOCONCEPT_ID) TABLESPACE DATA2;
ALTER TABLE GOSLIMANNOTATION
ADD CONSTRAINT GOSLIMEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOSLIMANNOTATION
ADD CONSTRAINT GOSLIMEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOSLIMANNOTATION
ADD CONSTRAINT GOSLIMEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOSLIMANNOTATION
ADD CONSTRAINT GOSLIMEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOSLIMANNOTATION
ADD CONSTRAINT GOSLIMEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOSLIMANNOTATION
ADD CONSTRAINT GOSLIMEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOSLIMANNOTATION
ADD CONSTRAINT GOSLIMEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES GOBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GOSLIMANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOSLIMANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOSLIMANNOTATION TO AUXILIARY;

DROP TABLE HISTORYANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE HISTORYANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NULL,
CATEGORY VARCHAR2(100) NULL,
HISTORY_TYPE VARCHAR2(50) NULL,
NOTE VARCHAR2(4000) NULL,
CONSTRAINT HISTORYANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT HISTORYANNOTATION_UK UNIQUE (BIOENTITY_ID, HISTORY_TYPE, REFERENCE_ID, NOTE) ) TABLESPACE DATA2;
CREATE INDEX HISTEV_REF_FK_INDEX ON HISTORYANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX HISTEV_STRAIN_FK_INDEX ON HISTORYANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX HISTEV_EXPT_FK_INDEX ON HISTORYANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX HISTEV_SOURCE_FK_INDEX ON HISTORYANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX HISTEV_BIOENT_FK_INDEX ON HISTORYANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE HISTORYANNOTATION
ADD CONSTRAINT HISTEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYANNOTATION
ADD CONSTRAINT HISTEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYANNOTATION
ADD CONSTRAINT HISTEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYANNOTATION
ADD CONSTRAINT HISTEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYANNOTATION
ADD CONSTRAINT HISTEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYANNOTATION
ADD CONSTRAINT HISTEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON HISTORYANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTORYANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTORYANNOTATION TO AUXILIARY;

DROP TABLE LITERATUREANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE LITERATUREANNOTATION ( 
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NULL,
TOPIC VARCHAR2(40) NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT LITERATUREANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT LITERATUREANNOTATION_UK UNIQUE (BIOENTITY_ID, REFERENCE_ID, TOPIC) ) TABLESPACE DATA2;
CREATE INDEX LITEV_REF_FK_INDEX ON LITERATUREANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX LITEV_STRAIN_FK_INDEX ON LITERATUREANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX LITEV_EXPT_FK_INDEX ON LITERATUREANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX LITEV_SOURCE_FK_INDEX ON LITERATUREANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX LITEV_BIOENT_FK_INDEX ON LITERATUREANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE LITERATUREANNOTATION 
ADD CONSTRAINT LITEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREANNOTATION
ADD CONSTRAINT LITEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREANNOTATION
ADD CONSTRAINT LITEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREANNOTATION
ADD CONSTRAINT LITEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREANNOTATION
ADD CONSTRAINT LITEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREANNOTATION 
ADD CONSTRAINT LITEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON LITERATUREANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LITERATUREANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LITERATUREANNOTATION TO AUXILIARY;

DROP TABLE PATHWAYANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE PATHWAYANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOITEM_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PATHWAYANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT PATHWAYANNOTATION_UK UNIQUE (BIOENTITY_ID, BIOITEM_ID) ) TABLESPACE DATA2;
CREATE INDEX PATHEV_REF_FK_INDEX ON PATHWAYANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_STRAIN_FK_INDEX ON PATHWAYANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_EXPT_FK_INDEX ON PATHWAYANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_SOURCE_FK_INDEX ON PATHWAYANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_BIOENT_FK_INDEX ON PATHWAYANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_PATH_FK_INDEX ON PATHWAYANNOTATION (BIOITEM_ID) TABLESPACE DATA2;
ALTER TABLE PATHWAYANNOTATION
ADD CONSTRAINT PATHEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYANNOTATION
ADD CONSTRAINT PATHEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYANNOTATION
ADD CONSTRAINT PATHEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYANNOTATION
ADD CONSTRAINT PATHEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYANNOTATION
ADD CONSTRAINT PATHEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYANNOTATION
ADD CONSTRAINT PATHEV_PATH_FK FOREIGN KEY (BIOITEM_ID) REFERENCES BIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYANNOTATION
ADD CONSTRAINT PATHEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PATHWAYANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PATHWAYANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PATHWAYANNOTATION TO AUXILIARY;

DROP TABLE PHENOTYPEANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE PHENOTYPEANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
MUTANT_TYPE VARCHAR2(100),
STRAIN_DETAILS VARCHAR2(2000),
EXPERIMENT_DETAILS VARCHAR2(2000),
CONDITIONS_KEY VARCHAR2(1000) NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PHENOTYPEANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT PHENOTYPEANNOTATION_UK UNIQUE (BIOENTITY_ID, BIOCONCEPT_ID, STRAIN_ID, EXPERIMENT_ID, REFERENCE_ID, EXPERIMENT_DETAILS, MUTANT_TYPE, CONDITIONS_KEY) ) TABLESPACE DATA2;
CREATE INDEX PHENOEV_REF_FK_INDEX ON PHENOTYPEANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_STRAIN_FK_INDEX ON PHENOTYPEANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_EXPT_FK_INDEX ON PHENOTYPEANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_SOURCE_FK_INDEX ON PHENOTYPEANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_BIOENT_FK_INDEX ON PHENOTYPEANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_BIOCON_FK_INDEX ON PHENOTYPEANNOTATION (BIOCONCEPT_ID) TABLESPACE DATA2;
ALTER TABLE PHENOTYPEANNOTATION
ADD CONSTRAINT PHENOEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEANNOTATION
ADD CONSTRAINT PHENOEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEANNOTATION
ADD CONSTRAINT PHENOEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEANNOTATION
ADD CONSTRAINT PHENOEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEANNOTATION
ADD CONSTRAINT PHENOEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEANNOTATION
ADD CONSTRAINT PHENOEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEANNOTATION
ADD CONSTRAINT PHENOEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES PHENOTYPEBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHENOTYPEANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPEANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPEANNOTATION TO AUXILIARY;

DROP TABLE PHOSPHORYLATIONANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE PHOSPHORYLATIONANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
SITE_INDEX INTEGER NOT NULL,
SITE_RESIDUE VARCHAR2(1) NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PHOSPHORYLATIONANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT PHOSPHORYLATIONANNOTATION_UK UNIQUE (BIOENTITY_ID, SITE_RESIDUE, SITE_INDEX, REFERENCE_ID) ) TABLESPACE DATA2;
CREATE INDEX PHOSEV_REF_FK_INDEX ON PHOSPHORYLATIONANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PHOSEV_STRAIN_FK_INDEX ON PHOSPHORYLATIONANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PHOSEV_EXPT_FK_INDEX ON PHOSPHORYLATIONANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PHOSEV_SOURCE_FK_INDEX ON PHOSPHORYLATIONANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PHOSEV_BIOENT_FK_INDEX ON PHOSPHORYLATIONANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE PHOSPHORYLATIONANNOTATION
ADD CONSTRAINT PHOSEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONANNOTATION
ADD CONSTRAINT PHOSEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONANNOTATION
ADD CONSTRAINT PHOSEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONANNOTATION
ADD CONSTRAINT PHOSEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONANNOTATION
ADD CONSTRAINT PHOSEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONANNOTATION
ADD CONSTRAINT PHOSEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHOSPHORYLATIONANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHOSPHORYLATIONANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHOSPHORYLATIONANNOTATION TO AUXILIARY;

DROP TABLE PHYSINTERACTIONANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE PHYSINTERACTIONANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NULL,
MODIFICATION VARCHAR2(40) NOT NULL,
ANNOTATION_TYPE VARCHAR2(40) NOT NULL,
BAIT_HIT VARCHAR2(20) NOT NULL,
BIOENTITY1_ID INTEGER NOT NULL,
BIOENTITY2_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PHYSINTERACTIONANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT PHYSINTERACTIONANNOTATION_UK UNIQUE (BIOENTITY1_ID, BIOENTITY2_ID, BAIT_HIT, EXPERIMENT_ID, REFERENCE_ID)) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_REF_FK_INDEX ON PHYSINTERACTIONANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_STRAIN_FK_INDEX ON PHYSINTERACTIONANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_EXPT_FK_INDEX ON PHYSINTERACTIONANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_SOURCE_FK_INDEX ON PHYSINTERACTIONANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_BIOENT2_INDEX ON PHYSINTERACTIONANNOTATION (BIOENTITY2_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_BIOENT1_INDEX ON PHYSINTERACTIONANNOTATION (BIOENTITY1_ID) TABLESPACE DATA2;
ALTER TABLE PHYSINTERACTIONANNOTATION
ADD CONSTRAINT PHYSINTEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONANNOTATION
ADD CONSTRAINT PHYSINTEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONANNOTATION
ADD CONSTRAINT PHYSINTEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONANNOTATION
ADD CONSTRAINT PHYSINTEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONANNOTATION
ADD CONSTRAINT PHYSINTEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONANNOTATION
ADD CONSTRAINT PHYSINTEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONANNOTATION
ADD CONSTRAINT PHYSINTEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHYSINTERACTIONANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHYSINTERACTIONANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHYSINTERACTIONANNOTATION TO AUXILIARY;

DROP TABLE PROTEINEXPERIMENTANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE PROTEINEXPERIMENTANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
DATA_VALUE VARCHAR2(25) NOT NULL,
DATA_UNIT VARCHAR2(25) NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PROTEINEXPERIMENTANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT PROTEINEXPERIMENTANNOTATION_UK UNIQUE (BIOENTITY_ID, EXPERIMENT_ID) ) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_REF_FK_INDEX ON PROTEINEXPERIMENTANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_STRAIN_FK_INDEX ON PROTEINEXPERIMENTANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_EXPT_FK_INDEX ON PROTEINEXPERIMENTANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_SOURCE_FK_INDEX ON PROTEINEXPERIMENTANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_BIOENT_FK_INDEX ON PROTEINEXPERIMENTANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE PROTEINEXPERIMENTANNOTATION
ADD CONSTRAINT PROTEXPEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTANNOTATION
ADD CONSTRAINT PROTEXPEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTANNOTATION
ADD CONSTRAINT PROTEXPEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTANNOTATION
ADD CONSTRAINT PROTEXPEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTANNOTATION
ADD CONSTRAINT PROTEXPEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTANNOTATION
ADD CONSTRAINT PROTEXPEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PROTEINEXPERIMENTANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINEXPERIMENTANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINEXPERIMENTANNOTATION TO AUXILIARY;

DROP TABLE PROTEINSEQUENCEANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE PROTEINSEQUENCEANNOTATION (
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
PROTEIN_TYPE VARCHAR2(50) NOT NULL,
RESIDUES CLOB NOT NULL,
MOLECULAR_WEIGHT VARCHAR2(10),
PI VARCHAR2(10),
CAI VARCHAR2(10),
N_TERM_SEQ VARCHAR2(10) NOT NULL,
C_TERM_SEQ VARCHAR2(10) NOT NULL,
CODON_BIAS VARCHAR2(10),
FOP_SCORE VARCHAR2(10),
GRAVY_SCORE VARCHAR2(10),
AROMATICITY_SCORE VARCHAR2(10),
ALIPHATIC_INDEX VARCHAR2(10),
INSTABILITY_INDEX VARCHAR2(10),
ALA INTEGER NOT NULL,
ARG INTEGER NOT NULL,
ASN INTEGER NOT NULL,
ASP INTEGER NOT NULL,
CYS INTEGER NOT NULL,
GLN INTEGER NOT NULL,
GLU INTEGER NOT NULL,
GLY INTEGER NOT NULL,
HIS INTEGER NOT NULL,
ILE INTEGER NOT NULL,
LEU INTEGER NOT NULL,
LYS INTEGER NOT NULL,
MET INTEGER NOT NULL,
PHE INTEGER NOT NULL,
PRO INTEGER NOT NULL,
THR INTEGER NOT NULL,
SER INTEGER NOT NULL,
TRP INTEGER NOT NULL,
TYR INTEGER NOT NULL,
VAL INTEGER NOT NULL,
HYDROGEN INTEGER,
SULFUR INTEGER,
NITROGEN INTEGER,
OXYGEN INTEGER,
CARBON INTEGER,
YEAST_HALF_LIFE VARCHAR2(50),
ECOLI_HALF_LIFE VARCHAR2(50),
MAMMAL_HALF_LIFE VARCHAR2(50),
NO_CYS_EXT_COEFF VARCHAR2(50),
ALL_CYS_EXT_COEFF VARCHAR2(50),
ALL_HALF_CYS_EXT_COEFF VARCHAR2(50),
ALL_PAIRS_CYS_EXT_COEFF VARCHAR2(50),
HEADER VARCHAR2(200),
FILENAME VARCHAR2(200),
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PROTEINSEQUENCEANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT PROTEINSEQUENCEANNOTATION_UK UNIQUE (BIOENTITY_ID, STRAIN_ID, PROTEIN_TYPE) ) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_REF_FK_INDEX ON PROTEINSEQUENCEANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_STRAIN_FK_INDEX ON PROTEINSEQUENCEANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_EXPT_FK_INDEX ON PROTEINSEQUENCEANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_SOURCE_FK_INDEX ON PROTEINSEQUENCEANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_BIOENT_FK_INDEX ON PROTEINSEQUENCEANNOTATION (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE PROTEINSEQUENCEANNOTATION
ADD CONSTRAINT PROTSEQEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEANNOTATION
ADD CONSTRAINT PROTSEQEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEANNOTATION
ADD CONSTRAINT PROTSEQEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEANNOTATION
ADD CONSTRAINT PROTSEQEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEANNOTATION
ADD CONSTRAINT PROTSEQEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEANNOTATION
ADD CONSTRAINT PROTSEQEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PROTEINSEQUENCEANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINSEQUENCEANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINSEQUENCEANNOTATION TO AUXILIARY;

DROP TABLE REGULATIONANNOTATION CASCADE CONSTRAINTS;
CREATE TABLE REGULATIONANNOTATION ( 
ANNOTATION_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY1_ID INTEGER NOT NULL,
BIOENTITY2_ID INTEGER NOT NULL,
CONDITIONS_KEY VARCHAR2(1000) NULL,
DIRECTION VARCHAR2(100),
PVALUE VARCHAR2(40),
FDR VARCHAR2(40),
CONSTRUCT VARCHAR2(100),
ASSAY VARCHAR2(300),
NOTE VARCHAR2(1000) NULL,
CONSTRAINT REGULATIONANNOTATION_PK PRIMARY KEY (ANNOTATION_ID),
CONSTRAINT REGULATIONANNOTATION_UK UNIQUE (BIOENTITY1_ID, BIOENTITY2_ID, EXPERIMENT_ID, REFERENCE_ID, STRAIN_ID, CONDITIONS_KEY)) TABLESPACE DATA2;
CREATE INDEX REGEV_REF_FK_INDEX ON REGULATIONANNOTATION (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_STRAIN_FK_INDEX ON REGULATIONANNOTATION (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_EXPT_FK_INDEX ON REGULATIONANNOTATION (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_SOURCE_FK_INDEX ON REGULATIONANNOTATION (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_BIOENT1_FK_INDEX ON REGULATIONANNOTATION (BIOENTITY1_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_BIOENT2_FK_INDEX ON REGULATIONANNOTATION (BIOENTITY2_ID) TABLESPACE DATA2;
ALTER TABLE REGULATIONANNOTATION 
ADD CONSTRAINT REGEV_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONANNOTATION
ADD CONSTRAINT REGEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONANNOTATION
ADD CONSTRAINT REGEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONANNOTATION
ADD CONSTRAINT REGEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONANNOTATION
ADD CONSTRAINT REGEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONANNOTATION 
ADD CONSTRAINT REGEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONANNOTATION 
ADD CONSTRAINT REGEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REGULATIONANNOTATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REGULATIONANNOTATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REGULATIONANNOTATION TO AUXILIARY;


/* Misc Annotation Tables */

DROP TABLE BIOENTITYDATA CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYDATA (
BIOENTITYDATA_ID INTEGER NOT NULL,
ANNOTATION_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
VALUE DECIMAL(7, 3) NOT NULL,
CONSTRAINT BIOENTITYDATA_PK PRIMARY KEY (BIOENTITYDATA_ID),
CONSTRAINT BIOENTITYDATA_UK UNIQUE (ANNOTATION_ID, BIOENTITY_ID)) TABLESPACE DATA3;
CREATE INDEX DAT_BIOENT_FK_INDEX ON BIOENTITYDATA (BIOENTITY_ID) TABLESPACE DATA3;
CREATE INDEX DAT_EV_FK_INDEX ON BIOENTITYDATA (ANNOTATION_ID) TABLESPACE DATA3;
ALTER TABLE BIOENTITYDATA
ADD CONSTRAINT DAT_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYDATA
ADD CONSTRAINT DAT_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYDATA TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYDATA TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYDATA TO AUXILIARY;
DROP SEQUENCE DATA_SEQ;
CREATE SEQUENCE DATA_SEQ NOCACHE;

DROP TABLE DNASEQUENCETAG CASCADE CONSTRAINTS;
CREATE TABLE DNASEQUENCETAG (
DNASEQUENCETAG_ID INTEGER NOT NULL,
ANNOTATION_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL,
RELATIVE_START_INDEX INTEGER NOT NULL,
RELATIVE_END_INDEX INTEGER NOT NULL,
CHROMOSOMAL_START_INDEX INTEGER NOT NULL,
CHROMOSOMAL_END_INDEX INTEGER NOT NULL,
PHASE VARCHAR2(1) NOT NULL,
SEQ_VERSION DATE,
COORD_VERSION DATE,
BIOENTITY_ID INTEGER NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT DNASEQUENCETAG_PK PRIMARY KEY (DNASEQUENCETAG_ID),
CONSTRAINT DNASEQUENCETAG_UK UNIQUE (ANNOTATION_ID, SUBCLASS, RELATIVE_START_INDEX, RELATIVE_END_INDEX)) TABLESPACE DATA1;
CREATE INDEX DNASEQTAG_EV_FK_INDEX ON DNASEQUENCETAG (ANNOTATION_ID) TABLESPACE DATA1;
CREATE INDEX DNASEQTAG_BIOENT_FK_INDEX ON DNASEQUENCETAG (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE DNASEQUENCETAG
ADD CONSTRAINT DNASEQTAG_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES DNASEQUENCEANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCETAG
ADD CONSTRAINT DNASEQTAG_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE DNASEQTAG_SEQ;
CREATE SEQUENCE DNASEQTAG_SEQ NOCACHE;
GRANT SELECT ON DNASEQUENCETAG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DNASEQUENCETAG TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DNASEQUENCETAG TO AUXILIARY;

DROP TABLE ANNOTATIONEXTRA CASCADE CONSTRAINTS;
CREATE TABLE CONDITION ( 
ANNOTATIONEXTRA_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500),
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('GENERAL', 'TEMPERATURE', 'BIOENTITY', 'BIOCONCEPT', 'BIOITEM', 'CHEMICAL')),
ANNOTATION_ID INTEGER NOT NULL, 
ROLE VARCHAR2(40),
NOTE VARCHAR(1000), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT CONDITION_PK PRIMARY KEY (CONDITION_ID), 
CONSTRAINT CONDITION_UK UNIQUE (ANNOTATION_ID, FORMAT_NAME, SUBCLASS, ROLE) ) TABLESPACE DATA1;
ALTER TABLE CONDITION 
ADD CONSTRAINT COND_EV_FK FOREIGN KEY (ANNOTATION_ID) REFERENCES ANNOTATION (ANNOTATION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE COND_SEQ;
CREATE SEQUENCE COND_SEQ NOCACHE;
GRANT SELECT ON CONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONDITION TO AUXILIARY;

DROP TABLE BIOENTITYANNOTATIONEXTRA CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYANNOTATIONEXTRA (
CONDITION_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL, 
CONSTRAINT ANNOTATIONEXTRACONDITION_PK PRIMARY KEY (ANNOTATIONEXTRA_ID) ) TABLESPACE DATA1;
ALTER TABLE ANNOTATIONEXTRACONDITION
ADD CONSTRAINT BIOENTITYCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOENTITYCOND_BIOENT_FK_INDEX ON BIOENTITYCONDITION (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITYCONDITION 
ADD CONSTRAINT BIOENTITYCOND_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYCONDITION TO AUXILIARY;


DROP TABLE CHEMICALCONDITION CASCADE CONSTRAINTS;
CREATE TABLE CHEMICALCONDITION (
CONDITION_ID INTEGER NOT NULL,
AMOUNT VARCHAR2(500),
CONSTRAINT CHEMICALCONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1;
ALTER TABLE CHEMICALCONDITION
ADD CONSTRAINT CHEMCONDITION_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES BIOITEMCONDITION (CONDITION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CHEMICALCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALCONDITION TO AUXILIARY;

/* Paragraph */
DROP TABLE DOCUMENT CASCADE CONSTRAINTS;
CREATE TABLE DOCUMENT (
DOCUMENT_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
CLASS VARCHAR2(100) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
TEXT CLOB NOT NULL,
HTML CLOB NOT NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT DOCUMENT_PK PRIMARY KEY (DOCUMENT_ID),
CONSTRAINT DOCUMENT_UK UNIQUE (FORMAT_NAME, CLASS, CATEGORY)) TABLESPACE DATA1;
CREATE INDEX PARA_SOURCE_FK_INDEX ON PARAGRAPH (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE PARAGRAPH
ADD CONSTRAINT PARA_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE PARA_SEQ;
CREATE SEQUENCE PARA_SEQ NOCACHE;
GRANT SELECT ON PARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH TO AUXILIARY;

DROP TABLE PARAGRAPH_REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE PARAGRAPH_REFERENCE ( 
PARAGRAPH_REFERENCE_ID INTEGER NOT NULL, 
PARAGRAPH_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER NOT NULL,
CONSTRAINT PARAGRAPH_REFERENCE_PK PRIMARY KEY (PARAGRAPH_REFERENCE_ID), 
CONSTRAINT PARAGRAPH_REFERENCE_UK UNIQUE (PARAGRAPH_ID, REFERENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX PARAREF_REF_FK_INDEX ON PARAGRAPH_REFERENCE (REFERENCE_ID) TABLESPACE DATA1;
CREATE INDEX PARAREF_PAR_FK_INDEX ON PARAGRAPH_REFERENCE (PARAGRAPH_ID) TABLESPACE DATA1;
ALTER TABLE PARAGRAPH_REFERENCE 
ADD CONSTRAINT PARAREF_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PARAGRAPH_REFERENCE 
ADD CONSTRAINT PARAREF_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE PARAREF_SEQ;
CREATE SEQUENCE PARAREF_SEQ NOCACHE;
GRANT SELECT ON PARAGRAPH_REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH_REFERENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH_REFERENCE TO AUXILIARY;

DROP TABLE BIOENTITYPARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYPARAGRAPH (
PARAGRAPH_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
CONSTRAINT BIOENTITYPARAGRAPH_PK PRIMARY KEY (PARAGRAPH_ID) ) TABLESPACE DATA1;
CREATE INDEX BIOENTPARA_BIOENT_FK_INDEX ON BIOENTITYPARAGRAPH (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITYPARAGRAPH
ADD CONSTRAINT BIOENTPARA_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYPARAGRAPH
ADD CONSTRAINT BIOENTPARA_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYPARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYPARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYPARAGRAPH TO AUXILIARY;

DROP TABLE STRAINPARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE STRAINPARAGRAPH (
PARAGRAPH_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NOT NULL,
CONSTRAINT STRAINPARAGRAPH_PK PRIMARY KEY (PARAGRAPH_ID) ) TABLESPACE DATA1;
CREATE INDEX STRAINPARA_STRAIN_FK_INDEX ON STRAINPARAGRAPH (STRAIN_ID) TABLESPACE DATA1;
ALTER TABLE STRAINPARAGRAPH
ADD CONSTRAINT STRAINPARA_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE STRAINPARAGRAPH
ADD CONSTRAINT STRAINPARA_STRAIN_ID_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON STRAINPARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAINPARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAINPARAGRAPH TO AUXILIARY;

DROP TABLE REFERENCEPARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE REFERENCEPARAGRAPH (
PARAGRAPH_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
CONSTRAINT REFERENCEPARAGRAPH_PK PRIMARY KEY (PARAGRAPH_ID) ) TABLESPACE DATA1;
CREATE INDEX REFPARA_STRAIN_FK_INDEX ON REFERENCEPARAGRAPH (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCEPARAGRAPH
ADD CONSTRAINT REFPARA_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCEPARAGRAPH
ADD CONSTRAINT REFPARA_STRAIN_ID_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCEPARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEPARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEPARAGRAPH TO AUXILIARY;

/* Auxiliary */
DROP TABLE DISAMBIG CASCADE CONSTRAINTS;
CREATE TABLE DISAMBIG (
DISAMBIG_ID INTEGER NOT NULL,
DISAMBIG_KEY VARCHAR2(200) NOT NULL, 
CLASS VARCHAR(40) CHECK (CLASS IN ('LOCUS', 'GO', 'PHENOTYPE', 'OBSERVABLE', 'ENZYME', 'DOMAIN', 'CONTIG', 'CHEMICAL', 'DATASET', 'DATASETCOLUMN', 'RESERVEDNAME')),
OBJ_ID INTEGER NOT NULL, 
CONSTRAINT DISAMBIG_PK PRIMARY KEY (DISAMBIG_ID),
CONSTRAINT DISAMBIG_UK UNIQUE (DISAMBIG_KEY, CLASS) ) TABLESPACE DATA1;
CREATE INDEX DISAMBIG_OBJID_INDEX ON DISAMBIG (OBJ_ID) TABLESPACE DATA1;
DROP SEQUENCE DISAMBIG_SEQ;
CREATE SEQUENCE DISAMBIG_SEQ NOCACHE;
GRANT SELECT ON DISAMBIG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DISAMBIG TO AUXILIARY;

DROP TABLE LOCUSTABS CASCADE CONSTRAINTS;
CREATE TABLE LOCUSTABS (
BIOENTITY_ID INTEGER NOT NULL, 
SUMMARY NUMBER(1) NOT NULL,
SEQ NUMBER(1) NOT NULL,
HISTORY NUMBER(1) NOT NULL, 
LITERATURE NUMBER(1) NOT NULL, 
GO NUMBER(1) NOT NULL, 
PHENOTYPE NUMBER(1) NOT NULL, 
INTERACTIONS NUMBER(1) NOT NULL, 
EXPRESSION NUMBER(1) NOT NULL, 
REGULATION NUMBER(1) NOT NULL, 
PROTEIN NUMBER(1) NOT NULL, 
WIKI NUMBER(1) NOT NULL,
SEQ_SECTION NUMBER(1),
CONSTRAINT LOCUSTABS_PK PRIMARY KEY (BIOENTITY_ID) ) TABLESPACE DATA1;
GRANT SELECT ON LOCUSTABS TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON LOCUSTABS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUSTABS TO AUXILIARY;