/* Primary */
DROP TABLE PRIMARYOBJECT CASCADE CONSTRAINTS;
CREATE TABLE PRIMARYOBJECT (
ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
BUDID INTEGER,
SGDID VARCHAR2(40),
STATUS VARCHAR2(40),
DESCRIPTION VARCHAR2(2000),
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('LOCUS', 'REFERENCE', 'STRAIN')),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT PRIMARY_PK PRIMARY KEY (ID),
CONSTRAINT PRIMARY_UK UNIQUE (FORMAT_NAME, SUBCLASS),
CONSTRAINT PRIMARY_SGDID_UK UNIQUE (SGDID)) TABLESPACE DATA1;
CREATE INDEX PRIMARY_SOURCE_FK ON PRIMARYOBJECT (SOURCE_ID) TABLESPACE DATA1;
GRANT SELECT ON PRIMARYOBJECT TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON PRIMARYOBJECT TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PRIMARYOBJECT TO AUXILIARY;

DROP TABLE LOCUS CASCADE CONSTRAINTS;
CREATE TABLE LOCUS (
ID INTEGER NOT NULL,
LOCUS_TYPE VARCHAR2(40) NOT NULL,
NAME_DESCRIPTION VARCHAR2(100),
HEADLINE VARCHAR2(70),
GENE_NAME VARCHAR2(100),
QUALIFIER VARCHAR2(40),
GENETIC_POSITION DECIMAL(7, 3) NULL,
CONSTRAINT LOCUS_PK PRIMARY KEY (ID) ) TABLESPACE DATA1;
ALTER TABLE LOCUS
ADD CONSTRAINT LOCUS_FK FOREIGN KEY (ID) REFERENCES PRIMARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON LOCUS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUS TO AUXILIARY;

DROP TABLE REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE (
ID INTEGER NOT NULL,
FULLTEXT_STATUS VARCHAR2(40) NOT NULL,
CITATION VARCHAR2(500) NOT NULL,
YEAR INTEGER NOT NULL,
PUBMED_ID INTEGER,
PUBMED_CENTRAL_ID VARCHAR2(40),
DATE_PUBLISHED VARCHAR2(40),
DATE_REVISED VARCHAR2(40),
ISSUE VARCHAR2(40),
PAGE VARCHAR2(40),
VOLUME VARCHAR2(40),
TITLE VARCHAR2(400),
JOURNAL_ID INTEGER,
BOOK_ID INTEGER,
DOI VARCHAR2(100),
CONSTRAINT REFERENCE_PK PRIMARY KEY (ID),
CONSTRAINT REFERENCE_CITATION_UK UNIQUE (CITATION)) TABLESPACE DATA2;
CREATE INDEX REF_BOOK_FK_INDEX ON REFERENCE (BOOK_ID) TABLESPACE DATA2;
CREATE INDEX REF_JOURNAL_FK_INDEX ON REFERENCE (JOURNAL_ID) TABLESPACE DATA2;
ALTER TABLE REFERENCE
ADD CONSTRAINT REF_JOURNAL_FK FOREIGN KEY (JOURNAL_ID) REFERENCES JOURNAL (ID)
ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE
ADD CONSTRAINT REF_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE
ADD CONSTRAINT REFERENCE_FK FOREIGN KEY (ID) REFERENCES PRIMARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE TO AUXILIARY;

DROP TABLE STRAIN CASCADE CONSTRAINTS;
CREATE TABLE STRAIN (
ID INTEGER NOT NULL,
GENOTYPE VARCHAR2(500),
CONSTRAINT STRAIN_PK PRIMARY KEY (ID)) TABLESPACE DATA1;
ALTER TABLE STRAIN
ADD CONSTRAINT STRAIN_FK FOREIGN KEY (ID) REFERENCES PRIMARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE STRAIN_SEQ;
CREATE SEQUENCE STRAIN_SEQ NOCACHE;
GRANT SELECT ON STRAIN TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON STRAIN TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAIN TO AUXILIARY;

/* Secondary */
DROP TABLE SECONDARYOBJECT CASCADE CONSTRAINTS;
CREATE TABLE SECONDARYOBJECT (
ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER,
IS_ROOT INTEGER,
PRIMARY_COUNT INTEGER,
DESCENDANT_PRIMARY_COUNT INTEGER,
DESCRIPTION VARCHAR2(2000),
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('ECNUMBER', 'GO', 'OBSERVABLE', 'PHENOTYPE', 'DOMAIN', 'CHEMICAL',
'CONTIG', 'DATASET', 'DATASETCOLUMN', 'RESERVEDNAME', 'ALLELE', 'ORPHAN', 'PATHWAY', 'SOURCE', 'EXPERIMENT', 'AUTHOR',
'BOOK', 'JOURNAL', 'REFTYPE')),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT SECONDARY_PK PRIMARY KEY (ID),
CONSTRAINT SECONDARY_UK UNIQUE (FORMAT_NAME, SUBCLASS) ) TABLESPACE DATA1;
CREATE INDEX SECONDARY_SOURCE_FK ON SECONDARYOBJECT (SOURCE_ID) TABLESPACE DATA1;
GRANT SELECT ON SECONDARYOBJECT TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON SECONDARYOBJECT TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON SECONDARYOBJECT TO AUXILIARY;

DROP TABLE AUTHOR CASCADE CONSTRAINTS;
CREATE TABLE AUTHOR (
ID INTEGER NOT NULL,
CONSTRAINT AUTHOR_PK PRIMARY KEY (ID)) TABLESPACE DATA1;
ALTER TABLE AUTHOR
ADD CONSTRAINT AUTHOR_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUTHOR TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR TO AUXILIARY;

DROP TABLE BOOK CASCADE CONSTRAINTS;
CREATE TABLE BOOK (
ID INTEGER NOT NULL,
TITLE VARCHAR2(200) NOT NULL,
VOLUME_TITLE VARCHAR2(200),
ISBN VARCHAR2(20),
TOTAL_PAGES INTEGER,
PUBLISHER VARCHAR2(100),
PUBLISHER_LOCATION VARCHAR2(100),
CONSTRAINT BOOK_PK PRIMARY KEY (ID),
CONSTRAINT BOOK_UK UNIQUE (TITLE, VOLUME_TITLE)) TABLESPACE DATA1;
ALTER TABLE BOOK
ADD CONSTRAINT BOOK_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BOOK TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BOOK TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BOOK TO AUXILIARY;

DROP TABLE CHEMICAL CASCADE CONSTRAINTS;
CREATE TABLE CHEMICAL (
ID INTEGER NOT NULL,
CHEBI_ID VARCHAR2(50),
CONSTRAINT CHEMICAL_PK PRIMARY KEY (ID) ) TABLESPACE DATA1;
ALTER TABLE CHEMICAL
ADD CONSTRAINT CHEMICAL_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CHEMICAL TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON CHEMICAL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICAL TO AUXILIARY;

DROP TABLE CONTIG CASCADE CONSTRAINTS;
CREATE TABLE CONTIG (
ID INTEGER NOT NULL,
RESIDUES CLOB NOT NULL,
STRAIN_ID INTEGER NOT NULL,
IS_CHROMOSOME INTEGER NOT NULL,
CENTROMERE_START INTEGER NULL,
CENTROMERE_END INTEGER NULL,
CONSTRAINT CONTIG_PK PRIMARY KEY (ID) ) TABLESPACE DATA1;
CREATE INDEX CONTIG_STRAIN_FK_INDEX ON CONTIG (STRAIN_ID) TABLESPACE DATA1;
ALTER TABLE CONTIG
ADD CONSTRAINT CONTIG_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE CONTIG
ADD CONSTRAINT CONTIG_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CONTIG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONTIG TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONTIG TO AUXILIARY;

DROP TABLE DATASET CASCADE CONSTRAINTS;
CREATE TABLE DATASET (
ID INTEGER NOT NULL,
GEO_ID VARCHAR2(40),
PCL_FILENAME VARCHAR2(100),
SHORT_DESCRIPTION VARCHAR2(400),
CHANNEL_COUNT INTEGER,
CONDITION_COUNT INTEGER,
REFERENCE_ID INTEGER,
CONSTRAINT DATASET_PK PRIMARY KEY (ID) ) TABLESPACE DATA1;
CREATE INDEX DATASET_REF_FK_INDEX ON DATASET (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE DATASET
ADD CONSTRAINT DATASET_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DATASET
ADD CONSTRAINT DATASET_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DATASET TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASET TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASET TO AUXILIARY;

DROP TABLE DATASETCOLUMN CASCADE CONSTRAINTS;
CREATE TABLE DATASETCOLUMN (
ID INTEGER NOT NULL,
DATASET_ID INTEGER,
FILE_ORDER INTEGER,
GEO_ID VARCHAR2(40),
CONSTRAINT DATASETCOLUMN_PK PRIMARY KEY (ID) ) TABLESPACE DATA1;
CREATE INDEX DATASETCOL_DSET_FK_INDEX ON DATASETCOLUMN (DATASET_ID) TABLESPACE DATA1;
ALTER TABLE DATASETCOLUMN
ADD CONSTRAINT DATASETCOL_DSET_FK FOREIGN KEY (DATASET_ID) REFERENCES DATASET (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DATASETCOLUMN
ADD CONSTRAINT DATASETCOLUMN_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DATASETCOLUMN TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASETCOLUMN TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DATASETCOLUMN TO AUXILIARY;

DROP TABLE DOMAIN CASCADE CONSTRAINTS;
CREATE TABLE DOMAIN (
ID INTEGER NOT NULL,
INTERPRO_ID VARCHAR2(20),
INTERPRO_DESCRIPTION VARCHAR2(500),
EXTERNAL_URL VARCHAR2(500),
CONSTRAINT DOMAIN_PK PRIMARY KEY (ID) ) TABLESPACE DATA1;
ALTER TABLE DOMAIN
ADD CONSTRAINT DOMAIN_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DOMAIN TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAIN TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAIN TO AUXILIARY;

DROP TABLE EXPERIMENT CASCADE CONSTRAINTS;
CREATE TABLE EXPERIMENT (
ID INTEGER NOT NULL,
ECO_ID VARCHAR2(40),
CATEGORY VARCHAR2(20),
CONSTRAINT EXPERIMENT_PK PRIMARY KEY (ID)) TABLESPACE DATA1;
ALTER TABLE EXPERIMENT
ADD CONSTRAINT EXPERIMENT_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON EXPERIMENT TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON EXPERIMENT TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPERIMENT TO AUXILIARY;

DROP TABLE GO CASCADE CONSTRAINTS;
CREATE TABLE GO (
ID INTEGER NOT NULL,
GO_ID VARCHAR2(12) NOT NULL,
GO_ASPECT VARCHAR2(40) NOT NULL,
CONSTRAINT GO_PK PRIMARY KEY (ID) ) TABLESPACE DATA1;
ALTER TABLE GO
ADD CONSTRAINT GO_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GO TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GO TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GO TO AUXILIARY;

DROP TABLE JOURNAL CASCADE CONSTRAINTS;
CREATE TABLE JOURNAL (
ID INTEGER NOT NULL,
MED_ABBR VARCHAR2(100),
TITLE VARCHAR2(200),
ISSN_PRINT VARCHAR2(20),
ISSN_ONLINE VARCHAR2(20),
CONSTRAINT JOURNAL_PK PRIMARY KEY (ID),
CONSTRAINT JOURNAL_UK UNIQUE (MED_ABBR, TITLE)) TABLESPACE DATA1;
ALTER TABLE JOURNAL
ADD CONSTRAINT JOURNAL_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON JOURNAL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON JOURNAL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON JOURNAL TO AUXILIARY;

DROP TABLE OBSERVABLE CASCADE CONSTRAINTS;
CREATE TABLE OBSERVABLE (
ID INTEGER NOT NULL,
ANCESTOR_TYPE VARCHAR(40) NOT NULL,
CONSTRAINT OBSERVABLE_PK PRIMARY KEY (ID)) TABLESPACE DATA1;
ALTER TABLE OBSERVABLE
ADD CONSTRAINT OBSERVABLE_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON OBSERVABLE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON OBSERVABLE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON OBSERVABLE TO AUXILIARY;

DROP TABLE PHENOTYPE CASCADE CONSTRAINTS;
CREATE TABLE PHENOTYPE (
ID INTEGER NOT NULL,
OBSERVABLE_ID INTEGER NOT NULL,
QUALIFIER VARCHAR2(100),
CONSTRAINT PHENOTYPE_PK PRIMARY KEY (ID)) TABLESPACE DATA1;
CREATE INDEX PHENO_OBS_FK_INDEX ON PHENOTYPE (OBSERVABLE_ID) TABLESPACE DATA1;
ALTER TABLE PHENOTYPE
ADD CONSTRAINT PHENO_OBS_FK FOREIGN KEY (OBSERVABLE_ID) REFERENCES OBSERVABLE (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPE
ADD CONSTRAINT PHENOTYPE_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHENOTYPE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPE TO AUXILIARY;

DROP TABLE REFTYPE CASCADE CONSTRAINTS;
CREATE TABLE REFTYPE (
ID INTEGER NOT NULL,
CONSTRAINT REFTYPE_PK PRIMARY KEY (ID)) TABLESPACE DATA1;
ALTER TABLE REFTYPE
ADD CONSTRAINT REFTYPE_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFTYPE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFTYPE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFTYPE TO AUXILIARY;

DROP TABLE RESERVEDNAME CASCADE CONSTRAINTS;
CREATE TABLE RESERVEDNAME (
ID INTEGER NOT NULL,
LOCUS_ID INTEGER NULL,
REFERENCE_ID INTEGER NULL,
RESERVATION_DATE DATE NOT NULL,
EXPIRATION_DATE DATE NOT NULL,
CONSTRAINT RNBIOITEM_PK PRIMARY KEY (ID) ) TABLESPACE DATA1;
CREATE INDEX RN_LOCUS_FK_INDEX ON RESERVEDNAME (LOCUS_ID) TABLESPACE DATA1;
ALTER TABLE RESERVEDNAME
ADD CONSTRAINT RN_LOCUS_FK FOREIGN KEY (LOCUS_ID) REFERENCES LOCUS (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX RN_REF_FK_INDEX ON RESERVEDNAME (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE RESERVEDNAME
ADD CONSTRAINT RN_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE RESERVEDNAME
ADD CONSTRAINT RESERVEDNAME_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON RESERVEDNAME TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON RESERVEDNAME TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON RESERVEDNAME TO AUXILIARY;

DROP TABLE SOURCE CASCADE CONSTRAINTS;
CREATE TABLE SOURCE (
ID INTEGER NOT NULL,
CONSTRAINT SOURCE_PK PRIMARY KEY (ID)) TABLESPACE DATA1;
ALTER TABLE SOURCE
ADD CONSTRAINT SOURCE_FK FOREIGN KEY (ID) REFERENCES SECONDARYOBJECT (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON SOURCE TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON SOURCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON SOURCE TO AUXILIARY;

ALTER TABLE PRIMARYOBJECT
ADD CONSTRAINT PRIMARY_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;

ALTER TABLE SECONDARYOBJECT
ADD CONSTRAINT SECONDARY_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;


/* Sequences */
DROP SEQUENCE CURATION_OBJECT_SEQ;
CREATE SEQUENCE CURATION_OBJECT_SEQ;







DROP TABLE REFERENCE_REFTYPE CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE_REFTYPE ( 
REFERENCE_REFTYPE_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER NOT NULL, 
REFTYPE_ID INTEGER NOT NULL, 
SOURCE_ID INTEGER NOT NULL, 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT REFERENCE_REFTYPE_PK PRIMARY KEY (REFERENCE_REFTYPE_ID), 
CONSTRAINT REFERENCE_REFTYPE_UK UNIQUE (REFERENCE_ID, REFTYPE_ID) ) TABLESPACE DATA1;
CREATE INDEX REFREFTYPE_SOURCE_FK_INDEX ON REFERENCE_REFTYPE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCE_REFTYPE
ADD CONSTRAINT REFREFTYPE_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE_REFTYPE 
ADD CONSTRAINT REFREFTYPE_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX REFREFTYPE_REFTYPE_FK_INDEX ON REFERENCE_REFTYPE (REFTYPE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCE_REFTYPE
ADD CONSTRAINT REFREFTYPE_REFTYPE_FK FOREIGN KEY (REFTYPE_ID) REFERENCES REFTYPE (REFTYPE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCE_REFTYPE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_REFTYPE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_REFTYPE TO AUXILIARY;

DROP TABLE AUTHOR_REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE AUTHOR_REFERENCE ( 
AUTHOR_REFERENCE_ID INTEGER NOT NULL, 
AUTHOR_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER NOT NULL, 
AUTHOR_ORDER INTEGER NOT NULL, 
AUTHOR_TYPE VARCHAR2(40) NOT NULL, 
SOURCE_ID INTEGER NOT NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT AUTHOR_REFERENCE_PK PRIMARY KEY (AUTHOR_REFERENCE_ID), 
CONSTRAINT AUTHOR_REFERENCE_UK UNIQUE (REFERENCE_ID, AUTHOR_ID, AUTHOR_ORDER) ) TABLESPACE DATA1;
CREATE INDEX AUTHORREF_AUTHOR_FK_INDEX ON AUTHOR_REFERENCE (AUTHOR_ID) TABLESPACE DATA1;
ALTER TABLE AUTHOR_REFERENCE 
ADD CONSTRAINT AUTHORREF_AUTHOR_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE AUTHOR_REFERENCE 
ADD CONSTRAINT AUTHORREF_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX AUTHORREF_SOURCE_FK_INDEX ON AUTHOR_REFERENCE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE AUTHOR_REFERENCE 
ADD CONSTRAINT AUTHORREF_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUTHOR_REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR_REFERENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR_REFERENCE TO AUXILIARY;





/* Evidence */
DROP TABLE EVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE EVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('PHENOTYPE', 'GO', 'ECNUMBER', 'GENINTERACTION', 'PHYSINTERACTION', 'BINDING', 'DOMAIN', 'LITERATURE', 'REGULATION', 'DNASEQUENCE', 'PROTEINSEQUENCE', 'BIOENTITY', 'ALIAS', 'PHOSPHORYLATION', 'PROTEINEXPERIMENT', 'EXPRESSION', 'HISTORY', 'PATHWAY')),
JSON VARCHAR2(4000),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT EVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA2;
CREATE INDEX EV_SUBCLASS_INDEX ON EVIDENCE (SUBCLASS) TABLESPACE DATA2;
DROP SEQUENCE EVIDENCE_SEQ;
CREATE SEQUENCE EVIDENCE_SEQ NOCACHE;
GRANT SELECT ON EVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE TO AUXILIARY;

DROP TABLE PATHWAYEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PATHWAYEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOITEM_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PATHWAYEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT PATHWAYEVIDENCE_UK UNIQUE (BIOENTITY_ID, BIOITEM_ID) ) TABLESPACE DATA2;
CREATE INDEX PATHEV_REF_FK_INDEX ON PATHWAYEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_STRAIN_FK_INDEX ON PATHWAYEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_EXPT_FK_INDEX ON PATHWAYEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_SOURCE_FK_INDEX ON PATHWAYEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_BIOENT_FK_INDEX ON PATHWAYEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX PATHEV_PATH_FK_INDEX ON PATHWAYEVIDENCE (BIOITEM_ID) TABLESPACE DATA2;
ALTER TABLE PATHWAYEVIDENCE
ADD CONSTRAINT PATHEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYEVIDENCE
ADD CONSTRAINT PATHEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYEVIDENCE
ADD CONSTRAINT PATHEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYEVIDENCE
ADD CONSTRAINT PATHEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYEVIDENCE
ADD CONSTRAINT PATHEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYEVIDENCE
ADD CONSTRAINT PATHEV_PATH_FK FOREIGN KEY (BIOITEM_ID) REFERENCES BIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PATHWAYEVIDENCE
ADD CONSTRAINT PATHEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PATHWAYEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PATHWAYEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PATHWAYEVIDENCE TO AUXILIARY;

DROP TABLE DOMAINEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE DOMAINEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOITEM_ID INTEGER NOT NULL,
START_INDEX INTEGER, 
END_INDEX INTEGER, 
EVALUE VARCHAR2(40), 
DOMAIN_STATUS VARCHAR2(40), 
DATE_OF_RUN DATE,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT DOMAINEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT DOMAINEVIDENCE_UK UNIQUE (BIOENTITY_ID, BIOITEM_ID, START_INDEX, END_INDEX) ) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_REF_FK_INDEX ON DOMAINEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_STRAIN_FK_INDEX ON DOMAINEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_EXPT_FK_INDEX ON DOMAINEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_SOURCE_FK_INDEX ON DOMAINEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_BIOENT_FK_INDEX ON DOMAINEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX DOMAINEV_DOMAIN_FK_INDEX ON DOMAINEVIDENCE (BIOITEM_ID) TABLESPACE DATA2;
ALTER TABLE DOMAINEVIDENCE 
ADD CONSTRAINT DOMAINEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINEVIDENCE
ADD CONSTRAINT DOMAINEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINEVIDENCE
ADD CONSTRAINT DOMAINEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINEVIDENCE
ADD CONSTRAINT DOMAINEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINEVIDENCE
ADD CONSTRAINT DOMAINEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINEVIDENCE  
ADD CONSTRAINT DOMAINEV_DOMAIN_FK FOREIGN KEY (BIOITEM_ID) REFERENCES DOMAINBIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINEVIDENCE 
ADD CONSTRAINT DOMAINEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DOMAINEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAINEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAINEVIDENCE TO AUXILIARY;

DROP TABLE LITERATUREEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE LITERATUREEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NULL,
TOPIC VARCHAR2(40) NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT LITERATUREEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT LITERATUREEVIDENCE_UK UNIQUE (BIOENTITY_ID, REFERENCE_ID, TOPIC) ) TABLESPACE DATA2;
CREATE INDEX LITEV_REF_FK_INDEX ON LITERATUREEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX LITEV_STRAIN_FK_INDEX ON LITERATUREEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX LITEV_EXPT_FK_INDEX ON LITERATUREEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX LITEV_SOURCE_FK_INDEX ON LITERATUREEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX LITEV_BIOENT_FK_INDEX ON LITERATUREEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE LITERATUREEVIDENCE 
ADD CONSTRAINT LITEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREEVIDENCE
ADD CONSTRAINT LITEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREEVIDENCE
ADD CONSTRAINT LITEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREEVIDENCE
ADD CONSTRAINT LITEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREEVIDENCE
ADD CONSTRAINT LITEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREEVIDENCE 
ADD CONSTRAINT LITEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON LITERATUREEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LITERATUREEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LITERATUREEVIDENCE TO AUXILIARY;

DROP TABLE ARCH_LITERATUREEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE ARCH_LITERATUREEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NULL,
TOPIC VARCHAR2(60) NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT ARCH_LITERATUREEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT ARCH_LITERATUREEVIDENCE_UK UNIQUE (BIOENTITY_ID, REFERENCE_ID, TOPIC) ) TABLESPACE DATA2;
CREATE INDEX ARLITEV_REF_FK_INDEX ON ARCH_LITERATUREEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX ARLITEV_STRAIN_FK_INDEX ON ARCH_LITERATUREEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX ARLITEV_EXPT_FK_INDEX ON ARCH_LITERATUREEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX ARLITEV_SOURCE_FK_INDEX ON ARCH_LITERATUREEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX ARLITEV_BIOENT_FK_INDEX ON ARCH_LITERATUREEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE ARCH_LITERATUREEVIDENCE
ADD CONSTRAINT ARLITEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREEVIDENCE
ADD CONSTRAINT ARLITEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREEVIDENCE
ADD CONSTRAINT ARLITEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREEVIDENCE
ADD CONSTRAINT ARLITEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREEVIDENCE
ADD CONSTRAINT ARLITEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ARCH_LITERATUREEVIDENCE
ADD CONSTRAINT ARLITEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON ARCH_LITERATUREEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ARCH_LITERATUREEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ARCH_LITERATUREEVIDENCE TO AUXILIARY;

DROP TABLE BIOENTITYEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
INFO_KEY VARCHAR2(60) NOT NULL,
INFO_VALUE VARCHAR2(1000) NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT BIOENTITYEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT BIOENTITYEVIDENCE_UK UNIQUE (BIOENTITY_ID, REFERENCE_ID, STRAIN_ID, INFO_KEY) ) TABLESPACE DATA2;
CREATE INDEX BIOENTEV_REF_FK_INDEX ON BIOENTITYEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX BIOENTEV_STRAIN_FK_INDEX ON BIOENTITYEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX BIOENTEV_EXPT_FK_INDEX ON BIOENTITYEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX BIOENTEV_SOURCE_FK_INDEX ON BIOENTITYEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX BIOENTEV_BIOENT_FK_INDEX ON BIOENTITYEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE BIOENTITYEVIDENCE
ADD CONSTRAINT BIOENTEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYEVIDENCE
ADD CONSTRAINT BIOENTEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYEVIDENCE
ADD CONSTRAINT BIOENTEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYEVIDENCE
ADD CONSTRAINT BIOENTEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYEVIDENCE
ADD CONSTRAINT BIOENTEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYEVIDENCE
ADD CONSTRAINT BIOENTEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYEVIDENCE TO AUXILIARY;

DROP TABLE ALIASEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE ALIASEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
ALIAS_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT ALIASEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT ALIASEVIDENCE_UK UNIQUE (REFERENCE_ID, ALIAS_ID) ) TABLESPACE DATA2;
CREATE INDEX ALIASEV_REF_FK_INDEX ON ALIASEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX ALIASEV_STRAIN_FK_INDEX ON ALIASEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX ALIASEV_EXPT_FK_INDEX ON ALIASEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX ALIASEV_SOURCE_FK_INDEX ON ALIASEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX ALIASEV_BIOENT_FK_INDEX ON ALIASEVIDENCE (ALIAS_ID) TABLESPACE DATA2;
ALTER TABLE ALIASEVIDENCE
ADD CONSTRAINT ALIASEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ALIASEVIDENCE
ADD CONSTRAINT ALIASEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ALIASEVIDENCE
ADD CONSTRAINT ALIASEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ALIASEVIDENCE
ADD CONSTRAINT ALIASEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ALIASEVIDENCE
ADD CONSTRAINT ALIASEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ALIASEVIDENCE
ADD CONSTRAINT ALIASEV_BIOENT_FK FOREIGN KEY (ALIAS_ID) REFERENCES ALIAS (ALIAS_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON ALIASEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ALIASEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ALIASEVIDENCE TO AUXILIARY;

DROP TABLE REGULATIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE REGULATIONEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY1_ID INTEGER NOT NULL,
BIOENTITY2_ID INTEGER NOT NULL,
CONDITIONS_KEY VARCHAR2(1000) NULL,
DIRECTION VARCHAR2(100),
PVALUE VARCHAR2(40),
FDR VARCHAR2(40),
CONSTRUCT VARCHAR2(100),
ASSAY VARCHAR2(300),
NOTE VARCHAR2(1000) NULL,
CONSTRAINT REGULATIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT REGULATIONEVIDENCE_UK UNIQUE (BIOENTITY1_ID, BIOENTITY2_ID, EXPERIMENT_ID, REFERENCE_ID, STRAIN_ID, CONDITIONS_KEY)) TABLESPACE DATA2;
CREATE INDEX REGEV_REF_FK_INDEX ON REGULATIONEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_STRAIN_FK_INDEX ON REGULATIONEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_EXPT_FK_INDEX ON REGULATIONEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_SOURCE_FK_INDEX ON REGULATIONEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_BIOENT1_FK_INDEX ON REGULATIONEVIDENCE (BIOENTITY1_ID) TABLESPACE DATA2;
CREATE INDEX REGEV_BIOENT2_FK_INDEX ON REGULATIONEVIDENCE (BIOENTITY2_ID) TABLESPACE DATA2;
ALTER TABLE REGULATIONEVIDENCE 
ADD CONSTRAINT REGEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONEVIDENCE
ADD CONSTRAINT REGEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONEVIDENCE
ADD CONSTRAINT REGEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONEVIDENCE
ADD CONSTRAINT REGEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONEVIDENCE
ADD CONSTRAINT REGEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONEVIDENCE 
ADD CONSTRAINT REGEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONEVIDENCE 
ADD CONSTRAINT REGEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REGULATIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REGULATIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REGULATIONEVIDENCE TO AUXILIARY;

DROP TABLE EXPRESSIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE EXPRESSIONEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
DESCRIPTION CLOB,
DATASETCOLUMN_ID INTEGER,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT EXPRESSIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT EXPRESSIONEVIDENCE_UK UNIQUE (DATASETCOLUMN_ID)) TABLESPACE DATA2;
CREATE INDEX EXPEV_REF_FK_INDEX ON EXPRESSIONEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX EXPEV_STRAIN_FK_INDEX ON EXPRESSIONEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX EXPEV_EXPT_FK_INDEX ON EXPRESSIONEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX EXPEV_SOURCE_FK_INDEX ON EXPRESSIONEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
ALTER TABLE EXPRESSIONEVIDENCE
ADD CONSTRAINT EXPEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONEVIDENCE
ADD CONSTRAINT EXPEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONEVIDENCE
ADD CONSTRAINT EXPEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONEVIDENCE
ADD CONSTRAINT EXPEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONEVIDENCE
ADD CONSTRAINT EXPEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPRESSIONEVIDENCE
ADD CONSTRAINT EXPEV_DSETCOL_FK FOREIGN KEY (DATASETCOLUMN_ID) REFERENCES DATASETCOLUMNBIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON EXPRESSIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPRESSIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPRESSIONEVIDENCE TO AUXILIARY;

DROP TABLE BIOENTITYDATA CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYDATA (
BIOENTITYDATA_ID INTEGER NOT NULL,
EVIDENCE_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
VALUE DECIMAL(7, 3) NOT NULL,
CONSTRAINT BIOENTITYDATA_PK PRIMARY KEY (BIOENTITYDATA_ID),
CONSTRAINT BIOENTITYDATA_UK UNIQUE (EVIDENCE_ID, BIOENTITY_ID)) TABLESPACE DATA3;
CREATE INDEX DAT_BIOENT_FK_INDEX ON BIOENTITYDATA (BIOENTITY_ID) TABLESPACE DATA3;
CREATE INDEX DAT_EV_FK_INDEX ON BIOENTITYDATA (EVIDENCE_ID) TABLESPACE DATA3;
ALTER TABLE BIOENTITYDATA
ADD CONSTRAINT DAT_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYDATA
ADD CONSTRAINT DAT_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYDATA TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYDATA TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYDATA TO AUXILIARY;
DROP SEQUENCE DATA_SEQ;
CREATE SEQUENCE DATA_SEQ NOCACHE;

DROP TABLE BINDINGEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE BINDINGEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL, 
TOTAL_SCORE VARCHAR2(10) NOT NULL, 
EXPERT_CONFIDENCE VARCHAR2(40) NOT NULL, 
OBJ_URL VARCHAR2(500) NOT NULL, 
MOTIF_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT BINDINGEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT BINDINGEVIDENCE_UK UNIQUE (BIOENTITY_ID, MOTIF_ID) ) TABLESPACE DATA2;
CREATE INDEX BINDEV_REF_FK_INDEX ON BINDINGEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX BINDEV_STRAIN_FK_INDEX ON BINDINGEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX BINDEV_EXPT_FK_INDEX ON BINDINGEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX BINDEV_SOURCE_FK_INDEX ON BINDINGEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX BINDEV_BIOENT_FK_INDEX ON BINDINGEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE BINDINGEVIDENCE 
ADD CONSTRAINT BINDEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGEVIDENCE
ADD CONSTRAINT BINDEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGEVIDENCE
ADD CONSTRAINT BINDEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGEVIDENCE
ADD CONSTRAINT BINDEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGEVIDENCE
ADD CONSTRAINT BINDEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGEVIDENCE 
ADD CONSTRAINT BINDEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BINDINGEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BINDINGEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BINDINGEVIDENCE TO AUXILIARY;

DROP TABLE GOEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE GOEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
GO_EVIDENCE VARCHAR2(40) NOT NULL, 
ANNOTATION_TYPE VARCHAR2(40) NOT NULL, 
QUALIFIER VARCHAR2(40) NOT NULL,
CONDITIONS_KEY VARCHAR2(1000) NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT GOEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT GOEVIDENCE_UK UNIQUE (BIOENTITY_ID, BIOCONCEPT_ID, GO_EVIDENCE, REFERENCE_ID, CONDITIONS_KEY)) TABLESPACE DATA2;
CREATE INDEX GOEV_REF_FK_INDEX ON GOEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_STRAIN_FK_INDEX ON GOEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_EXPT_FK_INDEX ON GOEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_SOURCE_FK_INDEX ON GOEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_BIOENT_FK_INDEX ON GOEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX GOEV_BIOCON_FK_INDEX ON GOEVIDENCE	(BIOCONCEPT_ID) TABLESPACE DATA2;
ALTER TABLE GOEVIDENCE
ADD CONSTRAINT GOEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOEVIDENCE
ADD CONSTRAINT GOEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOEVIDENCE
ADD CONSTRAINT GOEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOEVIDENCE
ADD CONSTRAINT GOEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOEVIDENCE
ADD CONSTRAINT GOEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOEVIDENCE 
ADD CONSTRAINT GOEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOEVIDENCE 
ADD CONSTRAINT GOEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES GOBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GOEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOEVIDENCE TO AUXILIARY;

DROP TABLE PHENOTYPEEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PHENOTYPEEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
MUTANT_TYPE VARCHAR2(100),
STRAIN_DETAILS VARCHAR2(2000),
EXPERIMENT_DETAILS VARCHAR2(2000),
CONDITIONS_KEY VARCHAR2(1000) NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PHENOTYPEEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT PHENOTYPEEVIDENCE_UK UNIQUE (BIOENTITY_ID, BIOCONCEPT_ID, STRAIN_ID, EXPERIMENT_ID, REFERENCE_ID, EXPERIMENT_DETAILS, MUTANT_TYPE, CONDITIONS_KEY) ) TABLESPACE DATA2;
CREATE INDEX PHENOEV_REF_FK_INDEX ON PHENOTYPEEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_STRAIN_FK_INDEX ON PHENOTYPEEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_EXPT_FK_INDEX ON PHENOTYPEEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_SOURCE_FK_INDEX ON PHENOTYPEEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_BIOENT_FK_INDEX ON PHENOTYPEEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX PHENOEV_BIOCON_FK_INDEX ON PHENOTYPEEVIDENCE (BIOCONCEPT_ID) TABLESPACE DATA2;
ALTER TABLE PHENOTYPEEVIDENCE 
ADD CONSTRAINT PHENOEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEEVIDENCE
ADD CONSTRAINT PHENOEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEEVIDENCE
ADD CONSTRAINT PHENOEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEEVIDENCE
ADD CONSTRAINT PHENOEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEEVIDENCE
ADD CONSTRAINT PHENOEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEEVIDENCE 
ADD CONSTRAINT PHENOEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEEVIDENCE 
ADD CONSTRAINT PHENOEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES PHENOTYPEBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHENOTYPEEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPEEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPEEVIDENCE TO AUXILIARY;

DROP TABLE ECNUMBEREVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE ECNUMBEREVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT ECNUMBEREVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT ECNUMBEREVIDENCE_UK UNIQUE (BIOENTITY_ID, BIOCONCEPT_ID) ) TABLESPACE DATA2;
CREATE INDEX ECEV_REF_FK_INDEX ON ECNUMBEREVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_STRAIN_FK_INDEX ON ECNUMBEREVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_EXPT_FK_INDEX ON ECNUMBEREVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_SOURCE_FK_INDEX ON ECNUMBEREVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_BIOENT_FK_INDEX ON ECNUMBEREVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX ECEV_BIOCON_FK_INDEX ON ECNUMBEREVIDENCE	(BIOCONCEPT_ID) TABLESPACE DATA2;
ALTER TABLE ECNUMBEREVIDENCE
ADD CONSTRAINT ECEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ECNUMBEREVIDENCE
ADD CONSTRAINT ECEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ECNUMBEREVIDENCE
ADD CONSTRAINT ECEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ECNUMBEREVIDENCE
ADD CONSTRAINT ECEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ECNUMBEREVIDENCE
ADD CONSTRAINT ECEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ECNUMBEREVIDENCE
ADD CONSTRAINT ECEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE ECNUMBEREVIDENCE
ADD CONSTRAINT ECEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON ECNUMBEREVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ECNUMBEREVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ECNUMBEREVIDENCE TO AUXILIARY;

DROP TABLE PROTEINEXPERIMENTEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PROTEINEXPERIMENTEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
DATA_VALUE VARCHAR2(25) NOT NULL,
DATA_UNIT VARCHAR2(25) NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PROTEINEXPERIMENTEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT PROTEINEXPERIMENTEVIDENCE_UK UNIQUE (BIOENTITY_ID, EXPERIMENT_ID) ) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_REF_FK_INDEX ON PROTEINEXPERIMENTEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_STRAIN_FK_INDEX ON PROTEINEXPERIMENTEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_EXPT_FK_INDEX ON PROTEINEXPERIMENTEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_SOURCE_FK_INDEX ON PROTEINEXPERIMENTEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PROTEXPEV_BIOENT_FK_INDEX ON PROTEINEXPERIMENTEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE PROTEINEXPERIMENTEVIDENCE
ADD CONSTRAINT PROTEXPEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTEVIDENCE
ADD CONSTRAINT PROTEXPEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTEVIDENCE
ADD CONSTRAINT PROTEXPEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTEVIDENCE
ADD CONSTRAINT PROTEXPEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTEVIDENCE
ADD CONSTRAINT PROTEXPEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINEXPERIMENTEVIDENCE
ADD CONSTRAINT PROTEXPEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PROTEINEXPERIMENTEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINEXPERIMENTEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINEXPERIMENTEVIDENCE TO AUXILIARY;

DROP TABLE GENINTERACTIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE GENINTERACTIONEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NULL,
PHENOTYPE_ID INTEGER,
MUTANT_TYPE VARCHAR2(100),
ANNOTATION_TYPE VARCHAR2(40) NOT NULL, 
BAIT_HIT VARCHAR2(20) NOT NULL, 
BIOENTITY1_ID INTEGER NOT NULL, 
BIOENTITY2_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT GENINTERACTIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT GENINTERACTIONEVIDENCE_UK UNIQUE (BIOENTITY1_ID, BIOENTITY2_ID, BAIT_HIT, EXPERIMENT_ID, REFERENCE_ID)) TABLESPACE DATA2;
CREATE INDEX GENINTEV_REF_FK_INDEX ON GENINTERACTIONEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_STRAIN_FK_INDEX ON GENINTERACTIONEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_EXPT_FK_INDEX ON GENINTERACTIONEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_SOURCE_FK_INDEX ON GENINTERACTIONEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_BIOENT2_INDEX ON GENINTERACTIONEVIDENCE (BIOENTITY2_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_BIOENT1_INDEX ON GENINTERACTIONEVIDENCE (BIOENTITY1_ID) TABLESPACE DATA2;
CREATE INDEX GENINTEV_PHENO_FK_INDEX ON GENINTERACTIONEVIDENCE (PHENOTYPE_ID) TABLESPACE DATA2;
ALTER TABLE GENINTERACTIONEVIDENCE 
ADD CONSTRAINT GENINTEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE
ADD CONSTRAINT GENINTEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE
ADD CONSTRAINT GENINTEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE
ADD CONSTRAINT GENINTEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE
ADD CONSTRAINT GENINTEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE 
ADD CONSTRAINT GENINTEV_PHENO_FK FOREIGN KEY (PHENOTYPE_ID) REFERENCES PHENOTYPEBIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE
ADD CONSTRAINT GENINTEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE
ADD CONSTRAINT GENINTEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GENINTERACTIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GENINTERACTIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GENINTERACTIONEVIDENCE TO AUXILIARY;

DROP TABLE PHYSINTERACTIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PHYSINTERACTIONEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NULL,
MODIFICATION VARCHAR2(40) NOT NULL, 
ANNOTATION_TYPE VARCHAR2(40) NOT NULL, 
BAIT_HIT VARCHAR2(20) NOT NULL, 
BIOENTITY1_ID INTEGER NOT NULL, 
BIOENTITY2_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PHYSINTERACTIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT PHYSINTERACTIONEVIDENCE_UK UNIQUE (BIOENTITY1_ID, BIOENTITY2_ID, BAIT_HIT, EXPERIMENT_ID, REFERENCE_ID)) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_REF_FK_INDEX ON PHYSINTERACTIONEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_STRAIN_FK_INDEX ON PHYSINTERACTIONEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_EXPT_FK_INDEX ON PHYSINTERACTIONEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_SOURCE_FK_INDEX ON PHYSINTERACTIONEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_BIOENT2_INDEX ON PHYSINTERACTIONEVIDENCE (BIOENTITY2_ID) TABLESPACE DATA2;
CREATE INDEX PHYSINTEV_BIOENT1_INDEX ON PHYSINTERACTIONEVIDENCE (BIOENTITY1_ID) TABLESPACE DATA2;
ALTER TABLE PHYSINTERACTIONEVIDENCE 
ADD CONSTRAINT PHYSINTEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONEVIDENCE
ADD CONSTRAINT PHYSINTEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONEVIDENCE
ADD CONSTRAINT PHYSINTEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONEVIDENCE
ADD CONSTRAINT PHYSINTEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONEVIDENCE
ADD CONSTRAINT PHYSINTEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONEVIDENCE
ADD CONSTRAINT PHYSINTEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONEVIDENCE
ADD CONSTRAINT PHYSINTEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHYSINTERACTIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHYSINTERACTIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHYSINTERACTIONEVIDENCE TO AUXILIARY;

DROP TABLE DNASEQUENCEEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE DNASEQUENCEEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
DNA_TYPE VARCHAR2(50) NOT NULL,
RESIDUES CLOB NOT NULL,
CONTIG_ID INTEGER NULL,
START_INDEX INTEGER NULL,
END_INDEX INTEGER NULL,
STRAND VARCHAR2(1),
NOTE VARCHAR2(1000) NULL,
CONSTRAINT DNASEQUENCEEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT DNASEQUENCEEVIDENCE_UK UNIQUE (BIOENTITY_ID, STRAIN_ID, DNA_TYPE) ) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_REF_FK_INDEX ON DNASEQUENCEEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_STRAIN_FK_INDEX ON DNASEQUENCEEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_EXPT_FK_INDEX ON DNASEQUENCEEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_SOURCE_FK_INDEX ON DNASEQUENCEEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_BIOENT_FK_INDEX ON DNASEQUENCEEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
CREATE INDEX DNASEQEV_CONTIG_FK_INDEX ON DNASEQUENCEEVIDENCE	(CONTIG_ID) TABLESPACE DATA2;
ALTER TABLE DNASEQUENCEEVIDENCE
ADD CONSTRAINT DNASEQEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEEVIDENCE
ADD CONSTRAINT DNASEQEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEEVIDENCE
ADD CONSTRAINT DNASEQEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEEVIDENCE
ADD CONSTRAINT DNASEQEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEEVIDENCE
ADD CONSTRAINT DNASEQEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEEVIDENCE
ADD CONSTRAINT DNASEQEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCEEVIDENCE
ADD CONSTRAINT DNASEQEV_CONTIG_FK FOREIGN KEY (CONTIG_ID) REFERENCES CONTIGBIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DNASEQUENCEEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DNASEQUENCEEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DNASEQUENCEEVIDENCE TO AUXILIARY;

DROP TABLE DNASEQUENCETAG CASCADE CONSTRAINTS;
CREATE TABLE DNASEQUENCETAG (
DNASEQUENCETAG_ID INTEGER NOT NULL,
EVIDENCE_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL,
RELATIVE_START_INDEX INTEGER NOT NULL,
RELATIVE_END_INDEX INTEGER NOT NULL,
CHROMOSOMAL_START_INDEX INTEGER NOT NULL,
CHROMOSOMAL_END_INDEX INTEGER NOT NULL,
PHASE VARCHAR2(1) NOT NULL,
SEQ_VERSION DATE,
COORD_VERSION DATE,
BIOENTITY_ID INTEGER NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT DNASEQUENCETAG_PK PRIMARY KEY (DNASEQUENCETAG_ID),
CONSTRAINT DNASEQUENCETAG_UK UNIQUE (EVIDENCE_ID, SUBCLASS, RELATIVE_START_INDEX, RELATIVE_END_INDEX)) TABLESPACE DATA1;
CREATE INDEX DNASEQTAG_EV_FK_INDEX ON DNASEQUENCETAG (EVIDENCE_ID) TABLESPACE DATA1;
CREATE INDEX DNASEQTAG_BIOENT_FK_INDEX ON DNASEQUENCETAG (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE DNASEQUENCETAG
ADD CONSTRAINT DNASEQTAG_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES DNASEQUENCEEVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DNASEQUENCETAG
ADD CONSTRAINT DNASEQTAG_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE DNASEQTAG_SEQ;
CREATE SEQUENCE DNASEQTAG_SEQ NOCACHE;
GRANT SELECT ON DNASEQUENCETAG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DNASEQUENCETAG TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DNASEQUENCETAG TO AUXILIARY;

DROP TABLE PROTEINSEQUENCEEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PROTEINSEQUENCEEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
PROTEIN_TYPE VARCHAR2(50) NOT NULL,
RESIDUES CLOB NOT NULL,
MOLECULAR_WEIGHT VARCHAR2(10),
PI VARCHAR2(10),
CAI VARCHAR2(10),
N_TERM_SEQ VARCHAR2(10) NOT NULL,
C_TERM_SEQ VARCHAR2(10) NOT NULL,
CODON_BIAS VARCHAR2(10),
FOP_SCORE VARCHAR2(10),
GRAVY_SCORE VARCHAR2(10),
AROMATICITY_SCORE VARCHAR2(10),
ALIPHATIC_INDEX VARCHAR2(10),
INSTABILITY_INDEX VARCHAR2(10),
ALA INTEGER NOT NULL,
ARG INTEGER NOT NULL,
ASN INTEGER NOT NULL,
ASP INTEGER NOT NULL,
CYS INTEGER NOT NULL,
GLN INTEGER NOT NULL,
GLU INTEGER NOT NULL,
GLY INTEGER NOT NULL,
HIS INTEGER NOT NULL,
ILE INTEGER NOT NULL,
LEU INTEGER NOT NULL,
LYS INTEGER NOT NULL,
MET INTEGER NOT NULL,
PHE INTEGER NOT NULL,
PRO INTEGER NOT NULL,
THR INTEGER NOT NULL,
SER INTEGER NOT NULL,
TRP INTEGER NOT NULL,
TYR INTEGER NOT NULL,
VAL INTEGER NOT NULL,
HYDROGEN INTEGER,
SULFUR INTEGER,
NITROGEN INTEGER,
OXYGEN INTEGER,
CARBON INTEGER,
YEAST_HALF_LIFE VARCHAR2(50),
ECOLI_HALF_LIFE VARCHAR2(50),
MAMMAL_HALF_LIFE VARCHAR2(50),
NO_CYS_EXT_COEFF VARCHAR2(50),
ALL_CYS_EXT_COEFF VARCHAR2(50),
ALL_HALF_CYS_EXT_COEFF VARCHAR2(50),
ALL_PAIRS_CYS_EXT_COEFF VARCHAR2(50),
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PROTEINSEQUENCEEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT PROTEINSEQUENCEEVIDENCE_UK UNIQUE (BIOENTITY_ID, STRAIN_ID, PROTEIN_TYPE) ) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_REF_FK_INDEX ON PROTEINSEQUENCEEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_STRAIN_FK_INDEX ON PROTEINSEQUENCEEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_EXPT_FK_INDEX ON PROTEINSEQUENCEEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_SOURCE_FK_INDEX ON PROTEINSEQUENCEEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PROTSEQEV_BIOENT_FK_INDEX ON PROTEINSEQUENCEEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PROTEINSEQUENCEEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINSEQUENCEEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINSEQUENCEEVIDENCE TO AUXILIARY;

DROP TABLE PHOSPHORYLATIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PHOSPHORYLATIONEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NOT NULL,
SITE_INDEX INTEGER NOT NULL,
SITE_RESIDUE VARCHAR2(1) NOT NULL,
NOTE VARCHAR2(1000) NULL,
CONSTRAINT PHOSPHORYLATIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT PHOSPHORYLATIONEVIDENCE_UK UNIQUE (BIOENTITY_ID, SITE_RESIDUE, SITE_INDEX, REFERENCE_ID) ) TABLESPACE DATA2;
CREATE INDEX PHOSEV_REF_FK_INDEX ON PHOSPHORYLATIONEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX PHOSEV_STRAIN_FK_INDEX ON PHOSPHORYLATIONEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX PHOSEV_EXPT_FK_INDEX ON PHOSPHORYLATIONEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX PHOSEV_SOURCE_FK_INDEX ON PHOSPHORYLATIONEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX PHOSEV_BIOENT_FK_INDEX ON PHOSPHORYLATIONEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE PHOSPHORYLATIONEVIDENCE
ADD CONSTRAINT PHOSEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONEVIDENCE
ADD CONSTRAINT PHOSEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONEVIDENCE
ADD CONSTRAINT PHOSEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONEVIDENCE
ADD CONSTRAINT PHOSEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONEVIDENCE
ADD CONSTRAINT PHOSEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONEVIDENCE
ADD CONSTRAINT PHOSEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHOSPHORYLATIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHOSPHORYLATIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHOSPHORYLATIONEVIDENCE TO AUXILIARY;

DROP TABLE HISTORYEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE HISTORYEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
SOURCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NULL,
EXPERIMENT_ID INTEGER NULL,
STRAIN_ID INTEGER NULL,
BIOENTITY_ID INTEGER NULL,
CATEGORY VARCHAR2(100) NULL,
HISTORY_TYPE VARCHAR2(50) NULL,
NOTE VARCHAR2(4000) NULL,
CONSTRAINT HISTORYEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT HISTORYEVIDENCE_UK UNIQUE (BIOENTITY_ID, HISTORY_TYPE, REFERENCE_ID, NOTE) ) TABLESPACE DATA2;
CREATE INDEX HISTEV_REF_FK_INDEX ON HISTORYEVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX HISTEV_STRAIN_FK_INDEX ON HISTORYEVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX HISTEV_EXPT_FK_INDEX ON HISTORYEVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
CREATE INDEX HISTEV_SOURCE_FK_INDEX ON HISTORYEVIDENCE (SOURCE_ID) TABLESPACE DATA2;
CREATE INDEX HISTEV_BIOENT_FK_INDEX ON HISTORYEVIDENCE (BIOENTITY_ID) TABLESPACE DATA2;
ALTER TABLE HISTORYEVIDENCE
ADD CONSTRAINT HISTEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYEVIDENCE
ADD CONSTRAINT HISTEV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYEVIDENCE
ADD CONSTRAINT HISTEV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYEVIDENCE
ADD CONSTRAINT HISTEV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYEVIDENCE
ADD CONSTRAINT HISTEV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE HISTORYEVIDENCE
ADD CONSTRAINT HISTEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON HISTORYEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTORYEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON HISTORYEVIDENCE TO AUXILIARY;

/* Condition */
DROP TABLE CONDITION CASCADE CONSTRAINTS;
CREATE TABLE CONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500),
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('GENERAL', 'TEMPERATURE', 'BIOENTITY', 'BIOCONCEPT', 'BIOITEM', 'CHEMICAL')),
EVIDENCE_ID INTEGER NOT NULL, 
ROLE VARCHAR2(40),
NOTE VARCHAR(1000), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT CONDITION_PK PRIMARY KEY (CONDITION_ID), 
CONSTRAINT CONDITION_UK UNIQUE (EVIDENCE_ID, FORMAT_NAME, SUBCLASS, ROLE) ) TABLESPACE DATA1;
ALTER TABLE CONDITION 
ADD CONSTRAINT COND_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE COND_SEQ;
CREATE SEQUENCE COND_SEQ NOCACHE;
GRANT SELECT ON CONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONDITION TO AUXILIARY;

DROP TABLE TEMPERATURECONDITION CASCADE CONSTRAINTS;
CREATE TABLE TEMPERATURECONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
TEMPERATURE FLOAT NOT NULL, 
CONSTRAINT TEMPERATURECONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1; 
ALTER TABLE TEMPERATURECONDITION 
ADD CONSTRAINT TEMPCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON TEMPERATURECONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON TEMPERATURECONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON TEMPERATURECONDITION TO AUXILIARY;

DROP TABLE BIOENTITYCONDITION CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYCONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL, 
CONSTRAINT BIOENTITYCONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1; 
ALTER TABLE BIOENTITYCONDITION 
ADD CONSTRAINT BIOENTITYCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOENTITYCOND_BIOENT_FK_INDEX ON BIOENTITYCONDITION (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITYCONDITION 
ADD CONSTRAINT BIOENTITYCOND_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYCONDITION TO AUXILIARY;

DROP TABLE BIOCONCEPTCONDITION CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPTCONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
BIOCONCEPT_ID INTEGER NOT NULL, 
CONSTRAINT BIOCONCEPTCONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1; 
ALTER TABLE BIOCONCEPTCONDITION 
ADD CONSTRAINT BIOCONCEPTCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOCONCEPTCOND_BIOCON_FK_INDEX ON BIOCONCEPTCONDITION (BIOCONCEPT_ID) TABLESPACE DATA1;
ALTER TABLE BIOCONCEPTCONDITION 
ADD CONSTRAINT BIOCONCEPTCOND_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOCONCEPTCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTCONDITION TO AUXILIARY;

DROP TABLE BIOITEMCONDITION CASCADE CONSTRAINTS;
CREATE TABLE BIOITEMCONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
BIOITEM_ID INTEGER NOT NULL, 
CONSTRAINT BIOITEMCONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1; 
ALTER TABLE BIOITEMCONDITION 
ADD CONSTRAINT BIOITEMCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOITEMCOND_BIOENT_FK_INDEX ON BIOITEMCONDITION (BIOITEM_ID) TABLESPACE DATA1;
ALTER TABLE BIOITEMCONDITION 
ADD CONSTRAINT BIOITEMCOND_BIOITEM_FK FOREIGN KEY (BIOITEM_ID) REFERENCES BIOITEM (BIOITEM_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOITEMCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOITEMCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOITEMCONDITION TO AUXILIARY;

DROP TABLE CHEMICALCONDITION CASCADE CONSTRAINTS;
CREATE TABLE CHEMICALCONDITION (
CONDITION_ID INTEGER NOT NULL,
AMOUNT VARCHAR2(500),
CONSTRAINT CHEMICALCONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1;
ALTER TABLE CHEMICALCONDITION
ADD CONSTRAINT CHEMCONDITION_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES BIOITEMCONDITION (CONDITION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CHEMICALCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALCONDITION TO AUXILIARY;

/* Paragraph */
DROP TABLE PARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE PARAGRAPH (
PARAGRAPH_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL,
CLASS VARCHAR2(100) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
CATEGORY VARCHAR2(40),
TEXT CLOB NOT NULL,
HTML CLOB NOT NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT PARAGRAPH_PK PRIMARY KEY (PARAGRAPH_ID),
CONSTRAINT PARAGRAPH_UK UNIQUE (FORMAT_NAME, CLASS, CATEGORY)) TABLESPACE DATA1;
CREATE INDEX PARA_SOURCE_FK_INDEX ON PARAGRAPH (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE PARAGRAPH
ADD CONSTRAINT PARA_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE PARA_SEQ;
CREATE SEQUENCE PARA_SEQ NOCACHE;
GRANT SELECT ON PARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH TO AUXILIARY;

DROP TABLE PARAGRAPH_REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE PARAGRAPH_REFERENCE ( 
PARAGRAPH_REFERENCE_ID INTEGER NOT NULL, 
PARAGRAPH_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER NOT NULL,
CONSTRAINT PARAGRAPH_REFERENCE_PK PRIMARY KEY (PARAGRAPH_REFERENCE_ID), 
CONSTRAINT PARAGRAPH_REFERENCE_UK UNIQUE (PARAGRAPH_ID, REFERENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX PARAREF_REF_FK_INDEX ON PARAGRAPH_REFERENCE (REFERENCE_ID) TABLESPACE DATA1;
CREATE INDEX PARAREF_PAR_FK_INDEX ON PARAGRAPH_REFERENCE (PARAGRAPH_ID) TABLESPACE DATA1;
ALTER TABLE PARAGRAPH_REFERENCE 
ADD CONSTRAINT PARAREF_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PARAGRAPH_REFERENCE 
ADD CONSTRAINT PARAREF_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE PARAREF_SEQ;
CREATE SEQUENCE PARAREF_SEQ NOCACHE;
GRANT SELECT ON PARAGRAPH_REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH_REFERENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH_REFERENCE TO AUXILIARY;

DROP TABLE BIOENTITYPARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYPARAGRAPH (
PARAGRAPH_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
CONSTRAINT BIOENTITYPARAGRAPH_PK PRIMARY KEY (PARAGRAPH_ID) ) TABLESPACE DATA1;
CREATE INDEX BIOENTPARA_BIOENT_FK_INDEX ON BIOENTITYPARAGRAPH (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITYPARAGRAPH
ADD CONSTRAINT BIOENTPARA_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYPARAGRAPH
ADD CONSTRAINT BIOENTPARA_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYPARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYPARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYPARAGRAPH TO AUXILIARY;

DROP TABLE STRAINPARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE STRAINPARAGRAPH (
PARAGRAPH_ID INTEGER NOT NULL,
STRAIN_ID INTEGER NOT NULL,
CONSTRAINT STRAINPARAGRAPH_PK PRIMARY KEY (PARAGRAPH_ID) ) TABLESPACE DATA1;
CREATE INDEX STRAINPARA_STRAIN_FK_INDEX ON STRAINPARAGRAPH (STRAIN_ID) TABLESPACE DATA1;
ALTER TABLE STRAINPARAGRAPH
ADD CONSTRAINT STRAINPARA_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE STRAINPARAGRAPH
ADD CONSTRAINT STRAINPARA_STRAIN_ID_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON STRAINPARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAINPARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAINPARAGRAPH TO AUXILIARY;

DROP TABLE REFERENCEPARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE REFERENCEPARAGRAPH (
PARAGRAPH_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
CONSTRAINT REFERENCEPARAGRAPH_PK PRIMARY KEY (PARAGRAPH_ID) ) TABLESPACE DATA1;
CREATE INDEX REFPARA_STRAIN_FK_INDEX ON REFERENCEPARAGRAPH (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCEPARAGRAPH
ADD CONSTRAINT REFPARA_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCEPARAGRAPH
ADD CONSTRAINT REFPARA_STRAIN_ID_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCEPARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEPARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEPARAGRAPH TO AUXILIARY;

/* Auxiliary */
DROP TABLE AUX_DISAMBIG CASCADE CONSTRAINTS;
CREATE TABLE AUX_DISAMBIG ( 
AUX_DISAMBIG_ID INTEGER NOT NULL, 
DISAMBIG_KEY VARCHAR2(200) NOT NULL, 
CLASS VARCHAR(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'BIOITEM', 'REFERENCE', 'AUTHOR', 'STRAIN', 'TAG')),
SUBCLASS VARCHAR(40) CHECK (SUBCLASS IN ('LOCUS', 'GO', 'PHENOTYPE', 'OBSERVABLE', 'ECNUMBER', 'DOMAIN', 'CONTIG', 'CHEMICAL', 'DATASET', 'DATASETCOLUMN', 'RESERVEDNAME')),
OBJ_ID INTEGER NOT NULL, 
CONSTRAINT AUX_DISAMBIG_PK PRIMARY KEY (AUX_DISAMBIG_ID), 
CONSTRAINT AUX_DISAMBIG_UK UNIQUE (DISAMBIG_KEY, CLASS, SUBCLASS) ) TABLESPACE DATA1;
CREATE INDEX AUX_DISAMBIG_OBJID_INDEX ON AUX_DISAMBIG (OBJ_ID) TABLESPACE DATA1;
DROP SEQUENCE AUX_DISAMBIG_SEQ;
CREATE SEQUENCE AUX_DISAMBIG_SEQ NOCACHE;
GRANT SELECT ON AUX_DISAMBIG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_DISAMBIG TO AUXILIARY;

DROP TABLE AUX_LOCUSTABS CASCADE CONSTRAINTS;
CREATE TABLE AUX_LOCUSTABS ( 
BIOENTITY_ID INTEGER NOT NULL, 
SUMMARY NUMBER(1) NOT NULL,
SEQ NUMBER(1) NOT NULL,
HISTORY NUMBER(1) NOT NULL, 
LITERATURE NUMBER(1) NOT NULL, 
GO NUMBER(1) NOT NULL, 
PHENOTYPE NUMBER(1) NOT NULL, 
INTERACTIONS NUMBER(1) NOT NULL, 
EXPRESSION NUMBER(1) NOT NULL, 
REGULATION NUMBER(1) NOT NULL, 
PROTEIN NUMBER(1) NOT NULL, 
WIKI NUMBER(1) NOT NULL, 
CONSTRAINT AUX_LOCUSTABS_PK PRIMARY KEY (BIOENTITY_ID) ) TABLESPACE DATA1;
GRANT SELECT ON AUX_LOCUSTABS TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON AUX_LOCUSTABS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_LOCUSTABS TO AUXILIARY;

DROP TABLE AUX_INTERACTION CASCADE CONSTRAINTS;
CREATE TABLE AUX_INTERACTION (
AUX_INTERACTION_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'BIOITEM', 'REFERENCE')),
BIOENTITY_ID INTEGER NOT NULL,
INTERACTION_TYPE VARCHAR2(100) NOT NULL,
EVIDENCE_COUNT INTEGER,
CONSTRAINT AUX_INTERACTION_PK PRIMARY KEY (AUX_INTERACTION_ID),
CONSTRAINT AUX_INTERACTION_CLASS_UK UNIQUE (BIOENTITY_ID, CLASS, INTERACTION_TYPE, FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX INTER_BIOENT_FK_INDX ON AUX_INTERACTION (BIOENTITY_ID) TABLESPACE DATA1;
CREATE INDEX INTER_TYPE_INDX ON AUX_INTERACTION (INTERACTION_TYPE) TABLESPACE DATA1;
ALTER TABLE AUX_INTERACTION
ADD CONSTRAINT INTER_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE AUX_INTERACTION_SEQ;
CREATE SEQUENCE AUX_INTERACTION_SEQ NOCACHE;
GRANT SELECT ON AUX_INTERACTION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_INTERACTION TO AUXILIARY;

DROP TABLE AUX_BIOENTITYINTERACTION CASCADE CONSTRAINTS;
CREATE TABLE AUX_BIOENTITYINTERACTION (
AUX_INTERACTION_ID INTEGER NOT NULL,
INTERACTOR_ID INTEGER NOT NULL,
DIRECTION VARCHAR2(40) NOT NULL,
CONSTRAINT AUX_BIOENTITYINTERACTION_PK PRIMARY KEY (AUX_INTERACTION_ID) ) TABLESPACE DATA1;
CREATE INDEX BIOENTINTER_BIOENT_FK_INDX ON AUX_BIOENTITYINTERACTION (INTERACTOR_ID) TABLESPACE DATA1;
ALTER TABLE AUX_BIOENTITYINTERACTION
ADD CONSTRAINT BIOENTINTER_INTER_FK FOREIGN KEY (AUX_INTERACTION_ID) REFERENCES AUX_INTERACTION (AUX_INTERACTION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE AUX_BIOENTITYINTERACTION
ADD CONSTRAINT BIOENTINTER_BIOENT_FK FOREIGN KEY (INTERACTOR_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUX_BIOENTITYINTERACTION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_BIOENTITYINTERACTION TO AUXILIARY;

DROP TABLE AUX_BIOCONCEPTINTERACTION CASCADE CONSTRAINTS;
CREATE TABLE AUX_BIOCONCEPTINTERACTION (
AUX_INTERACTION_ID INTEGER NOT NULL,
INTERACTOR_ID INTEGER NOT NULL,
CONSTRAINT AUX_BIOCONCEPTINTERACTION_PK PRIMARY KEY (AUX_INTERACTION_ID) ) TABLESPACE DATA1;
CREATE INDEX BIOCONINTER_BIOCON_FK_INDX ON AUX_BIOCONCEPTINTERACTION (INTERACTOR_ID) TABLESPACE DATA1;
ALTER TABLE AUX_BIOCONCEPTINTERACTION
ADD CONSTRAINT BIOCONINTER_INTER_FK FOREIGN KEY (AUX_INTERACTION_ID) REFERENCES AUX_INTERACTION (AUX_INTERACTION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE AUX_BIOCONCEPTINTERACTION
ADD CONSTRAINT BIOCONINTER_BIOCON_FK FOREIGN KEY (INTERACTOR_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUX_BIOCONCEPTINTERACTION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_BIOCONCEPTINTERACTION TO AUXILIARY;

DROP TABLE AUX_BIOITEMINTERACTION CASCADE CONSTRAINTS;
CREATE TABLE AUX_BIOITEMINTERACTION (
AUX_INTERACTION_ID INTEGER NOT NULL,
INTERACTOR_ID INTEGER NOT NULL,
CONSTRAINT AUX_BIOITEMINTERACTION_PK PRIMARY KEY (AUX_INTERACTION_ID) ) TABLESPACE DATA1;
CREATE INDEX BIOITEMINTER_BIOITEM_FK_INDX ON AUX_BIOITEMINTERACTION (INTERACTOR_ID) TABLESPACE DATA1;
ALTER TABLE AUX_BIOITEMINTERACTION
ADD CONSTRAINT BIOITEMINTER_INTER_FK FOREIGN KEY (AUX_INTERACTION_ID) REFERENCES AUX_INTERACTION (AUX_INTERACTION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE AUX_BIOITEMINTERACTION
ADD CONSTRAINT BIOITEMINTER_BIOITEM_FK FOREIGN KEY (INTERACTOR_ID) REFERENCES BIOITEM (BIOITEM_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUX_BIOITEMINTERACTION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_BIOITEMINTERACTION TO AUXILIARY;

DROP TABLE AUX_REFERENCEINTERACTION CASCADE CONSTRAINTS;
CREATE TABLE AUX_REFERENCEINTERACTION (
AUX_INTERACTION_ID INTEGER NOT NULL,
INTERACTOR_ID INTEGER NOT NULL,
CONSTRAINT AUX_REFERENCEINTERACTION_PK PRIMARY KEY (AUX_INTERACTION_ID) ) TABLESPACE DATA1;
CREATE INDEX REFINTER_REF_FK_INDX ON AUX_REFERENCEINTERACTION (INTERACTOR_ID) TABLESPACE DATA1;
ALTER TABLE AUX_REFERENCEINTERACTION
ADD CONSTRAINT REFINTER_INTER_FK FOREIGN KEY (AUX_INTERACTION_ID) REFERENCES AUX_INTERACTION (AUX_INTERACTION_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE AUX_REFERENCEINTERACTION
ADD CONSTRAINT REFINTER_REF_FK FOREIGN KEY (INTERACTOR_ID) REFERENCES REFERENCE (REFERENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUX_REFERENCEINTERACTION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_REFERENCEINTERACTION TO AUXILIARY;

/* Misc */
DROP TABLE TAG CASCADE CONSTRAINTS;
CREATE TABLE TAG (
TAG_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
DESCRIPTION VARCHAR2(400) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT TAG_PK PRIMARY KEY (TAG_ID) ,
CONSTRAINT TAG_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
DROP SEQUENCE TAG_SEQ;
CREATE SEQUENCE TAG_SEQ NOCACHE;
GRANT SELECT ON TAG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON TAG TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON TAG TO AUXILIARY;

DROP TABLE ALIAS CASCADE CONSTRAINTS;
CREATE TABLE ALIAS (
ALIAS_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500),
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'BIOITEM', 'REFERENCE', 'EXPERIMENT', 'STRAIN')),
CATEGORY VARCHAR2(40),
SOURCE_ID INTEGER NOT NULL,
NOTE VARCHAR2(1000) NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT ALIAS_PK PRIMARY KEY (ALIAS_ID),
CONSTRAINT ALIAS_UK UNIQUE (FORMAT_NAME, CLASS, DISPLAY_NAME, CATEGORY) ) TABLESPACE DATA1;
CREATE INDEX ALIAS_SOURCE_FK_INDEX ON ALIAS (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE ALIAS
ADD CONSTRAINT ALIAS_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE ALIAS_SEQ;
CREATE SEQUENCE ALIAS_SEQ NOCACHE;
GRANT SELECT ON ALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ALIAS TO AUXILIARY;

DROP TABLE URL CASCADE CONSTRAINTS;
CREATE TABLE URL (
URL_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'BIOITEM', 'REFERENCE', 'EXPERIMENT', 'STRAIN')),
CATEGORY VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT URL_PK PRIMARY KEY (URL_ID),
CONSTRAINT URL_UK UNIQUE (CLASS, FORMAT_NAME, DISPLAY_NAME, CATEGORY) ) TABLESPACE DATA2;
DROP SEQUENCE URL_SEQ;
CREATE SEQUENCE URL_SEQ NOCACHE;
CREATE INDEX URL_SOURCE_FK_INDEX ON URL (SOURCE_ID) TABLESPACE DATA2;
ALTER TABLE URL
ADD CONSTRAINT URL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON URL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON URL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON URL TO AUXILIARY;

DROP TABLE RELATION CASCADE CONSTRAINTS;
CREATE TABLE RELATION (
RELATION_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
SOURCE_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'BIOITEM', 'REFERENCE', 'EXPERIMENT', 'STRAIN')),
RELATION_TYPE VARCHAR2(40),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT RELATION_PK PRIMARY KEY (RELATION_ID),
CONSTRAINT RELATION_UK UNIQUE (FORMAT_NAME, CLASS, RELATION_TYPE) ) TABLESPACE DATA1;
CREATE INDEX REL_SOURCE_FK_INDEX ON RELATION (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE RELATION
ADD CONSTRAINT REL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE RELATION_SEQ;
CREATE SEQUENCE RELATION_SEQ NOCACHE;
GRANT SELECT ON RELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON RELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON RELATION TO AUXILIARY;