DROP TRIGGER SOURCE_TRIGGER;
--/
CREATE TRIGGER SOURCE_TRIGGER
BEFORE INSERT ON source
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.source_id FROM DUAL;
END;
/

DROP TRIGGER DBENTITY_TRIGGER;
--/
CREATE TRIGGER DBENTITY_TRIGGER
BEFORE INSERT ON dbentity
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.dbentity_id FROM DUAL;
END;
/

DROP TRIGGER KEYWORD_TRIGGER;
--/
CREATE TRIGGER KEYWORD_TRIGGER
BEFORE INSERT ON keyword
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.keyword_id FROM DUAL;
END;
/

DROP TRIGGER TAXONOMY_TRIGGER;
--/
CREATE TRIGGER TAXONOMY_TRIGGER
BEFORE INSERT ON taxonomy
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.taxonomy_id FROM DUAL;
END;
/

DROP TRIGGER BOOK_TRIGGER;
--/
CREATE TRIGGER BOOK_TRIGGER
BEFORE INSERT ON book
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.book_id FROM DUAL;
END;
/

DROP TRIGGER JOURNAL_TRIGGER;
--/
CREATE TRIGGER JOURNAL_TRIGGER
BEFORE INSERT ON journal
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.journal_id FROM DUAL;
END;
/

DROP TRIGGER AUTHOR_TRIGGER;
--/
CREATE TRIGGER AUTHOR_TRIGGER
BEFORE INSERT ON author
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.author_id FROM DUAL;
END;
/

DROP TRIGGER REFTYPE_TRIGGER;
--/
CREATE TRIGGER REFTYPE_TRIGGER
BEFORE INSERT ON reftype
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.reftype_id FROM DUAL;
END;
/

DROP TRIGGER COLLEAGUE_TRIGGER;
--/
CREATE TRIGGER COLLEAGUE_TRIGGER
BEFORE INSERT ON colleague
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.colleague_id FROM DUAL;
END;
/

DROP TRIGGER LOCUS_ALIAS_TRIGGER;
--/
CREATE TRIGGER LOCUS_ALIAS_TRIGGER
BEFORE INSERT ON locus_alias
FOR EACH ROW
BEGIN
SELECT alias_seq.nextval INTO :new.alias_id FROM DUAL;
END;
/

DROP TRIGGER LOCUS_URL_TRIGGER;
--/
CREATE TRIGGER LOCUS_URL_TRIGGER
BEFORE INSERT ON locus_url
FOR EACH ROW
BEGIN
SELECT url_seq.nextval INTO :new.url_id FROM DUAL;
END;
/

DROP TRIGGER LOCUS_RELATION_TRIGGER;
--/
CREATE TRIGGER LOCUS_RELATION_TRIGGER
BEFORE INSERT ON locus_relation
FOR EACH ROW
BEGIN
SELECT relation_seq.nextval INTO :new.relation_id FROM DUAL;
END;
/

DROP TRIGGER LOCUS_DOC_TRIGGER;
--/
CREATE TRIGGER LOCUS_DOC_TRIGGER
BEFORE INSERT ON locus_document
FOR EACH ROW
BEGIN
SELECT document_seq.nextval INTO :new.document_id FROM DUAL;
END;
/

DROP TRIGGER LOCUS_DOC_REF_TRIGGER;
--/
CREATE TRIGGER LOCUS_DOC_REF_TRIGGER
BEFORE INSERT ON locus_document_reference
FOR EACH ROW
BEGIN
SELECT docref_seq.nextval INTO :new.document_reference_id FROM DUAL;
END;
/

DROP TRIGGER REFERENCE_ALIAS_TRIGGER;
--/
CREATE TRIGGER REFERENCE_ALIAS_TRIGGER
BEFORE INSERT ON reference_alias
FOR EACH ROW
BEGIN
SELECT alias_seq.nextval INTO :new.alias_id FROM DUAL;
END;
/

DROP TRIGGER REFERENCE_URL_TRIGGER;
--/
CREATE TRIGGER REFERENCE_URL_TRIGGER
BEFORE INSERT ON reference_url
FOR EACH ROW
BEGIN
SELECT url_seq.nextval INTO :new.url_id FROM DUAL;
END;
/

DROP TRIGGER REFERENCE_DOC_TRIGGER;
--/
CREATE TRIGGER REFERENCE_DOC_TRIGGER
BEFORE INSERT ON reference_document
FOR EACH ROW
BEGIN
SELECT document_seq.nextval INTO :new.document_id FROM DUAL;
END;
/

DROP TRIGGER REFERENCE_REFTYPE_TRIGGER;
--/
CREATE TRIGGER REFERENCE_REFTYPE_TRIGGER
BEFORE INSERT ON reference_reftype
FOR EACH ROW
BEGIN
SELECT reference_reftype_seq.nextval INTO :new.reference_reftype_id FROM DUAL;
END;
/

DROP TRIGGER REFERENCE_AUTHOR_TRIGGER;
--/
CREATE TRIGGER REFERENCE_AUTHOR_TRIGGER
BEFORE INSERT ON reference_author
FOR EACH ROW
BEGIN
SELECT reference_author_seq.nextval INTO :new.reference_author_id FROM DUAL;
END;
/

DROP TRIGGER REFERENCE_RELATION_TRIGGER;
--/
CREATE TRIGGER REFERENCE_RELATION_TRIGGER
BEFORE INSERT ON reference_relation
FOR EACH ROW
BEGIN
SELECT relation_seq.nextval INTO :new.relation_id FROM DUAL;
END;
/

DROP TRIGGER COLLEAGUE_URL_TRIGGER;
--/
CREATE TRIGGER COLLEAGUE_URL_TRIGGER
BEFORE INSERT ON colleague_url
FOR EACH ROW
BEGIN
SELECT url_seq.nextval INTO :new.url_id FROM DUAL;
END;
/

DROP TRIGGER COLLEAGUE_RELATION_TRIGGER;
--/
CREATE TRIGGER COLLEAGUE_RELATION_TRIGGER
BEFORE INSERT ON colleague_relation
FOR EACH ROW
BEGIN
SELECT relation_seq.nextval INTO :new.relation_id FROM DUAL;
END;
/

DROP TRIGGER COLLEAGUE_DOC_TRIGGER;
--/
CREATE TRIGGER COLLEAGUE_DOC_TRIGGER
BEFORE INSERT ON colleague_document
FOR EACH ROW
BEGIN
SELECT document_seq.nextval INTO :new.document_id FROM DUAL;
END;
/

DROP TRIGGER COLLEAGUE_LOCUS_TRIGGER;
--/
CREATE TRIGGER COLLEAGUE_LOCUS_TRIGGER
BEFORE INSERT ON colleague_locus
FOR EACH ROW
BEGIN
SELECT colleague_locus_seq.nextval INTO :new.colleague_locus_id FROM DUAL;
END;
/

DROP TRIGGER COLLEAGUE_KEYWORD_TRIGGER;
--/
CREATE TRIGGER COLLEAGUE_KEYWORD_TRIGGER
BEFORE INSERT ON colleague_keyword
FOR EACH ROW
BEGIN
SELECT colleague_keyword_seq.nextval INTO :new.colleague_keyword_id FROM DUAL;
END;
/

DROP TRIGGER AUTHOR_RESPONSE_TRIGGER;
--/
CREATE TRIGGER AUTHOR_RESPONSE_TRIGGER
BEFORE INSERT ON author_response
FOR EACH ROW
BEGIN
SELECT author_response_seq.nextval INTO :new.author_response_id FROM DUAL;
END;
/

DROP TRIGGER TAXONOMY_ALIAS_TRIGGER;
--/
CREATE TRIGGER TAXONOMY_ALIAS_TRIGGER
BEFORE INSERT ON taxonomy_alias
FOR EACH ROW
BEGIN
SELECT alias_seq.nextval INTO :new.alias_id FROM DUAL;
END;
/

DROP TRIGGER TAXONOMY_RELATION_TRIGGER;
--/
CREATE TRIGGER TAXONOMY_RELATION_TRIGGER
BEFORE INSERT ON taxonomy_relation
FOR EACH ROW
BEGIN
SELECT relation_seq.nextval INTO :new.relation_id FROM DUAL;
END;
/

DROP TRIGGER STRAIN_URL_TRIGGER;
--/
CREATE TRIGGER STRAIN_URL_TRIGGER
BEFORE INSERT ON strain_url
FOR EACH ROW
BEGIN
SELECT url_seq.nextval INTO :new.url_id FROM DUAL;
END;
/

DROP TRIGGER STRAIN_DOC_TRIGGER;
--/
CREATE TRIGGER STRAIN_DOC_TRIGGER
BEFORE INSERT ON strain_document
FOR EACH ROW
BEGIN
SELECT document_seq.nextval INTO :new.document_id FROM DUAL;
END;
/

DROP TRIGGER STRAIN_DOC_REF_TRIGGER;
--/
CREATE TRIGGER STRAIN_DOC_REF_TRIGGER
BEFORE INSERT ON strain_document_reference
FOR EACH ROW
BEGIN
SELECT docref_seq.nextval INTO :new.document_reference_id FROM DUAL;
END;
/

DROP TRIGGER EVIDENCE_TRIGGER;
--/
CREATE TRIGGER EVIDENCE_TRIGGER
BEFORE INSERT ON evidence
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.evidence_id FROM DUAL;
END;
/

DROP TRIGGER EVIDENCE_ALIAS_TRIGGER;
--/
CREATE TRIGGER EVIDENCE_ALIAS_TRIGGER
BEFORE INSERT ON evidence_alias
FOR EACH ROW
BEGIN
SELECT alias_seq.nextval INTO :new.alias_id FROM DUAL;
END;
/

DROP TRIGGER EVIDENCE_URL_TRIGGER;
--/
CREATE TRIGGER EVIDENCE_URL_TRIGGER
BEFORE INSERT ON evidence_url
FOR EACH ROW
BEGIN
SELECT url_seq.nextval INTO :new.url_id FROM DUAL;
END;
/


DROP TRIGGER EVIDENCE_RELATION_TRIGGER;
--/
CREATE TRIGGER EVIDENCE_RELATION_TRIGGER
BEFORE INSERT ON evidence_relation
FOR EACH ROW
BEGIN
SELECT relation_seq.nextval INTO :new.relation_id FROM DUAL;
END;
/

DROP TRIGGER SEQUENCEFEATURE_TRIGGER;
--/
CREATE TRIGGER SEQUENCEFEATURE_TRIGGER
BEFORE INSERT ON sequencefeature
FOR EACH ROW
BEGIN
SELECT object_seq.nextval INTO :new.sequencefeature_id FROM DUAL;
END;
/

DROP TRIGGER SEQUENCEFEATURE_ALIAS_TRIGGER;
--/
CREATE TRIGGER SEQUENCEFEATURE_ALIAS_TRIGGER
BEFORE INSERT ON sequencefeature_alias
FOR EACH ROW
BEGIN
SELECT alias_seq.nextval INTO :new.alias_id FROM DUAL;
END;
/

DROP TRIGGER SEQUENCEFEATURE_URL_TRIGGER;
--/
CREATE TRIGGER SEQUENCEFEATURE_URL_TRIGGER
BEFORE INSERT ON sequencefeature_url
FOR EACH ROW
BEGIN
SELECT url_seq.nextval INTO :new.url_id FROM DUAL;
END;
/

DROP TRIGGER SEQUENCEFEATURE_REL_TRIGGER;
--/
CREATE TRIGGER SEQUENCEFEATURE_REL_TRIGGER
BEFORE INSERT ON sequencefeature_relation
FOR EACH ROW
BEGIN
SELECT relation_seq.nextval INTO :new.relation_id FROM DUAL;
END;
/