@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/AuditLog.sps
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/AuditLog.spb
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/CheckUser.fnc
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/CheckDelete.sps
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/CheckDelete.spb
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/MakeSgdid.fnc
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ManageSgdid.sps
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ManageSgdid.spb
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/CheckPubmed.fnc
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/CheckPhenotype.fnc
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/CheckChebi.fnc

@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DeleteLog_BUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/UpdateLog_BUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dbuser_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dbuser_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Source_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Source_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Sgdid_BIUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Sgdid_AUR.trg

@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Ro_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Ro_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/RoUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/RoUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/RoRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/RoRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Apo_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Apo_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ApoAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ApoAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ApoUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ApoUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ApoRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ApoRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Chebi_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Chebi_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ChebiAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ChebiAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ChebiUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ChebiUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ChebiRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ChebiRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Ec_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Ec_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Eco_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Eco_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcoAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcoAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcoUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcoUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcoRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EcoRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Edam_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Edam_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EdamAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EdamAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EdamUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EdamUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EdamRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/EdamRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Go_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Go_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/GoAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/GoAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/GoUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/GoUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/GoRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/GoRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Keyword_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Keyword_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Obi_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Obi_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ObiUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ObiUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ObiRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ObiRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Psimod_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Psimod_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PsimodUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PsimodUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PsimodRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PsimodRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/So_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/So_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/SoAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/SoAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/SoUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/SoUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/SoRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/SoRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Taxonomy_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Taxonomy_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/TaxonomyAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/TaxonomyAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/TaxonomyUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/TaxonomyUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/TaxonomyRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/TaxonomyRelation_AUDR.trg

@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dbentity_BIUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dbentity_AUDR.trg
--@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dbentity_AIUDR.trg   # only for initial data load
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Locusdbentity_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Locusdbentity_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Straindbentity_BUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Straindbentity_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/StrainUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/StrainUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Pathwaydbentity_BUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Pathwaydbentity_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PathwayUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PathwayUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Book_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Book_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Journal_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Journal_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Referencedbentity_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Referencedbentity_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceAlias_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceAlias_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceReftype_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceReftype_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceCorrection_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceCorrection_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceDocument_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceDocument_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceAuthor_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceAuthor_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceUnlink_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceUnlink_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceDeleted_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ReferenceDeleted_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Filedbentity_BUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Filedbentity_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/FileRelation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/FileRelation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Colleague_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Colleague_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueAssociation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueAssociation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueKeyword_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueKeyword_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueLocus_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueLocus_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueReference_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ColleagueReference_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusSummary_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusSummary_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusSummaryReference_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/LocusSummaryReference_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/StrainSummary_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/StrainSummary_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/StrainSummaryReference_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/StrainSummaryReference_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PathwaySummary_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PathwaySummary_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PathwaySummaryReference_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PathwaySummaryReference_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Reservedname_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Reservedname_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Goslim_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Goslim_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Phenotype_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Phenotype_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Allele_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Allele_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Reporter_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Reporter_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dataset_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dataset_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetLab_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetLab_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetKeyword_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetKeyword_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetReference_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetReference_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetFile_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/DatasetFile_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Datasetsample_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Datasetsample_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Genomerelease_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Genomerelease_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Contig_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Contig_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ContigUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ContigUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Proteindomain_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Proteindomain_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ProteindomainUrl_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ProteindomainUrl_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Bindingmotifannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Bindingmotifannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dnasequenceannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dnasequenceannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dnasubsequence_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Dnasubsequence_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Enzymeannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Enzymeannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Expressionannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Expressionannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Geninteractionannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Geninteractionannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Goannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Goannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Gosupportingevidence_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Gosupportingevidence_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Goextension_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Goextension_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Goslimannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Goslimannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Literatureannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Literatureannotation_AUDR.trg

@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Noteannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Noteannotation_AUDR.trg

@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Pathwayannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Pathwayannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Phenotypeannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Phenotypeannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PhenotypeannotationCond_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/PhenotypeannotationCond_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Physinteractionannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Physinteractionannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Posttranslationannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Posttranslationannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Proteindomainannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Proteindomainannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Proteinexptannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Proteinexptannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ProteinexptannotationCond_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ProteinexptannotationCond_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Proteinsequenceannotation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Proteinsequenceannotation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ProteinsequenceDetail_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ProteinsequenceDetail_AUDR.trg

@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Curation_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Curation_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Authorresponse_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Authorresponse_AUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Referencetriage_BIUR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/Referencetriage_AUDR.trg

@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ArchLocuschange_BIUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ArchLiteratureannotation_BIUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ArchContig_BIUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ArchContigchange_BIUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ArchDnaseqannotation_BIUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ArchDnasubsequence_BIUDR.trg
@/db0/home/oracle/SGDBackend/src/sgd/model/nex/triggers/ArchProteinseqannotation_BIUDR.trg
