/* Source */
DROP TABLE SOURCE CASCADE CONSTRAINTS;
CREATE TABLE SOURCE ( 
SOURCE_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
DESCRIPTION VARCHAR2(400), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT SOURCE_PK PRIMARY KEY (SOURCE_ID), 
CONSTRAINT SOURCE_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
DROP SEQUENCE SOURCE_SEQ;
CREATE SEQUENCE SOURCE_SEQ NOCACHE;
GRANT SELECT ON SOURCE TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON SOURCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON SOURCE TO AUXILIARY;

/* Misc */
DROP TABLE ALIAS CASCADE CONSTRAINTS;
CREATE TABLE ALIAS ( 
ALIAS_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'CHEMICAL', 'REFERENCE', 'EXPERIMENT')), 
CATEGORY VARCHAR2(40), 
SOURCE_ID INTEGER NOT NULL, 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT ALIAS_PK PRIMARY KEY (ALIAS_ID), 
CONSTRAINT ALIAS_UK UNIQUE (FORMAT_NAME, CLASS, DISPLAY_NAME) ) TABLESPACE DATA1;
CREATE INDEX ALIAS_SOURCE_FK_INDEX ON ALIAS (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE ALIAS
ADD CONSTRAINT ALIAS_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE ALIAS_SEQ;
CREATE SEQUENCE ALIAS_SEQ NOCACHE;
GRANT SELECT ON ALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ALIAS TO AUXILIARY;

DROP TABLE URL CASCADE CONSTRAINTS;
CREATE TABLE URL ( 
URL_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500) NOT NULL, 
SOURCE_ID INTEGER NOT NULL, 
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'REFERENCE')), 
CATEGORY VARCHAR2(40), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT URL_PK PRIMARY KEY (URL_ID), 
CONSTRAINT URL_UK UNIQUE (FORMAT_NAME, CLASS, OBJ_URL) ) TABLESPACE DATA2;
DROP SEQUENCE URL_SEQ;
CREATE SEQUENCE URL_SEQ NOCACHE;
CREATE INDEX URL_SOURCE_FK_INDEX ON URL (SOURCE_ID) TABLESPACE DATA2;
ALTER TABLE URL
ADD CONSTRAINT URL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON URL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON URL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON URL TO AUXILIARY;

DROP TABLE RELATION CASCADE CONSTRAINTS;
CREATE TABLE RELATION ( 
RELATION_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
SOURCE_ID INTEGER NOT NULL, 
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'CHEMICAL', 'REFERENCE', 'EXPERIMENT')),
RELATION_TYPE VARCHAR2(40), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT RELATION_PK PRIMARY KEY (RELATION_ID), 
CONSTRAINT RELATION_UK UNIQUE (FORMAT_NAME, CLASS, RELATION_TYPE) ) TABLESPACE DATA1;
CREATE INDEX REL_SOURCE_FK_INDEX ON RELATION (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE RELATION
ADD CONSTRAINT REL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE RELATION_SEQ;
CREATE SEQUENCE RELATION_SEQ NOCACHE;
GRANT SELECT ON RELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON RELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON RELATION TO AUXILIARY;

/* Reference */
DROP TABLE BOOK CASCADE CONSTRAINTS;
CREATE TABLE BOOK ( 
BOOK_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL, 
TITLE VARCHAR2(200) NOT NULL, 
VOLUME_TITLE VARCHAR2(200), 
ISBN VARCHAR2(20), 
TOTAL_PAGES INTEGER, 
PUBLISHER VARCHAR2(100), 
PUBLISHER_LOCATION VARCHAR2(100), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT BOOK_PK PRIMARY KEY (BOOK_ID), 
CONSTRAINT BOOK_UK UNIQUE (TITLE, VOLUME_TITLE) ,
CONSTRAINT BOOK_FORMAT_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX BOOK_SOURCE_FK_INDEX ON BOOK (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE BOOK
ADD CONSTRAINT BOOK_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BOOK TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BOOK TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BOOK TO AUXILIARY;

DROP TABLE JOURNAL CASCADE CONSTRAINTS;
CREATE TABLE JOURNAL ( 
JOURNAL_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL, 
MED_ABBR VARCHAR2(100), 
TITLE VARCHAR2(200),
ISSN_PRINT VARCHAR2(20), 
ISSN_ONLINE VARCHAR2(20), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT JOURNAL_PK PRIMARY KEY (JOURNAL_ID), 
CONSTRAINT JOURNAL_UK UNIQUE (MED_ABBR, TITLE),
CONSTRAINT JOURNAL_FORMAT_UK UNIQUE (FORMAT_NAME)  ) TABLESPACE DATA1;
CREATE INDEX JOURNAL_SOURCE_FK_INDEX ON JOURNAL (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE JOURNAL
ADD CONSTRAINT JOURNAL_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON JOURNAL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON JOURNAL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON JOURNAL TO AUXILIARY;

DROP TABLE REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE ( 
REFERENCE_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500) NOT NULL, 
SOURCE_ID INTEGER NOT NULL, 
SGDID VARCHAR2(40) NOT NULL, 
REF_STATUS VARCHAR2(40) NOT NULL, 
FULLTEXT_STATUS VARCHAR2(40) NOT NULL, 
CITATION VARCHAR2(500) NOT NULL, 
YEAR INTEGER NOT NULL, 
PUBMED_ID INTEGER, 
PUBMED_CENTRAL_ID INTEGER, 
DATE_PUBLISHED VARCHAR2(40), 
DATE_REVISED DATE,
ISSUE VARCHAR2(40), 
PAGE VARCHAR2(40), 
VOLUME VARCHAR2(40), 
TITLE VARCHAR2(400), 
JOURNAL_ID INTEGER, 
BOOK_ID INTEGER, 
DOI VARCHAR2(100), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT REFERENCE_PK PRIMARY KEY (REFERENCE_ID), 
CONSTRAINT REFERENCE_SGDID_UK UNIQUE (SGDID), 
CONSTRAINT REFERENCE_CITATION_UK UNIQUE (CITATION),
CONSTRAINT REFERENCE_FORMAT_UK UNIQUE (FORMAT_NAME)  ) TABLESPACE DATA2;
CREATE INDEX REF_BOOK_FK_INDEX ON REFERENCE (BOOK_ID) TABLESPACE DATA2;
CREATE INDEX REF_JOURNAL_FK_INDEX ON REFERENCE (JOURNAL_ID) TABLESPACE DATA2;
CREATE INDEX REF_SOURCE_FK_INDEX ON REFERENCE (SOURCE_ID) TABLESPACE DATA2;
ALTER TABLE REFERENCE 
ADD CONSTRAINT REF_JOURNAL_FK FOREIGN KEY (JOURNAL_ID) REFERENCES JOURNAL (JOURNAL_ID) 
NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE 
ADD CONSTRAINT REF_BOOK_FK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID) 
NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE
ADD CONSTRAINT REF_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE TO AUXILIARY;

DROP TABLE REFERENCERELATION CASCADE CONSTRAINTS;
CREATE TABLE REFERENCERELATION ( 
RELATION_ID INTEGER NOT NULL, 
PARENT_ID INTEGER NOT NULL, 
CHILD_ID INTEGER NOT NULL, 
CONSTRAINT REFERENCERELATION_PK PRIMARY KEY (RELATION_ID) ) TABLESPACE DATA1;
CREATE INDEX REFREL_PARENT_FK_INDEX ON REFERENCERELATION (PARENT_ID) TABLESPACE DATA1;
CREATE INDEX REFREL_CHILD_FK_INDEX ON REFERENCERELATION (CHILD_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCERELATION 
ADD CONSTRAINT REFREL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCERELATION 
ADD CONSTRAINT REFREL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCERELATION 
ADD CONSTRAINT REFREL_REL_FK FOREIGN KEY (RELATION_ID) REFERENCES RELATION (RELATION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCERELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCERELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCERELATION TO AUXILIARY;

DROP TABLE REFERENCEALIAS CASCADE CONSTRAINTS;
CREATE TABLE REFERENCEALIAS (
ALIAS_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
CONSTRAINT REFERENCEALIAS_PK PRIMARY KEY (ALIAS_ID) ) TABLESPACE DATA1;
ALTER TABLE REFERENCEALIAS
ADD CONSTRAINT REFALIAS_ALIAS_FK FOREIGN KEY (ALIAS_ID) REFERENCES ALIAS (ALIAS_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX REFALIAS_BIOENT_FK_INDEX ON REFERENCEALIAS (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCEALIAS
ADD CONSTRAINT REFALIAS_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCEALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEALIAS TO AUXILIARY;

DROP TABLE REFERENCEURL CASCADE CONSTRAINTS;
CREATE TABLE REFERENCEURL (
URL_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
CONSTRAINT REFERENCEURL_PK PRIMARY KEY (URL_ID) ) TABLESPACE DATA1;
ALTER TABLE REFERENCEURL
ADD CONSTRAINT REFURL_URL_FK FOREIGN KEY (URL_ID) REFERENCES URL (URL_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX REFURL_REF_FK_INDEX ON REFERENCEURL (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCEURL
ADD CONSTRAINT REFURL_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCEURL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEURL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCEURL TO AUXILIARY;

DROP TABLE ABSTRACT CASCADE CONSTRAINTS;
CREATE TABLE ABSTRACT ( 
REFERENCE_ID INTEGER NOT NULL, 
TEXT CLOB NOT NULL, 
CONSTRAINT ABSTRACT_PK PRIMARY KEY (REFERENCE_ID) ) TABLESPACE DATA2;
ALTER TABLE ABSTRACT 
ADD CONSTRAINT ABSTRACT_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON ABSTRACT TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON ABSTRACT TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON ABSTRACT TO AUXILIARY;

DROP TABLE BIBENTRY CASCADE CONSTRAINTS;
CREATE TABLE BIBENTRY ( 
REFERENCE_ID INTEGER NOT NULL, 
TEXT CLOB NOT NULL, 
CONSTRAINT BIBENTRY_PK PRIMARY KEY (REFERENCE_ID) ) TABLESPACE DATA2;
ALTER TABLE BIBENTRY 
ADD CONSTRAINT BIB_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIBENTRY TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIBENTRY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIBENTRY TO AUXILIARY;

DROP TABLE REFTYPE CASCADE CONSTRAINTS;
CREATE TABLE REFTYPE ( 
REFTYPE_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL, 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT REFTYPE_PK PRIMARY KEY (REFTYPE_ID), 
CONSTRAINT REFTYPE_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX REFTYPE_SOURCE_FK_INDEX ON REFTYPE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE REFTYPE
ADD CONSTRAINT REFTYPE_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFTYPE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFTYPE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFTYPE TO AUXILIARY;

DROP TABLE REFERENCE_REFTYPE CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE_REFTYPE ( 
REFERENCE_REFTYPE_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER NOT NULL, 
REFTYPE_ID INTEGER NOT NULL, 
SOURCE_ID INTEGER NOT NULL, 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT REFERENCE_REFTYPE_PK PRIMARY KEY (REFERENCE_REFTYPE_ID), 
CONSTRAINT REFERENCE_REFTYPE_UK UNIQUE (REFERENCE_ID, REFTYPE_ID) ) TABLESPACE DATA1;
CREATE INDEX REFREFTYPE_SOURCE_FK_INDEX ON REFERENCE_REFTYPE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCE_REFTYPE
ADD CONSTRAINT REFREFTYPE_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REFERENCE_REFTYPE 
ADD CONSTRAINT REFREFTYPE_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX REFREFTYPE_REFTYPE_FK_INDEX ON REFERENCE_REFTYPE (REFTYPE_ID) TABLESPACE DATA1;
ALTER TABLE REFERENCE_REFTYPE
ADD CONSTRAINT REFREFTYPE_REFTYPE_FK FOREIGN KEY (REFTYPE_ID) REFERENCES REFTYPE (REFTYPE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCE_REFTYPE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_REFTYPE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_REFTYPE TO AUXILIARY;

DROP TABLE AUTHOR CASCADE CONSTRAINTS;
CREATE TABLE AUTHOR ( 
AUTHOR_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID), 
CONSTRAINT AUTHOR_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX AUTHOR_SOURCE_FK_INDEX ON AUTHOR (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE AUTHOR
ADD CONSTRAINT AUTHOR_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUTHOR TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR TO AUXILIARY;

DROP TABLE AUTHOR_REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE AUTHOR_REFERENCE ( 
AUTHOR_REFERENCE_ID INTEGER NOT NULL, 
AUTHOR_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER NOT NULL, 
AUTHOR_ORDER INTEGER NOT NULL, 
AUTHOR_TYPE VARCHAR2(40) NOT NULL, 
SOURCE_ID INTEGER NOT NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT AUTHOR_REFERENCE_PK PRIMARY KEY (AUTHOR_REFERENCE_ID), 
CONSTRAINT AUTHOR_REFERENCE_UK UNIQUE (REFERENCE_ID, AUTHOR_ID, AUTHOR_ORDER) ) TABLESPACE DATA1;
CREATE INDEX AUTHORREF_AUTHOR_FK_INDEX ON AUTHOR_REFERENCE (AUTHOR_ID) TABLESPACE DATA1;
ALTER TABLE AUTHOR_REFERENCE 
ADD CONSTRAINT AUTHORREF_AUTHOR_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE AUTHOR_REFERENCE 
ADD CONSTRAINT AUTHORREF_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX AUTHORREF_SOURCE_FK_INDEX ON AUTHOR_REFERENCE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE AUTHOR_REFERENCE 
ADD CONSTRAINT AUTHORREF_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON AUTHOR_REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR_REFERENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR_REFERENCE TO AUXILIARY;

/* Evidence Elements */
DROP TABLE EXPERIMENT CASCADE CONSTRAINTS;
CREATE TABLE EXPERIMENT ( 
EXPERIMENT_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(200) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL,
ECO_ID VARCHAR2(20), 
DESCRIPTION VARCHAR2(1000), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT EXPERIMENT_PK PRIMARY KEY (EXPERIMENT_ID), 
CONSTRAINT EXPERIMENT_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX EXP_SOURCE_FK_INDEX ON EXPERIMENT (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE EXPERIMENT
ADD CONSTRAINT EXP_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE EXPERIMENT_SEQ;
CREATE SEQUENCE EXPERIMENT_SEQ NOCACHE;
GRANT SELECT ON EXPERIMENT TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON EXPERIMENT TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPERIMENT TO AUXILIARY;

DROP TABLE EXPERIMENTRELATION CASCADE CONSTRAINTS;
CREATE TABLE EXPERIMENTRELATION ( 
RELATION_ID INTEGER NOT NULL, 
PARENT_ID INTEGER NOT NULL, 
CHILD_ID INTEGER NOT NULL, 
CONSTRAINT EXPERIMENTRELATION_PK PRIMARY KEY (RELATION_ID)) TABLESPACE DATA1;
CREATE INDEX EXPTREL_PARENT_FK_INDEX ON EXPERIMENTRELATION (PARENT_ID) TABLESPACE DATA1;
CREATE INDEX EXPTREL_CHILD_FK_INDEX ON EXPERIMENTRELATION (CHILD_ID) TABLESPACE DATA1;
ALTER TABLE EXPERIMENTRELATION 
ADD CONSTRAINT EXPTREL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPERIMENTRELATION 
ADD CONSTRAINT EXPTREL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EXPERIMENTRELATION 
ADD CONSTRAINT EXPTREL_REL_FK FOREIGN KEY (RELATION_ID) REFERENCES RELATION (RELATION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON EXPERIMENTRELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPERIMENTRELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPERIMENTRELATION TO AUXILIARY;

DROP TABLE EXPERIMENTALIAS CASCADE CONSTRAINTS;
CREATE TABLE EXPERIMENTALIAS (
ALIAS_ID INTEGER NOT NULL,
EXPERIMENT_ID INTEGER NOT NULL,
CONSTRAINT EXPERIMENTALIAS_PK PRIMARY KEY (ALIAS_ID) ) TABLESPACE DATA1;
ALTER TABLE EXPERIMENTALIAS
ADD CONSTRAINT EXPTALIAS_ALIAS_FK FOREIGN KEY (ALIAS_ID) REFERENCES ALIAS (ALIAS_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX EXPTALIAS_EXPT_FK_INDEX ON EXPERIMENTALIAS (EXPERIMENT_ID) TABLESPACE DATA1;
ALTER TABLE EXPERIMENTALIAS
ADD CONSTRAINT EXPTALIAS_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON EXPERIMENTALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPERIMENTALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EXPERIMENTALIAS TO AUXILIARY;

DROP TABLE STRAIN CASCADE CONSTRAINTS;
CREATE TABLE STRAIN ( 
STRAIN_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL,
DESCRIPTION VARCHAR2(400), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT STRAIN_PK PRIMARY KEY (STRAIN_ID), 
CONSTRAINT STRAIN_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX STRAIN_SOURCE_FK_INDEX ON STRAIN (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE STRAIN
ADD CONSTRAINT STRAIN_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE STRAIN_SEQ;
CREATE SEQUENCE STRAIN_SEQ NOCACHE;
GRANT SELECT ON STRAIN TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON STRAIN TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON STRAIN TO AUXILIARY;

/* Bioitem */
DROP TABLE BIOITEM CASCADE CONSTRAINTS;
CREATE TABLE BIOITEM ( 
BIOITEM_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('ALLELE', 'PROTEIN', 'PATHWAY', 'DNA', 'DOMAIN')),
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL,
DESCRIPTION VARCHAR2(200), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT BIOITEM_PK PRIMARY KEY (BIOITEM_ID) , 
CONSTRAINT BIOITEM_UK UNIQUE (FORMAT_NAME, SUBCLASS) ) TABLESPACE DATA1;
CREATE INDEX BIOITEM_SOURCE_FK_INDEX ON BIOITEM (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE BIOITEM
ADD CONSTRAINT BIOITEM_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE BIOITEM_SEQ;
CREATE SEQUENCE BIOITEM_SEQ NOCACHE;
GRANT SELECT ON BIOITEM TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOITEM TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOITEM TO AUXILIARY;

DROP TABLE DOMAINBIOITEM CASCADE CONSTRAINTS;
CREATE TABLE DOMAINBIOITEM ( 
BIOITEM_ID INTEGER NOT NULL, 
INTERPRO_ID VARCHAR2(20), 
INTERPRO_DESCRIPTION VARCHAR2(500),
EXTERNAL_URL VARCHAR2(500),
CONSTRAINT DOMAINBIOITEM_PK PRIMARY KEY (BIOITEM_ID) ) TABLESPACE DATA1;
ALTER TABLE DOMAINBIOITEM
ADD CONSTRAINT DOMAINBIOITEM_BIOITEM_FK FOREIGN KEY (BIOITEM_ID) REFERENCES BIOITEM (BIOITEM_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DOMAINBIOITEM TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAINBIOITEM TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAINBIOITEM TO AUXILIARY;

/* Bioentity */
DROP TABLE BIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY ( 
BIOENTITY_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500) NOT NULL, 
SOURCE_ID INTEGER NOT NULL, 
SGDID VARCHAR2(40), 
UNIPROTID VARCHAR2(40), 
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('LOCUS', 'PROTEIN', 'COMPLEX')),
BIOENT_STATUS VARCHAR2(40),
DESCRIPTION VARCHAR2(2000),
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT BIOENTITY_PK PRIMARY KEY (BIOENTITY_ID), 
CONSTRAINT BIOENTITY_UK UNIQUE (FORMAT_NAME, SUBCLASS) ) TABLESPACE DATA1;
CREATE INDEX BIOENT_SOURCE_FK ON BIOENTITY (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITY
ADD CONSTRAINT BIOENT_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITY TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON BIOENTITY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY TO AUXILIARY;
DROP SEQUENCE BIOENTITY_SEQ;
CREATE SEQUENCE BIOENTITY_SEQ START WITH 500000 NOCACHE;

DROP TABLE BIOENTITYALIAS CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYALIAS (
ALIAS_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('LOCUS', 'PROTEIN', 'COMPLEX')),
CONSTRAINT BIOENTITYALIAS_PK PRIMARY KEY (ALIAS_ID) ) TABLESPACE DATA1;
ALTER TABLE BIOENTITYALIAS
ADD CONSTRAINT BIOENTALIAS_ALIAS_FK FOREIGN KEY (ALIAS_ID) REFERENCES ALIAS (ALIAS_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOENTALIAS_BIOENT_FK_INDEX ON BIOENTITYALIAS (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITYALIAS
ADD CONSTRAINT BIOENTALIAS_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYALIAS TO AUXILIARY;

DROP TABLE BIOENTITYURL CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYURL (
URL_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('LOCUS', 'PROTEIN', 'COMPLEX')),
CONSTRAINT BIOENTITYURL_PK PRIMARY KEY (URL_ID) ) TABLESPACE DATA1;
ALTER TABLE BIOENTITYURL
ADD CONSTRAINT BIOENTURL_URL_FK FOREIGN KEY (URL_ID) REFERENCES URL (URL_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOENTURL_BIOENT_FK_INDEX ON BIOENTITYURL (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITYURL
ADD CONSTRAINT BIOENTURL_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYURL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYURL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYURL TO AUXILIARY;

DROP TABLE BIOENTITYRELATION CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYRELATION ( 
RELATION_ID INTEGER NOT NULL, 
PARENT_ID INTEGER NOT NULL, 
CHILD_ID INTEGER NOT NULL, 
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('LOCUS', 'PROTEIN', 'COMPLEX')),
CONSTRAINT BIOENTITYRELATION_PK PRIMARY KEY (RELATION_ID) ) TABLESPACE DATA1;
CREATE INDEX BIOENTREL_PARENT_FK_INDEX ON BIOENTITYRELATION (PARENT_ID) TABLESPACE DATA1;
CREATE INDEX BIOENTREL_CHILD_FK_INDEX ON BIOENTITYRELATION (CHILD_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITYRELATION 
ADD CONSTRAINT BIOENTREL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES BIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYRELATION 
ADD CONSTRAINT BIOENTREL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES BIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOENTITYRELATION 
ADD CONSTRAINT BIOENTREL_REL_FK FOREIGN KEY (RELATION_ID) REFERENCES RELATION (RELATION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYRELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYRELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYRELATION TO AUXILIARY;

DROP TABLE LOCUSBIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE LOCUSBIOENTITY ( 
BIOENTITY_ID INTEGER NOT NULL, 
LOCUS_TYPE VARCHAR2(40) NOT NULL, 
NAME_DESCRIPTION VARCHAR2(100), 
GENETIC_POSITION NUMBER, 
HEADLINE VARCHAR2(70), 
CONSTRAINT LOCUSBIOENTITY_PK PRIMARY KEY (BIOENTITY_ID) ) TABLESPACE DATA1;
ALTER TABLE LOCUSBIOENTITY 
ADD CONSTRAINT LOCUS_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID);
GRANT SELECT ON LOCUSBIOENTITY TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUSBIOENTITY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LOCUSBIOENTITY TO AUXILIARY;

DROP TABLE PROTEINBIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE PROTEINBIOENTITY ( 
BIOENTITY_ID INTEGER NOT NULL, 
LOCUS_ID INTEGER NOT NULL, 
MOLECULAR_WEIGHT INTEGER, 
PROTEIN_LENGTH INTEGER, 
N_TERM_SEQ VARCHAR2(40), 
C_TERM_SEQ VARCHAR2(40), 
CONSTRAINT PROTEINBIOENTITY_PK PRIMARY KEY (BIOENTITY_ID) ) TABLESPACE DATA1;
CREATE INDEX PROTBIOENT_LOCUS_FK_INDEX ON PROTEINBIOENTITY (LOCUS_ID) TABLESPACE DATA1;
ALTER TABLE PROTEINBIOENTITY 
ADD CONSTRAINT PROTBIOENT_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID);
ALTER TABLE PROTEINBIOENTITY 
ADD CONSTRAINT PROTBIOENT_LOCUS_FK FOREIGN KEY (LOCUS_ID) REFERENCES BIOENTITY (BIOENTITY_ID);
GRANT SELECT ON PROTEINBIOENTITY TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINBIOENTITY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINBIOENTITY TO AUXILIARY;

DROP TABLE COMPLEXBIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE COMPLEXBIOENTITY (
BIOENTITY_ID INTEGER NOT NULL,
GO_ID INTEGER,
CELLULAR_LOCALIZATION VARCHAR2(100),
CONSTRAINT COMPLEXBIOENTITY_PK PRIMARY KEY (BIOENTITY_ID) ) TABLESPACE DATA1;
CREATE INDEX COMPLEXBIOENTITY_GO_INDEX ON COMPLEXBIOENTITY (GO_ID) TABLESPACE DATA1;
ALTER TABLE COMPLEXBIOENTITY
ADD CONSTRAINT COMPLEXBIOENT_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE COMPLEXBIOCONCEPT
ADD CONSTRAINT COMPLEXBIOENT_GO_FK FOREIGN KEY (GO_ID) REFERENCES GOBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON COMPLEXBIOENTITY TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON COMPLEXBIOENTITY TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON COMPLEXBIOENTITY TO AUXILIARY;

/* Bioconcept */
DROP TABLE BIOCONCEPT CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPT ( 
BIOCONCEPT_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL,
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('GO', 'PHENOTYPE', 'EC_NUMBER')),
SGDID VARCHAR2(40), 
DESCRIPTION VARCHAR2(2000), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT BIOCONCEPT_PK PRIMARY KEY (BIOCONCEPT_ID), 
CONSTRAINT BIOCONCEPT_UK UNIQUE (FORMAT_NAME, SUBCLASS) ) TABLESPACE DATA1;
CREATE INDEX BIOCON_SOURCE_FK_INDEX ON BIOCONCEPT (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE BIOCONCEPT
ADD CONSTRAINT BIOCON_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE BIOCONCEPT_SEQ;
CREATE SEQUENCE BIOCONCEPT_SEQ NOCACHE;
GRANT SELECT ON BIOCONCEPT TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON BIOCONCEPT TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPT TO AUXILIARY;

DROP TABLE BIOCONCEPTALIAS CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPTALIAS (
ALIAS_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('GO', 'PHENOTYPE', 'EC_NUMBER')),
CONSTRAINT BIOCONCEPTALIAS_PK PRIMARY KEY (ALIAS_ID) ) TABLESPACE DATA1;
ALTER TABLE BIOCONCEPTALIAS
ADD CONSTRAINT BIOCONALIAS_ALIAS_FK FOREIGN KEY (ALIAS_ID) REFERENCES ALIAS (ALIAS_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOCONALIAS_BIOCON_FK_INDEX ON BIOCONCEPTALIAS (BIOCONCEPT_ID) TABLESPACE DATA1;
ALTER TABLE BIOCONCEPTALIAS
ADD CONSTRAINT BIOCONALIAS_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOCONCEPTALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTALIAS TO AUXILIARY;

DROP TABLE BIOCONCEPTURL CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPTURL (
URL_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('GO', 'PHENOTYPE', 'EC_NUMBER')),
CONSTRAINT BIOCONCEPTURL_PK PRIMARY KEY (URL_ID) ) TABLESPACE DATA1;
ALTER TABLE BIOCONCEPTURL
ADD CONSTRAINT BIOCONALIAS_URL_FK FOREIGN KEY (URL_ID) REFERENCES URL (URL_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOCONURL_BIOCON_FK_INDEX ON BIOCONCEPTURL (BIOCONCEPT_ID) TABLESPACE DATA1;
ALTER TABLE BIOCONCEPTURL
ADD CONSTRAINT BIOCONURL_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOCONCEPTURL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTURL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTURL TO AUXILIARY;

DROP TABLE BIOCONCEPTRELATION CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPTRELATION ( 
RELATION_ID INTEGER NOT NULL, 
PARENT_ID INTEGER NOT NULL, 
CHILD_ID INTEGER NOT NULL, 
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('GO', 'PHENOTYPE', 'EC_NUMBER', 'GO_SLIM')),
CONSTRAINT BIOCONCEPT_RELATION_PK PRIMARY KEY (RELATION_ID) ) TABLESPACE DATA1;
CREATE INDEX BIOCONREL_CHILD_INDEX ON BIOCONCEPTRELATION (CHILD_ID) TABLESPACE DATA1;
CREATE INDEX BIOCONREL_PARENT_INDEX ON BIOCONCEPTRELATION (PARENT_ID) TABLESPACE DATA1;
ALTER TABLE BIOCONCEPTRELATION 
ADD CONSTRAINT BIOCONREL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOCONCEPTRELATION 
ADD CONSTRAINT BIOCONREL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BIOCONCEPTRELATION 
ADD CONSTRAINT BIOCONREL_REL_FK FOREIGN KEY (RELATION_ID) REFERENCES RELATION (RELATION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE BIOCONREL_SEQ;
CREATE SEQUENCE BIOCONREL_SEQ NOCACHE;
GRANT SELECT ON BIOCONCEPTRELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTRELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTRELATION TO AUXILIARY;

DROP TABLE GOBIOCONCEPT CASCADE CONSTRAINTS;
CREATE TABLE GOBIOCONCEPT ( 
BIOCONCEPT_ID INTEGER NOT NULL, 
GO_ID VARCHAR2(12) NOT NULL,
GO_ASPECT VARCHAR2(40) NOT NULL, 
CONSTRAINT GOBIOCONCEPT_PK PRIMARY KEY (BIOCONCEPT_ID) ) TABLESPACE DATA1;
CREATE INDEX GOBIOCONCEPT_GO_INDEX ON GOBIOCONCEPT (GO_ID, GO_ASPECT) TABLESPACE DATA1;
ALTER TABLE GOBIOCONCEPT 
ADD CONSTRAINT GOBIOCON_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GOBIOCONCEPT TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOBIOCONCEPT TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOBIOCONCEPT TO AUXILIARY;

DROP TABLE PHENOTYPEBIOCONCEPT CASCADE CONSTRAINTS;
CREATE TABLE PHENOTYPEBIOCONCEPT ( 
BIOCONCEPT_ID INTEGER NOT NULL, 
PHENOTYPE_TYPE VARCHAR2(40) NOT NULL,
OBSERVABLE VARCHAR2(100) NOT NULL,
QUALIFIER VARCHAR2(100),
IS_CORE NUMBER(1) NOT NULL,
ANCESTOR_TYPE VARCHAR(40) NOT NULL,
CONSTRAINT PHENOTYPEBIOCONCEPT_PK PRIMARY KEY (BIOCONCEPT_ID)) TABLESPACE DATA1;
ALTER TABLE PHENOTYPEBIOCONCEPT 
ADD CONSTRAINT PHENOBIOCON_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHENOTYPEBIOCONCEPT TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPEBIOCONCEPT TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPEBIOCONCEPT TO AUXILIARY;

/* Chemical */
DROP TABLE CHEMICAL CASCADE CONSTRAINTS;
CREATE TABLE CHEMICAL ( CHEMICAL_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
SOURCE_ID INTEGER NOT NULL, 
OBJ_URL VARCHAR2(500), 
CHEBI_ID VARCHAR2(50), 
DESCRIPTION VARCHAR2(2000), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT CHEMICAL_PK PRIMARY KEY (CHEMICAL_ID), 
CONSTRAINT CHEMICAL_UK UNIQUE (FORMAT_NAME) ) TABLESPACE DATA1;
CREATE INDEX CHEM_SOURCE_FK_INDEX ON CHEMICAL (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE CHEMICAL
ADD CONSTRAINT CHEM_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE CHEM_SEQ;
CREATE SEQUENCE CHEM_SEQ NOCACHE;
GRANT SELECT ON CHEMICAL TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON CHEMICAL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICAL TO AUXILIARY;

DROP TABLE CHEMICALALIAS CASCADE CONSTRAINTS;
CREATE TABLE CHEMICALALIAS (
ALIAS_ID INTEGER NOT NULL,
CHEMICAL_ID INTEGER NOT NULL,
CONSTRAINT CHEMICALALIAS_PK PRIMARY KEY (ALIAS_ID) ) TABLESPACE DATA1;
ALTER TABLE CHEMICALALIAS
ADD CONSTRAINT CHEMICAL_ALIAS_FK FOREIGN KEY (ALIAS_ID) REFERENCES ALIAS (ALIAS_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX CHEMALIAS_CHEM_FK_INDEX ON CHEMICALALIAS (CHEMICAL_ID) TABLESPACE DATA1;
ALTER TABLE CHEMICALALIAS
ADD CONSTRAINT CHEMALIAS_CHEM_FK FOREIGN KEY (CHEMICAL_ID) REFERENCES CHEMICAL (CHEMICAL_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CHEMICALALIAS TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALALIAS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALALIAS TO AUXILIARY;

DROP TABLE CHEMICALRELATION CASCADE CONSTRAINTS;
CREATE TABLE CHEMICALRELATION ( 
RELATION_ID INTEGER NOT NULL, 
PARENT_ID INTEGER NOT NULL,
CHILD_ID INTEGER NOT NULL, 
CONSTRAINT CHEMICALRELATION_PK PRIMARY KEY (RELATION_ID) ) TABLESPACE DATA1;
CREATE INDEX CHEMREL_PARENT_FK_INDEX ON CHEMICALRELATION (PARENT_ID) TABLESPACE DATA1;
CREATE INDEX CHEMREL_CHILD_FK_INDEX ON CHEMICALRELATION (CHILD_ID) TABLESPACE DATA1;
ALTER TABLE CHEMICALRELATION 
ADD CONSTRAINT CHEMREL_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES CHEMICAL (CHEMICAL_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE CHEMICALRELATION 
ADD CONSTRAINT CHEMREL_CHILD_FK FOREIGN KEY (CHILD_ID) REFERENCES CHEMICAL (CHEMICAL_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE CHEMICALRELATION 
ADD CONSTRAINT CHEMREL_REL_FK FOREIGN KEY (RELATION_ID) REFERENCES RELATION (RELATION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CHEMICALRELATION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALRELATION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALRELATION TO AUXILIARY;

/* Sequence */
DROP TABLE BIOSEQUENCE CASCADE CONSTRAINTS;
CREATE TABLE BIOSEQUENCE ( BIOSEQUENCE_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('DNA', 'RNA', 'PROTEIN', 'CONTIG')),
RESIDUES CLOB NOT NULL,
LENGTH INTEGER NOT NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT BIOSEQUENCE_PK PRIMARY KEY (BIOSEQUENCE_ID),
CONSTRAINT BIOSEQUENCE_UK UNIQUE (FORMAT_NAME, SUBCLASS) ) TABLESPACE DATA1;
DROP SEQUENCE BIOSEQ_SEQ;
CREATE SEQUENCE BIOSEQ_SEQ NOCACHE;
GRANT SELECT ON BIOSEQUENCE TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON BIOSEQUENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOSEQUENCE TO AUXILIARY;

DROP TABLE PROTEINBIOSEQUENCE CASCADE CONSTRAINTS;
CREATE TABLE PROTEINBIOSEQUENCE ( BIOSEQUENCE_ID INTEGER NOT NULL,
DNASEQUENCE_ID INTEGER NOT NULL,
CONSTRAINT PROTEINBIOSEQUENCE_PK PRIMARY KEY (BIOSEQUENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX PROTSEQ_DNA_FK_INDEX ON PROTEINBIOSEQUENCE (DNASEQUENCE_ID) TABLESPACE DATA1;
ALTER TABLE PROTEINBIOSEQUENCE
ADD CONSTRAINT PROTSEQ_SEQ_FK FOREIGN KEY (BIOSEQUENCE_ID) REFERENCES BIOSEQUENCE (BIOSEQUENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINBIOSEQUENCE
ADD CONSTRAINT PROTSEQ_DNA_FK FOREIGN KEY (DNASEQUENCE_ID) REFERENCES BIOSEQUENCE (BIOSEQUENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PROTEINBIOSEQUENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINBIOSEQUENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINBIOSEQUENCE TO AUXILIARY;

/* Evidence */
DROP TABLE EVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE EVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(500) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER,
EXPERIMENT_ID INTEGER,
STRAIN_ID INTEGER, 
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('PHENOTYPE', 'GO', 'EC_NUMBER', 'GENINTERACTION', 'PHYSINTERACTION', 'BINDING', 'DOMAIN', 'QUALIFIER', 'LITERATURE', 'REGULATION', 'COMPLEX')),
NOTE VARCHAR2(1000), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT EVIDENCE_PK PRIMARY KEY (EVIDENCE_ID),
CONSTRAINT EVIDENCE_UK UNIQUE (FORMAT_NAME, SUBCLASS) ) TABLESPACE DATA2;
CREATE INDEX EV_REF_FK_INDEX ON EVIDENCE (REFERENCE_ID) TABLESPACE DATA2;
CREATE INDEX EV_STRAIN_FK_INDEX ON EVIDENCE (STRAIN_ID) TABLESPACE DATA2;
CREATE INDEX EV_EXPT_FK_INDEX ON EVIDENCE (EXPERIMENT_ID) TABLESPACE DATA2;
ALTER TABLE EVIDENCE 
ADD CONSTRAINT EV_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EVIDENCE 
ADD CONSTRAINT EV_STRAIN_FK FOREIGN KEY (STRAIN_ID) REFERENCES STRAIN (STRAIN_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE EVIDENCE 
ADD CONSTRAINT EV_EXPT_FK FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX EV_SOURCE_FK_INDEX ON EVIDENCE (SOURCE_ID) TABLESPACE DATA2;
ALTER TABLE EVIDENCE
ADD CONSTRAINT EV_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE EVIDENCE_SEQ;
CREATE SEQUENCE EVIDENCE_SEQ NOCACHE;
GRANT SELECT ON EVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE TO AUXILIARY;

DROP TABLE QUALIFIEREVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE QUALIFIEREVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL, 
QUALIFIER VARCHAR2(40) NOT NULL, 
CONSTRAINT QUALIFIEREVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX QUALEV_QUALIFIER_INDEX ON QUALIFIEREVIDENCE (QUALIFIER) TABLESPACE	DATA1;
CREATE INDEX QUALEV_BIOENT_FK_INDEX ON QUALIFIEREVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE QUALIFIEREVIDENCE 
ADD CONSTRAINT QUALEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE QUALIFIEREVIDENCE 
ADD CONSTRAINT QUALEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON QUALIFIEREVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON QUALIFIEREVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON QUALIFIEREVIDENCE TO AUXILIARY;

DROP TABLE DOMAINEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE DOMAINEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
PROTEIN_ID INTEGER NOT NULL, 
DOMAIN_ID INTEGER NOT NULL, 
START_INDEX INTEGER, 
END_INDEX INTEGER, 
EVALUE VARCHAR2(40), 
DOMAIN_STATUS VARCHAR2(40), 
DATE_OF_RUN VARCHAR2(40), 
CONSTRAINT DOMAINEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX DOMAINEV_BIOENT_FK_INDEX ON DOMAINEVIDENCE (PROTEIN_ID) TABLESPACE DATA1;
CREATE INDEX DOMAINEV_DOMAIN_FK_INDEX ON DOMAINEVIDENCE (DOMAIN_ID) TABLESPACE DATA1;
ALTER TABLE DOMAINEVIDENCE 
ADD CONSTRAINT DOMAINEV_BIOENT_FK FOREIGN KEY (PROTEIN_ID) REFERENCES PROTEINBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINEVIDENCE  
ADD CONSTRAINT DOMAINEV_DOMAIN_FK FOREIGN KEY (DOMAIN_ID) REFERENCES DOMAINBIOITEM (BIOITEM_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE DOMAINEVIDENCE 
ADD CONSTRAINT DOMAINEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON DOMAINEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAINEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON DOMAINEVIDENCE TO AUXILIARY;

DROP TABLE LITERATUREEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE LITERATUREEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL, 
TOPIC VARCHAR2(40) NOT NULL, 
CONSTRAINT LITERATUREEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX LITEV_BIOENT_FK_INDEX ON LITERATUREEVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE LITERATUREEVIDENCE 
ADD CONSTRAINT LITEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE LITERATUREEVIDENCE 
ADD CONSTRAINT LITEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON LITERATUREEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON LITERATUREEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON LITERATUREEVIDENCE TO AUXILIARY;

DROP TABLE REGULATIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE REGULATIONEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
BIOENTITY1_ID INTEGER NOT NULL, 
BIOENTITY2_ID INTEGER NOT NULL, 
CONSTRAINT REGULATIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX REGEV_BIOENT2_FK_INDEX ON REGULATIONEVIDENCE (BIOENTITY2_ID) TABLESPACE DATA1;
CREATE INDEX REGEV_BIOENT1_FK_INDEX ON REGULATIONEVIDENCE (BIOENTITY1_ID) TABLESPACE DATA1;
ALTER TABLE REGULATIONEVIDENCE 
ADD CONSTRAINT REGEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONEVIDENCE 
ADD CONSTRAINT REGEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE REGULATIONEVIDENCE 
ADD CONSTRAINT REGEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REGULATIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REGULATIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON REGULATIONEVIDENCE TO AUXILIARY;

DROP TABLE BINDINGEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE BINDINGEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL, 
TOTAL_SCORE VARCHAR2(10) NOT NULL, 
EXPERT_CONFIDENCE VARCHAR2(40) NOT NULL, 
OBJ_URL VARCHAR2(500) NOT NULL, 
MOTIF_ID INTEGER NOT NULL, 
CONSTRAINT BINDINGEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX BINDEV_BIOENT_FK_INDEX ON BINDINGEVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE BINDINGEVIDENCE 
ADD CONSTRAINT BINDEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE BINDINGEVIDENCE 
ADD CONSTRAINT BINDEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BINDINGEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BINDINGEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BINDINGEVIDENCE TO AUXILIARY;

DROP TABLE GOEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE GOEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
GO_EVIDENCE VARCHAR2(40) NOT NULL, 
ANNOTATION_TYPE VARCHAR2(40) NOT NULL, 
QUALIFIER VARCHAR2(40), 
CONSTRAINT GOEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX GOEV_BIOENT_FK_INDEX ON GOEVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
CREATE INDEX GOEV_BIOCON_FK_INDEX ON GOEVIDENCE	(BIOCONCEPT_ID) TABLESPACE DATA1;
ALTER TABLE GOEVIDENCE 
ADD CONSTRAINT GOEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOEVIDENCE 
ADD CONSTRAINT GOEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GOEVIDENCE 
ADD CONSTRAINT GOEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES GOBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GOEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GOEVIDENCE TO AUXILIARY;

DROP TABLE PHENOTYPEEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PHENOTYPEEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
MUTANT_TYPE VARCHAR2(100),
STRAIN_DETAILS VARCHAR2(2000),
EXPERIMENT_DETAILS VARCHAR2(2000),
CONSTRAINT PHENOTYPEEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX PHENOEV_BIOENT_FK_INDEX ON PHENOTYPEEVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
CREATE INDEX PHENOEV_BIOCON_FK_INDEX ON PHENOTYPEEVIDENCE (BIOCONCEPT_ID) TABLESPACE DATA1;
ALTER TABLE PHENOTYPEEVIDENCE 
ADD CONSTRAINT PHENOEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEEVIDENCE 
ADD CONSTRAINT PHENOEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHENOTYPEEVIDENCE 
ADD CONSTRAINT PHENOEV_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES PHENOTYPEBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHENOTYPEEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPEEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHENOTYPEEVIDENCE TO AUXILIARY;

DROP TABLE GENINTERACTIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE GENINTERACTIONEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
PHENOTYPE_ID INTEGER,
MUTANT_TYPE VARCHAR2(100),
ANNOTATION_TYPE VARCHAR2(40) NOT NULL, 
BAIT_HIT VARCHAR2(20) NOT NULL, 
BIOENTITY1_ID INTEGER NOT NULL, 
BIOENTITY2_ID INTEGER NOT NULL, 
CONSTRAINT GENINTERACTIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX GENINTEV_BIOENT2_INDEX ON GENINTERACTIONEVIDENCE (BIOENTITY2_ID) TABLESPACE DATA1;
CREATE INDEX GENINTEV_BIOENT1_INDEX ON GENINTERACTIONEVIDENCE (BIOENTITY1_ID) TABLESPACE DATA1;
CREATE INDEX GENINTEV_PHENO_FK_INDEX ON GENINTERACTIONEVIDENCE (PHENOTYPE_ID) TABLESPACE DATA1;
ALTER TABLE GENINTERACTIONEVIDENCE 
ADD CONSTRAINT GENINTEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE 
ADD CONSTRAINT GENINTEV_PHENO_FK FOREIGN KEY (PHENOTYPE_ID) REFERENCES PHENOTYPEBIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE
ADD CONSTRAINT GENINTEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE GENINTERACTIONEVIDENCE
ADD CONSTRAINT GENINTEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON GENINTERACTIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON GENINTERACTIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON GENINTERACTIONEVIDENCE TO AUXILIARY;

DROP TABLE PHYSINTERACTIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PHYSINTERACTIONEVIDENCE ( 
EVIDENCE_ID INTEGER NOT NULL, 
MODIFICATION VARCHAR2(40) NOT NULL, 
ANNOTATION_TYPE VARCHAR2(40) NOT NULL, 
BAIT_HIT VARCHAR2(20) NOT NULL, 
BIOENTITY1_ID INTEGER NOT NULL, 
BIOENTITY2_ID INTEGER NOT NULL, 
CONSTRAINT PHYSINTERACTIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX PHYSINTEV_BIOENT2_INDEX ON PHYSINTERACTIONEVIDENCE (BIOENTITY2_ID) TABLESPACE DATA1;
CREATE INDEX PHYSINTEV_BIOENT1_INDEX ON PHYSINTERACTIONEVIDENCE (BIOENTITY1_ID) TABLESPACE DATA1;
ALTER TABLE PHYSINTERACTIONEVIDENCE 
ADD CONSTRAINT PHYSINTEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONEVIDENCE
ADD CONSTRAINT PHYSINTEV_BIOENT1_FK FOREIGN KEY (BIOENTITY1_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHYSINTERACTIONEVIDENCE
ADD CONSTRAINT PHYSINTEV_BIOENT2_FK FOREIGN KEY (BIOENTITY2_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHYSINTERACTIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHYSINTERACTIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHYSINTERACTIONEVIDENCE TO AUXILIARY;

DROP TABLE COMPLEXEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE COMPLEXEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
COMPLEX_ID INTEGER NOT NULL,
GO_ID INTEGER,
CONSTRAINT COMPLEXEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX COMPEV_BIOENT_INDEX ON COMPLEXEVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
CREATE INDEX COMPEV_COMP_INDEX ON COMPLEXEVIDENCE (COMPLEX_ID) TABLESPACE DATA1;
CREATE INDEX COMPEV_GO_INDEX ON COMPLEXEVIDENCE (GO_ID) TABLESPACE DATA1;
ALTER TABLE COMPLEXEVIDENCE
ADD CONSTRAINT COMPEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE COMPLEXEVIDENCE
ADD CONSTRAINT COMPEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE COMPLEXEVIDENCE
ADD CONSTRAINT COMPEV_COMP_FK FOREIGN KEY (COMPLEX_ID) REFERENCES COMPLEXBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE COMPLEXEVIDENCE
ADD CONSTRAINT COMPEV_GO_FK FOREIGN KEY (GO_ID) REFERENCES GOBIOCONCEPT (BIOCONCEPT_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON COMPLEXEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON COMPLEXEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON COMPLEXEVIDENCE TO AUXILIARY;

DROP TABLE SEQUENCEEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE SEQUENCEEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOSEQUENCE_ID INTEGER NOT NULL,
CONTIG_ID INTEGER NOT NULL,
START_INDEX INTEGER NOT NULL,
END_INDEX INTEGER NOT NULL,
STRAND VARCHAR2(1),
CONSTRAINT SEQUENCEEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX SEQEV_BIOENT_FK_INDEX ON SEQUENCEEVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
CREATE INDEX SEQEV_SEQ_FK_INDEX ON SEQUENCEEVIDENCE	(BIOSEQUENCE_ID) TABLESPACE DATA1;
CREATE INDEX SEQEV_CONTIG_FK_INDEX ON SEQUENCEEVIDENCE	(CONTIG_ID) TABLESPACE DATA1;
ALTER TABLE SEQUENCEEVIDENCE
ADD CONSTRAINT SEQEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE SEQUENCEEVIDENCE
ADD CONSTRAINT SEQEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES LOCUSBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE SEQUENCEEVIDENCE
ADD CONSTRAINT SEQEV_SEQ_FK FOREIGN KEY (BIOSEQUENCE_ID) REFERENCES BIOSEQUENCE (BIOSEQUENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE SEQUENCEEVIDENCE
ADD CONSTRAINT SEQEV_CONTIG_FK FOREIGN KEY (CONTIG_ID) REFERENCES BIOSEQUENCE (BIOSEQUENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON SEQUENCEEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON SEQUENCEEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON SEQUENCEEVIDENCE TO AUXILIARY;

DROP TABLE PROTEINSEQUENCEEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PROTEINSEQUENCEEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
BIOSEQUENCE_ID INTEGER NOT NULL,
DNASEQUENCE_ID INTEGER NOT NULL,
CONSTRAINT PROTEINSEQUENCEEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX PROTSEQEV_BIOENT_FK_INDEX ON PROTEINSEQUENCEEVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
CREATE INDEX PROTSEQEV_SEQ_FK_INDEX ON PROTEINSEQUENCEEVIDENCE	(BIOSEQUENCE_ID) TABLESPACE DATA1;
CREATE INDEX PROTSEQEV_DNA_FK_INDEX ON PROTEINSEQUENCEEVIDENCE	(DNASEQUENCE_ID) TABLESPACE DATA1;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES PROTEINBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_SEQ_FK FOREIGN KEY (BIOSEQUENCE_ID) REFERENCES BIOSEQUENCE (BIOSEQUENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PROTEINSEQUENCEEVIDENCE
ADD CONSTRAINT PROTSEQEV_CONTIG_FK FOREIGN KEY (DNASEQUENCE_ID) REFERENCES BIOSEQUENCE (BIOSEQUENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PROTEINSEQUENCEEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINSEQUENCEEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PROTEINSEQUENCEEVIDENCE TO AUXILIARY;

DROP TABLE SEQUENCELABEL CASCADE CONSTRAINTS;
CREATE TABLE SEQUENCELABEL (
SEQUENCELABEL_ID INTEGER NOT NULL,
EVIDENCE_ID INTEGER NOT NULL,
FORMAT_NAME VARCHAR2(100) NOT NULL,
DISPLAY_NAME VARCHAR2(500) NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL,
RELATIVE_START_INDEX INTEGER NOT NULL,
RELATIVE_END_INDEX INTEGER NOT NULL,
CHROMOSOMAL_START_INDEX INTEGER NOT NULL,
CHROMOSOMAL_END_INDEX INTEGER NOT NULL,
PHASE VARCHAR2(1) NOT NULL,
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL,
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL,
CONSTRAINT SEQUENCELABEL_PK PRIMARY KEY (SEQUENCELABEL_ID),
CONSTRAINT SEQUENCELABEL_UK UNIQUE (EVIDENCE_ID, SUBCLASS, RELATIVE_START_INDEX, RELATIVE_END_INDEX)) TABLESPACE DATA1;
CREATE INDEX SEQLAB_EV_FK_INDEX ON SEQUENCELABEL (EVIDENCE_ID) TABLESPACE DATA1;
ALTER TABLE SEQUENCELABEL
ADD CONSTRAINT SEQLAB_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES SEQUENCEEVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE SEQLABEL_SEQ;
CREATE SEQUENCE SEQLABEL_SEQ NOCACHE;
GRANT SELECT ON SEQUENCELABEL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON SEQUENCELABEL TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON SEQUENCELABEL TO AUXILIARY;

DROP TABLE PHOSPHORYLATIONEVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE PHOSPHORYLATIONEVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
SITE_INDEX INTEGER NOT NULL,
SITE_RESIDUE VARCHAR2(1) NOT NULL,
CONSTRAINT PHOSPHORYLATIONEVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX PHOSEV_BIOENT_FK_INDEX ON PHOSPHORYLATIONEVIDENCE (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE PHOSPHORYLATIONEVIDENCE
ADD CONSTRAINT PHOSEV_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PHOSPHORYLATIONEVIDENCE
ADD CONSTRAINT PHOSEV_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES PROTEINBIOENTITY (BIOENTITY_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON PHOSPHORYLATIONEVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHOSPHORYLATIONEVIDENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PHOSPHORYLATIONEVIDENCE TO AUXILIARY;

/* Condition */
DROP TABLE CONDITION CASCADE CONSTRAINTS;
CREATE TABLE CONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('CONDITION', 'CHEMICAL', 'TEMPERATURE', 'BIOENTITY', 'BIOCONCEPT', 'BIOITEM')), 
EVIDENCE_ID INTEGER NOT NULL, 
ROLE VARCHAR2(40),
NOTE VARCHAR(1000), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT CONDITION_PK PRIMARY KEY (CONDITION_ID), 
CONSTRAINT CONDITION_UK UNIQUE (EVIDENCE_ID, FORMAT_NAME, SUBCLASS, ROLE) ) TABLESPACE DATA1;
ALTER TABLE CONDITION 
ADD CONSTRAINT COND_EV_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE COND_SEQ;
CREATE SEQUENCE COND_SEQ NOCACHE;
GRANT SELECT ON CONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CONDITION TO AUXILIARY;

DROP TABLE CHEMICALCONDITION CASCADE CONSTRAINTS;
CREATE TABLE CHEMICALCONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
CHEMICAL_ID INTEGER NOT NULL, 
AMOUNT VARCHAR2(200), 
CONSTRAINT CHEMICALCONDITION_PK PRIMARY KEY (CONDITION_ID)) TABLESPACE DATA1;
CREATE INDEX CHEMCOND_CHEM_FK_INDEX ON CHEMICALCONDITION (CHEMICAL_ID) TABLESPACE DATA1;
ALTER TABLE CHEMICALCONDITION 
ADD CONSTRAINT CHEMCOND_CHEM_FK FOREIGN KEY (CHEMICAL_ID) REFERENCES CHEMICAL (CHEMICAL_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE CHEMICALCONDITION 
ADD CONSTRAINT CHEMCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CHEMICALCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICALCONDITION TO AUXILIARY;

DROP TABLE TEMPERATURECONDITION CASCADE CONSTRAINTS;
CREATE TABLE TEMPERATURECONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
TEMPERATURE FLOAT NOT NULL, 
CONSTRAINT TEMPERATURECONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1; 
ALTER TABLE TEMPERATURECONDITION 
ADD CONSTRAINT TEMPCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON TEMPERATURECONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON TEMPERATURECONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON TEMPERATURECONDITION TO AUXILIARY;

DROP TABLE BIOENTITYCONDITION CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITYCONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL, 
CONSTRAINT BIOENTITYCONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1; 
ALTER TABLE BIOENTITYCONDITION 
ADD CONSTRAINT BIOENTITYCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOENTITYCOND_BIOENT_FK_INDEX ON BIOENTITYCONDITION (BIOENTITY_ID) TABLESPACE DATA1;
ALTER TABLE BIOENTITYCONDITION 
ADD CONSTRAINT BIOENTITYCOND_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITYCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITYCONDITION TO AUXILIARY;

DROP TABLE BIOCONCEPTCONDITION CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPTCONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
BIOCONCEPT_ID INTEGER NOT NULL, 
CONSTRAINT BIOCONCEPTCONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1; 
ALTER TABLE BIOCONCEPTCONDITION 
ADD CONSTRAINT BIOCONCEPTCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOCONCEPTCOND_BIOCON_FK_INDEX ON BIOCONCEPTCONDITION (BIOCONCEPT_ID) TABLESPACE DATA1;
ALTER TABLE BIOCONCEPTCONDITION 
ADD CONSTRAINT BIOCONCEPTCOND_BIOCON_FK FOREIGN KEY (BIOCONCEPT_ID) REFERENCES BIOCONCEPT (BIOCONCEPT_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOCONCEPTCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPTCONDITION TO AUXILIARY;

DROP TABLE BIOITEMCONDITION CASCADE CONSTRAINTS;
CREATE TABLE BIOITEMCONDITION ( 
CONDITION_ID INTEGER NOT NULL, 
BIOITEM_ID INTEGER NOT NULL, 
CONSTRAINT BIOITEMCONDITION_PK PRIMARY KEY (CONDITION_ID) ) TABLESPACE DATA1; 
ALTER TABLE BIOITEMCONDITION 
ADD CONSTRAINT BIOITEMCOND_COND_FK FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX BIOITEMCOND_BIOENT_FK_INDEX ON BIOITEMCONDITION (BIOITEM_ID) TABLESPACE DATA1;
ALTER TABLE BIOITEMCONDITION 
ADD CONSTRAINT BIOITEMCOND_BIOITEM_FK FOREIGN KEY (BIOITEM_ID) REFERENCES BIOITEM (BIOITEM_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOITEMCONDITION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOITEMCONDITION TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOITEMCONDITION TO AUXILIARY;

/* Paragraph */
DROP TABLE PARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE PARAGRAPH ( 
PARAGRAPH_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
OBJ_URL VARCHAR2(500), 
SOURCE_ID INTEGER NOT NULL, 
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('REGULATION', 'GO')),
TEXT CLOB NOT NULL, 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT PARAGRAPH_PK PRIMARY KEY (PARAGRAPH_ID),
CONSTRAINT PARAGRAPH_UK UNIQUE (BIOENTITY_ID, SUBCLASS),
CONSTRAINT PARAGRAPH_FORMAT_UK UNIQUE (FORMAT_NAME, SUBCLASS)  ) TABLESPACE DATA1;
ALTER TABLE PARAGRAPH 
ADD CONSTRAINT PARA_BIOENT_FK FOREIGN KEY (BIOENTITY_ID) REFERENCES BIOENTITY (BIOENTITY_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX PARA_SOURCE_FK_INDEX ON PARAGRAPH (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE PARAGRAPH
ADD CONSTRAINT PARA_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE PARA_SEQ;
CREATE SEQUENCE PARA_SEQ NOCACHE;
GRANT SELECT ON PARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH TO AUXILIARY;

DROP TABLE PARAGRAPH_REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE PARAGRAPH_REFERENCE ( 
PARAGRAPH_REFERENCE_ID INTEGER NOT NULL, 
PARAGRAPH_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER NOT NULL, 
SOURCE_ID INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('REGULATION')), 
DATE_CREATED DATE DEFAULT SYSDATE NOT NULL, 
CREATED_BY VARCHAR2(12) DEFAULT SUBSTR(USER,1,12) NOT NULL, 
CONSTRAINT PARAGRAPH_REFERENCE_PK PRIMARY KEY (PARAGRAPH_REFERENCE_ID), 
CONSTRAINT PARAGRAPH_REFERENCE_UK UNIQUE (PARAGRAPH_ID, REFERENCE_ID) ) TABLESPACE DATA1;
CREATE INDEX PARAREF_REF_FK_INDEX ON PARAGRAPH_REFERENCE (REFERENCE_ID) TABLESPACE DATA1;
ALTER TABLE PARAGRAPH_REFERENCE 
ADD CONSTRAINT PARAREF_PARA_FK FOREIGN KEY (PARAGRAPH_ID) REFERENCES PARAGRAPH (PARAGRAPH_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
ALTER TABLE PARAGRAPH_REFERENCE 
ADD CONSTRAINT PARAREF_REF_FK FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
CREATE INDEX PARAREF_SOURCE_FK_INDEX ON PARAGRAPH_REFERENCE (SOURCE_ID) TABLESPACE DATA1;
ALTER TABLE PARAGRAPH_REFERENCE 
ADD CONSTRAINT PARAREF_SOURCE_FK FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID) 
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
DROP SEQUENCE PARAREF_SEQ;
CREATE SEQUENCE PARAREF_SEQ NOCACHE;
GRANT SELECT ON PARAGRAPH_REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH_REFERENCE TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON PARAGRAPH_REFERENCE TO AUXILIARY;

/* Auxiliary */
DROP TABLE AUX_DISAMBIG CASCADE CONSTRAINTS;
CREATE TABLE AUX_DISAMBIG ( 
AUX_DISAMBIG_ID INTEGER NOT NULL, 
DISAMBIG_KEY VARCHAR2(200) NOT NULL, 
CLASS VARCHAR(40) NOT NULL CHECK (CLASS IN ('BIOENTITY', 'BIOCONCEPT', 'REFERENCE', 'CHEMICAL', 'AUTHOR')),
SUBCLASS VARCHAR(40) CHECK (SUBCLASS IN ('LOCUS', 'PROTEIN', 'GO', 'PHENOTYPE', 'EC_NUMBER', 'COMPLEX')),
OBJ_ID INTEGER NOT NULL, 
CONSTRAINT AUX_DISAMBIG_PK PRIMARY KEY (AUX_DISAMBIG_ID), 
CONSTRAINT AUX_DISAMBIG_UK UNIQUE (DISAMBIG_KEY, CLASS, SUBCLASS) ) TABLESPACE DATA1;
CREATE INDEX AUX_DISAMBIG_OBJID_INDEX ON AUX_DISAMBIG (OBJ_ID) TABLESPACE DATA1;
DROP SEQUENCE AUX_DISAMBIG_SEQ;
CREATE SEQUENCE AUX_DISAMBIG_SEQ NOCACHE;
GRANT SELECT ON AUX_DISAMBIG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_DISAMBIG TO AUXILIARY;

DROP TABLE AUX_LOCUSTABS CASCADE CONSTRAINTS;
CREATE TABLE AUX_LOCUSTABS ( 
BIOENTITY_ID INTEGER NOT NULL, 
SUMMARY NUMBER(1) NOT NULL,
SEQ NUMBER(1) NOT NULL,
HISTORY NUMBER(1) NOT NULL, 
LITERATURE NUMBER(1) NOT NULL, 
GO NUMBER(1) NOT NULL, 
PHENOTYPE NUMBER(1) NOT NULL, 
INTERACTIONS NUMBER(1) NOT NULL, 
EXPRESSION NUMBER(1) NOT NULL, 
REGULATION NUMBER(1) NOT NULL, 
PROTEIN NUMBER(1) NOT NULL, 
WIKI NUMBER(1) NOT NULL, 
CONSTRAINT AUX_LOCUSTABS_PK PRIMARY KEY (BIOENTITY_ID) ) TABLESPACE DATA1;
GRANT SELECT ON AUX_LOCUSTABS TO DBSELECT;
GRANT INSERT, SELECT, UPDATE ON AUX_LOCUSTABS TO CURATOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_LOCUSTABS TO AUXILIARY;

DROP TABLE AUX_INTERACTION CASCADE CONSTRAINTS;
CREATE TABLE AUX_INTERACTION ( 
AUX_INTERACTION_ID INTEGER NOT NULL, 
FORMAT_NAME VARCHAR2(100) NOT NULL, 
DISPLAY_NAME VARCHAR2(500) NOT NULL, 
BIOENTITY_SUBCLASS VARCHAR2(40) NOT NULL CHECK (BIOENTITY_SUBCLASS IN ('GENINTERACTION', 'PHYSINTERACTION', 'REGULATION')), 
BIOENTITY1_ID INTEGER NOT NULL, 
BIOENTITY2_ID INTEGER NOT NULL, 
EVIDENCE_COUNT INTEGER NOT NULL, 
CONSTRAINT AUX_INTERACTION_PK PRIMARY KEY (AUX_INTERACTION_ID), 
CONSTRAINT AUX_INTERACTION_CLASS_UK UNIQUE (BIOENTITY1_ID, BIOENTITY2_ID, BIOENTITY_SUBCLASS), 
CONSTRAINT AUX_INTERACTION_FORMATNAME_UK UNIQUE (FORMAT_NAME, BIOENTITY_SUBCLASS) ) TABLESPACE DATA2;
CREATE INDEX AUX_INTERACTION_BIOENT2_INDEX ON AUX_INTERACTION (BIOENTITY2_ID) TABLESPACE DATA2;
DROP SEQUENCE AUX_INTERACTION_SEQ;
CREATE SEQUENCE AUX_INTERACTION_SEQ NOCACHE;
GRANT SELECT ON AUX_INTERACTION TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_INTERACTION TO AUXILIARY;

DROP TABLE AUX_BIOENTITY_REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE AUX_BIOENTITY_REFERENCE ( 
AUX_BIOENTITY_REFERENCE_ID INTEGER, 
BIOENTITY_ID INTEGER NOT NULL, 
REFERENCE_ID INTEGER NOT NULL, 
BIOENTITY_SUBCLASS VARCHAR2(40) NOT NULL CHECK (BIOENTITY_SUBCLASS IN ('PHYSINTERACTION', 'GENINTERACTION', 'PHENOTYPE', 'GO', 'EC_NUMBER', 'PRIMARY_LITERATURE', 'ADDITIONAL_LITERATURE', 'REVIEW_LITERATURE', 'OMICS_LITERATURE', 'REGULATION')), 
CONSTRAINT AUX_BIOENTITY_REFERENCE_PK PRIMARY KEY (AUX_BIOENTITY_REFERENCE_ID), 
CONSTRAINT AUX_BIOENTITY_REFERENCE_UK UNIQUE (BIOENTITY_ID, REFERENCE_ID, BIOENTITY_SUBCLASS) ) TABLESPACE DATA1;
CREATE INDEX AUX_BIOENTREF_REF_INDEX ON AUX_BIOENTITY_REFERENCE (REFERENCE_ID) TABLESPACE DATA1;
DROP SEQUENCE AUX_BIOENTITY_REFERENCE_SEQ;
CREATE SEQUENCE AUX_BIOENTITY_REFERENCE_SEQ NOCACHE;
GRANT SELECT ON AUX_BIOENTITY_REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_BIOENTITY_REFERENCE TO AUXILIARY;

DROP TABLE AUX_BIOFACT CASCADE CONSTRAINTS;
CREATE TABLE AUX_BIOFACT ( 
AUX_BIOFACT_ID INTEGER NOT NULL, 
BIOENTITY_ID INTEGER NOT NULL, 
BIOCONCEPT_ID INTEGER NOT NULL, 
BIOENTITY_SUBCLASS VARCHAR2(40) NOT NULL CHECK (BIOENTITY_SUBCLASS IN ('LOCUS', 'PROTEIN', 'COMPLEX')),
BIOCONCEPT_SUBCLASS VARCHAR2(40) NOT NULL CHECK (BIOCONCEPT_SUBCLASS IN ('GO', 'PHENOTYPE', 'EC_NUMBER')),
CONSTRAINT AUX_BIOFACT_PK PRIMARY KEY (AUX_BIOFACT_ID), 
CONSTRAINT AUX_BIOFACT_UK UNIQUE (BIOCONCEPT_ID, BIOENTITY_ID, BIOCONCEPT_SUBCLASS, BIOENTITY_SUBCLASS) ) TABLESPACE DATA1;
CREATE INDEX AUX_BIOFACT_BIOCON_INDEX ON AUX_BIOFACT (BIOCONCEPT_ID) TABLESPACE DATA1;
CREATE INDEX AUX_BIOFACT_BIOENT_INDEX ON AUX_BIOFACT (BIOENTITY_ID) TABLESPACE DATA1;
DROP SEQUENCE AUX_BIOFACT_SEQ;
CREATE SEQUENCE AUX_BIOFACT_SEQ NOCACHE;
GRANT SELECT ON AUX_BIOFACT TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_BIOFACT TO AUXILIARY;

DROP TABLE AUX_BIOCONCEPT_COUNT CASCADE CONSTRAINTS;
CREATE TABLE AUX_BIOCONCEPT_COUNT ( 
BIOCONCEPT_ID INTEGER NOT NULL, 
GENECOUNT INTEGER NOT NULL,
CHILD_GENE_COUNT INTEGER NOT NULL,
SUBCLASS VARCHAR2(40) NOT NULL CHECK (SUBCLASS IN ('GO', 'PHENOTYPE', 'EC_NUMBER')),
CONSTRAINT AUX_BIOCON_COUNT_PK PRIMARY KEY (BIOCONCEPT_ID) ) TABLESPACE DATA1;
GRANT SELECT ON AUX_BIOCONCEPT_COUNT TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_BIOCONCEPT_COUNT TO AUXILIARY;

DROP TABLE AUX_CHEMICAL_COUNT CASCADE CONSTRAINTS;
CREATE TABLE AUX_CHEMICAL_COUNT ( 
CHEMICAL_ID INTEGER NOT NULL, 
GENECOUNT INTEGER NOT NULL,
IS_RELEVANT NUMBER(1) NOT NULL,
CONSTRAINT AUX_CHEM_COUNT_PK PRIMARY KEY (CHEMICAL_ID) ) TABLESPACE DATA1;
GRANT SELECT ON AUX_CHEMICAL_COUNT TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUX_CHEMICAL_COUNT TO AUXILIARY;
