/* Perf_Core */

DROP TABLE BIOENTITY CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY (
BIOENTITY_ID INTEGER NOT NULL, 
JSON VARCHAR2(4000) NOT NULL, 
LOCUSTABS_JSON VARCHAR2(4000),
CONSTRAINT BIOENTITY_PK PRIMARY KEY (BIOENTITY_ID) ) TABLESPACE PDATA1;
GRANT SELECT ON BIOENTITY TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY TO AUXILIARY;

DROP TABLE BIOCONCEPT CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPT ( 
BIOCONCEPT_ID INTEGER NOT NULL, 
JSON VARCHAR2(4000) NOT NULL, 
CONSTRAINT BIOCONCEPT_PK PRIMARY KEY (BIOCONCEPT_ID) ) TABLESPACE PDATA1;
GRANT SELECT ON BIOCONCEPT TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPT TO AUXILIARY;

DROP TABLE REFERENCE CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE ( 
REFERENCE_ID INTEGER NOT NULL, 
JSON VARCHAR2(4000) NOT NULL, 
BIBENTRY_JSON CLOB, 
CONSTRAINT REFERENCE_PK PRIMARY KEY (REFERENCE_ID) ) TABLESPACE PDATA2;
GRANT SELECT ON REFERENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE TO AUXILIARY;

DROP TABLE CHEMICAL CASCADE CONSTRAINTS;
CREATE TABLE CHEMICAL (
CHEMICAL_ID INTEGER NOT NULL,
JSON VARCHAR2(4000) NOT NULL,
CONSTRAINT CHEMICAL_PK PRIMARY KEY (CHEMICAL_ID) ) TABLESPACE PDATA1;
GRANT SELECT ON CHEMICAL TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICAL TO AUXILIARY;

DROP TABLE AUTHOR CASCADE CONSTRAINTS;
CREATE TABLE AUTHOR (
AUTHOR_ID INTEGER NOT NULL,
JSON VARCHAR2(4000) NOT NULL,
CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID) ) TABLESPACE PDATA1;
GRANT SELECT ON AUTHOR TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON AUTHOR TO AUXILIARY;

DROP TABLE DISAMBIG CASCADE CONSTRAINTS;
CREATE TABLE DISAMBIG ( 
DISAMBIG_ID INTEGER NOT NULL, 
DISAMBIG_KEY VARCHAR2(200) NOT NULL, 
CLASS VARCHAR(40) NOT NULL, 
SUBCLASS VARCHAR(40), 
OBJ_ID INTEGER NOT NULL, 
CONSTRAINT DISAMBIG_PK PRIMARY KEY (DISAMBIG_ID), 
CONSTRAINT DISAMBIG_UK UNIQUE (DISAMBIG_KEY, CLASS, SUBCLASS) ) TABLESPACE PDATA2;
GRANT SELECT ON DISAMBIG TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON DISAMBIG TO AUXILIARY;

/* Bioentity */
DROP TABLE BIOENTITY_OVERVIEW CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY_OVERVIEW (
BIOENTITY_OVERVIEW_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('INTERACTION', 'REGULATION', 'LITERATURE', 'GO', 'PHENOTYPE')),
JSON VARCHAR2(4000) NOT NULL,
CONSTRAINT BIOENTITY_OVERVIEW_PK PRIMARY KEY (BIOENTITY_OVERVIEW_ID),
CONSTRAINT BIOENTITY_OVERVIEW_UK UNIQUE (BIOENTITY_ID, CLASS)) TABLESPACE PDATA1;
CREATE INDEX BIOENTITY_OVERVIEW_FK_INDX ON BIOENTITY_OVERVIEW (BIOENTITY_ID) TABLESPACE PDATA1;
GRANT SELECT ON BIOENTITY_OVERVIEW TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY_OVERVIEW TO AUXILIARY;
DROP SEQUENCE BIOENTITY_OVERVIEW_SEQ;
CREATE SEQUENCE BIOENTITY_OVERVIEW_SEQ NOCACHE;

DROP TABLE BIOENTITY_GRAPH CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY_GRAPH (
BIOENTITY_GRAPH_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('INTERACTION', 'REGULATION', 'LITERATURE', 'GO', 'PHENOTYPE')),
JSON CLOB NOT NULL,
CONSTRAINT BIOENTITY_GRAPH_PK PRIMARY KEY (BIOENTITY_GRAPH_ID),
CONSTRAINT BIOENTITY_GRAPH_UK UNIQUE (BIOENTITY_ID, CLASS)) TABLESPACE PDATA1;
CREATE INDEX BIOENTITY_GRAPH_FK_INDX ON BIOENTITY_GRAPH (BIOENTITY_ID) TABLESPACE PDATA1;
GRANT SELECT ON BIOENTITY_GRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY_GRAPH TO AUXILIARY;
DROP SEQUENCE BIOENTITY_GRAPH_SEQ;
CREATE SEQUENCE BIOENTITY_GRAPH_SEQ NOCACHE;

DROP TABLE BIOENTITY_RESOURCES CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY_RESOURCES (
BIOENTITY_RESOURCES_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('INTERACTION', 'PHENOTYPE')),
JSON VARCHAR2(4000) NOT NULL,
CONSTRAINT BIOENTITY_RESOURCES_PK PRIMARY KEY (BIOENTITY_RESOURCES_ID),
CONSTRAINT BIOENTITY_RESOURCES_UK UNIQUE (BIOENTITY_ID, CLASS)) TABLESPACE PDATA1;
CREATE INDEX BIOENTITY_RESOURCES_FK_INDX ON BIOENTITY_RESOURCES (BIOENTITY_ID) TABLESPACE PDATA1;
GRANT SELECT ON BIOENTITY_RESOURCES TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY_RESOURCES TO AUXILIARY;
DROP SEQUENCE BIOENTITY_RESOURCES_SEQ;
CREATE SEQUENCE BIOENTITY_RESOURCES_SEQ NOCACHE;

DROP TABLE BIOENTITY_ENRICHMENT CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY_ENRICHMENT (
BIOENTITY_ENRICHMENT_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('REGULATION_TARGET')),
JSON VARCHAR2(4000) NOT NULL,
CONSTRAINT BIOENTITY_ENRICHMENT_PK PRIMARY KEY (BIOENTITY_ENRICHMENT_ID),
CONSTRAINT BIOENTITY_ENRICHMENT_UK UNIQUE (BIOENTITY_ID, CLASS)) TABLESPACE PDATA1;
CREATE INDEX BIOENTITY_ENRICHMENT_FK_INDX ON BIOENTITY_ENRICHMENT (BIOENTITY_ID) TABLESPACE PDATA1;
GRANT SELECT ON BIOENTITY_ENRICHMENT TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY_ENRICHMENT TO AUXILIARY;
DROP SEQUENCE BIOENTITY_ENRICHMENT_SEQ;
CREATE SEQUENCE BIOENTITY_ENRICHMENT_SEQ NOCACHE;

DROP TABLE BIOENTITY_PARAGRAPH CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY_PARAGRAPH (
BIOENTITY_PARAGRAPH_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('REGULATION')),
JSON CLOB NOT NULL,
CONSTRAINT BIOENTITY_PARAGRAPH_PK PRIMARY KEY (BIOENTITY_PARAGRAPH_ID),
CONSTRAINT BIOENTITY_PARAGRAPH_UK UNIQUE (BIOENTITY_ID, CLASS)) TABLESPACE PDATA1;
CREATE INDEX BIOENTITY_PARAGRAPH_FK_INDX ON BIOENTITY_PARAGRAPH (BIOENTITY_ID) TABLESPACE PDATA1;
GRANT SELECT ON BIOENTITY_PARAGRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY_PARAGRAPH TO AUXILIARY;
DROP SEQUENCE BIOENTITY_PARAGRAPH_SEQ;
CREATE SEQUENCE BIOENTITY_PARAGRAPH_SEQ NOCACHE;

/* Bioconcept */

DROP TABLE BIOCONCEPT_GRAPH CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPT_GRAPH (
BIOCONCEPT_GRAPH_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('ONTOLOGY')),
JSON CLOB NOT NULL,
CONSTRAINT BIOCONCEPT_GRAPH_PK PRIMARY KEY (BIOCONCEPT_GRAPH_ID),
CONSTRAINT BIOCONCEPT_GRAPH_UK UNIQUE (BIOCONCEPT_ID, CLASS)) TABLESPACE PDATA1;
CREATE INDEX BIOCONCEPT_GRAPH_FK_INDX ON BIOCONCEPT_GRAPH (BIOCONCEPT_ID) TABLESPACE PDATA1;
GRANT SELECT ON BIOCONCEPT_GRAPH TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPT_GRAPH TO AUXILIARY;
DROP SEQUENCE BIOCONCEPT_GRAPH_SEQ;
CREATE SEQUENCE BIOCONCEPT_GRAPH_SEQ NOCACHE;

/* Evidence */

DROP TABLE EVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE EVIDENCE (
EVIDENCE_ID INTEGER NOT NULL,
JSON VARCHAR2(4000) NOT NULL,
CONSTRAINT EVIDENCE_PK PRIMARY KEY (EVIDENCE_ID) ) TABLESPACE PDATA2;
GRANT SELECT ON EVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON EVIDENCE TO AUXILIARY;

DROP TABLE BIOENTITY_EVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE BIOENTITY_EVIDENCE (
BIOENTITY_EVIDENCE_ID INTEGER NOT NULL,
BIOENTITY_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('INTERACTION', 'REGULATION', 'LITERATURE', 'GO', 'PHENOTYPE', 'BINDING', 'DOMAIN')),
EVIDENCE_ID INTEGER NOT NULL,
CONSTRAINT BIOENTITY_EVIDENCE_PK PRIMARY KEY (BIOENTITY_EVIDENCE_ID),
CONSTRAINT BIOENTITY_EVIDENCE_UK UNIQUE (BIOENTITY_ID, CLASS, EVIDENCE_ID)) TABLESPACE PDATA2;
CREATE INDEX BIOENTITY_EVIDENCE_FK_INDX ON BIOENTITY_EVIDENCE (EVIDENCE_ID) TABLESPACE PDATA2;
CREATE INDEX BIOENTITY_EVIDENCE_Q_INDX ON BIOENTITY_EVIDENCE (BIOENTITY_ID, CLASS) TABLESPACE PDATA2;
ALTER TABLE BIOENTITY_EVIDENCE
ADD CONSTRAINT BIOENTITY_EVIDENCE_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOENTITY_EVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOENTITY_EVIDENCE TO AUXILIARY;
DROP SEQUENCE BIOENTITY_EVIDENCE_SEQ;
CREATE SEQUENCE BIOENTITY_EVIDENCE_SEQ NOCACHE;

DROP TABLE BIOCONCEPT_EVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE BIOCONCEPT_EVIDENCE (
BIOCONCEPT_EVIDENCE_ID INTEGER NOT NULL,
BIOCONCEPT_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('LOCUS', 'LOCUS_ALL_CHILDREN')),
EVIDENCE_ID INTEGER NOT NULL,
CONSTRAINT BIOCONCEPT_EVIDENCE_PK PRIMARY KEY (BIOCONCEPT_EVIDENCE_ID),
CONSTRAINT BIOCONCEPT_EVIDENCE_UK UNIQUE (BIOCONCEPT_ID, CLASS, EVIDENCE_ID)) TABLESPACE PDATA2;
CREATE INDEX BIOCONCEPT_EVIDENCE_FK_INDX ON BIOCONCEPT_EVIDENCE (EVIDENCE_ID) TABLESPACE PDATA2;
CREATE INDEX BIOCONCEPT_EVIDENCE_Q_INDX ON BIOCONCEPT_EVIDENCE (BIOCONCEPT_ID, CLASS) TABLESPACE PDATA2;
ALTER TABLE BIOCONCEPT_EVIDENCE
ADD CONSTRAINT BIOCONCEPT_EVIDENCE_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON BIOCONCEPT_EVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON BIOCONCEPT_EVIDENCE TO AUXILIARY;
DROP SEQUENCE BIOCONCEPT_EVIDENCE_SEQ;
CREATE SEQUENCE BIOCONCEPT_EVIDENCE_SEQ NOCACHE;

DROP TABLE REFERENCE_EVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE REFERENCE_EVIDENCE (
REFERENCE_EVIDENCE_ID INTEGER NOT NULL,
REFERENCE_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('INTERACTION', 'REGULATION', 'LITERATURE', 'GO', 'PHENOTYPE')),
EVIDENCE_ID INTEGER NOT NULL,
CONSTRAINT REFERENCE_EVIDENCE_PK PRIMARY KEY (REFERENCE_EVIDENCE_ID),
CONSTRAINT REFERENCE_EVIDENCE_UK UNIQUE (REFERENCE_ID, CLASS, EVIDENCE_ID)) TABLESPACE PDATA2;
CREATE INDEX REFERENCE_EVIDENCE_FK_INDX ON REFERENCE_EVIDENCE (EVIDENCE_ID) TABLESPACE PDATA2;
CREATE INDEX REFERENCE_EVIDENCE_Q_INDX ON REFERENCE_EVIDENCE (REFERENCE_ID, CLASS) TABLESPACE PDATA2;
ALTER TABLE REFERENCE_EVIDENCE
ADD CONSTRAINT REFERENCE_EVIDENCE_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON REFERENCE_EVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON REFERENCE_EVIDENCE TO AUXILIARY;
DROP SEQUENCE REFERENCE_EVIDENCE_SEQ;
CREATE SEQUENCE REFERENCE_EVIDENCE_SEQ NOCACHE;

DROP TABLE CHEMICAL_EVIDENCE CASCADE CONSTRAINTS;
CREATE TABLE CHEMICAL_EVIDENCE (
CHEMICAL_EVIDENCE_ID INTEGER NOT NULL,
CHEMICAL_ID INTEGER NOT NULL,
CLASS VARCHAR2(40) NOT NULL CHECK (CLASS IN ('PHENOTYPE')),
EVIDENCE_ID INTEGER NOT NULL,
CONSTRAINT CHEMICAL_EVIDENCE_PK PRIMARY KEY (CHEMICAL_EVIDENCE_ID),
CONSTRAINT CHEMICAL_EVIDENCE_UK UNIQUE (CHEMICAL_ID, CLASS, EVIDENCE_ID)) TABLESPACE PDATA2;
CREATE INDEX CHEMICAL_EVIDENCE_FK_INDX ON CHEMICAL_EVIDENCE (EVIDENCE_ID) TABLESPACE PDATA2;
CREATE INDEX CHEMICAL_EVIDENCE_Q_INDX ON CHEMICAL_EVIDENCE (CHEMICAL_ID, CLASS) TABLESPACE PDATA2;
ALTER TABLE CHEMICAL_EVIDENCE
ADD CONSTRAINT CHEMICAL_EVIDENCE_FK FOREIGN KEY (EVIDENCE_ID) REFERENCES EVIDENCE (EVIDENCE_ID)
ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE VALIDATE;
GRANT SELECT ON CHEMICAL_EVIDENCE TO DBSELECT;
GRANT DELETE, INSERT, SELECT, UPDATE ON CHEMICAL_EVIDENCE TO AUXILIARY;
DROP SEQUENCE CHEMICAL_EVIDENCE_SEQ;
CREATE SEQUENCE CHEMICAL_EVIDENCE_SEQ NOCACHE;